'use strict';
// Actual Chromium controls; simulated IPC/runtime, not a Windows routing test.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {Store}=require('../src/main/store.cjs'),{Library}=require('../src/main/library.cjs'),{Workspace}=require('../src/main/workspace.cjs'),{prepareSettings,createInstance}=require('../src/main/operations.cjs'),{environment}=require('../src/main/environment.cjs');
(async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'arena-ux-renderer-')),store=new Store(root),library=new Library(root,store),workspace=new Workspace(root);let browser,page;const results=[],errors=[],states=new Map(),calls=[],diagnosticRequests=[];let diag={job:null,lastJob:null,results:[]},failStart=false,activeId=null;
const a=store.create('工作实例 A'),b=store.create('工作实例 B');states.set(a.id,'running');states.set(b.id,'stopped');
await library.save({name:'测试订阅',text:JSON.stringify({proxies:[1,2,3].map(i=>({name:'Node '+i,type:'http',server:'127.0.0.1',port:9000+i}))})});
const snap=()=>({...workspace.snapshot(library),versions:{app:'test',electron:'simulated IPC'},coreInstalled:true,activeId,creationProgress:c.creationProgress||null,library:library.summaries(),diagnostics:diag,instances:store.list().map(x=>({...x,status:states.get(x.id)||'stopped',nodes:store.nodes(x.id).map(n=>n.name),logs:[],assignment:{status:'未关联来源'},pageState:'未打开网页',error:'',currentURL:x.url}))});
const emit=()=>{if(page&&!page.isClosed())page.evaluate(s=>window.__stateListener?.(s),snap()).catch(()=>{});};
const c={store,library,workspace,emit,choose(id){activeId=id;emit();},log(id,text,level='INFO'){workspace.log('instance',text,level,id);emit();},diagnostics:{timezone:async()=>({timezone:'Europe/Berlin'})},start:async id=>{if(failStart){states.set(id,'error');throw Error('合成启动故障');}states.set(id,'running');emit();}};
try{browser=await chromium.launch({headless:true,args:['--no-sandbox']});page=await browser.newPage({viewport:{width:1440,height:960}});page.on('pageerror',e=>errors.push(e.message));
await page.exposeFunction('__testRequest',async(action,m={})=>{calls.push(action);try{let value;switch(action){
case 'snapshot':return {ok:true,value:snap()};case 'activate':activeId=m.id;break;case 'layout':return {ok:true};
case 'settings':{await new Promise(r=>setTimeout(r,70));const p=prepareSettings(store,m.id,m.patch);if(p.changed){states.set(m.id,'stopped');store.update(m.id,p.next);}value={changed:p.changed};break;}
case 'fingerprint-preset':return {ok:true,value:environment(require('../src/main/fingerprint.cjs').preset(m.preset,environment(m.environment)))};
case 'environment-timezone':return {ok:true,value:{timezone:'Europe/Berlin'}};case 'start':await c.start(m.id);break;case 'stop':states.set(m.id,'stopped');break;
case 'create':{const r=await createInstance(c,m);value=m.detailed?r:r.id;break;}
case 'library-assign':{const node=library.node(m.sourceId,m.name);states.set(m.id,'stopped');store.saveNodes(m.id,[node],null,{sourceId:m.sourceId,name:m.name});store.update(m.id,{network:{mode:'mihomo',nodeName:node.name}});break;}
case 'diagnostic-start':{diagnosticRequests.push(m);const id='task-'+diagnosticRequests.length;diag.lastJob={id,kind:m.kind,total:m.items.length,endedAt:new Date().toISOString(),items:m.items.map((x,i)=>({...x,state:i===1?'failed':'success'}))};diag.results=m.items.map((x,i)=>({...x,taskId:id,kind:m.kind,at:new Date().toISOString(),ok:i!==1,latencyMs:12,error:i===1?'检测目标无法完成请求':''}));workspace.log('diagnostic','开始latency检测：'+m.items.length+'个节点','INFO',null,{taskId:id});break;}
default:throw Error('Unmocked action '+action);}emit();return {ok:true,value};}catch(e){return {ok:false,error:e.message};}});
await page.addInitScript(()=>{window.arenaCore={request:(a,p)=>window.__testRequest(a,p),onState:fn=>window.__stateListener=fn};});
await page.goto('file://'+path.resolve(__dirname,'../src/renderer/index.html'));await page.waitForSelector('[role=tab]');
const ok=name=>{results.push(name);console.log('PASS',name);};

await page.evaluate(()=>{localStorage.setItem('arena.ui.theme','invalid');localStorage.setItem('arena.ui.sidebar','invalid');});await page.reload();await page.waitForSelector('[role=tab]');assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');assert.equal(await page.evaluate(()=>document.documentElement.dataset.sidebar),'expanded');ok('Invalid saved appearance preferences fall back to light and expanded');
const contrast=async selector=>page.locator(selector).evaluate(e=>{
 const rgb=c=>c.match(/[\d.]+/g).slice(0,3).map(Number),lum=c=>rgb(c).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);
 const style=getComputedStyle(e,'::placeholder'),bg=getComputedStyle(e).backgroundColor,a=lum(style.color),b=lum(bg);return {ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),opacity:style.opacity,bg,fg:style.color};
});
await page.locator('[data-quick="manage"]').click();let ratio=await contrast('#quickLinkURL');assert(ratio.ratio>=4.5,JSON.stringify(ratio));await page.locator('[data-quick="close"]').click();
await page.locator('#themeToggle').click();await page.locator('[data-quick="manage"]').click();ratio=await contrast('#quickLinkURL');assert(ratio.ratio>=4.5,JSON.stringify(ratio));assert.equal(ratio.opacity,'1');await page.locator('[data-quick="close"]').click();ok('Shortcut URL placeholder meets 4.5:1 contrast in day and night modes');
await page.locator('#sidebarToggle').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#sidebarToggle').getAttribute('aria-expanded'),'false');await page.locator('#sidebar [data-view="environment"]').click();await page.waitForSelector('#timezone');await page.locator('#timezone').fill('Europe/London');await page.locator('#themeToggle').click();await page.locator('#sidebarToggle').click();assert.equal(await page.locator('#timezone').inputValue(),'Europe/London');assert.equal(store.get(a.id).environment.timezone,'Asia/Tokyo');await page.locator('#timezone').fill('Asia/Tokyo');ok('Keyboard sidebar control and theme changes preserve an unsaved environment draft');
await page.locator('#themeToggle').click();await page.evaluate(()=>route('proxies'));await page.evaluate(()=>openIPBookmarks('ips'));ratio=await contrast('#ipEditorIP');assert(ratio.ratio>=4.5,JSON.stringify(ratio));const routeBefore=await page.evaluate(()=>({view,activeId}));await page.locator('[data-favorite-tab="nodes"]').click();ratio=await contrast('#unifiedSearch');assert(ratio.ratio>=4.5,JSON.stringify(ratio));await page.locator('[data-favorite-tab="ips"]').click();assert.deepEqual(await page.evaluate(()=>({view,activeId})),routeBefore);await page.locator('[data-bookmark="close"]').click();ok('Night favorite placeholders remain readable and tabs do not change instance route');
await page.evaluate(()=>route('browser'));await page.locator('[data-quick="manage"]').click();await page.locator('#quickLinkName').fill('保留的草稿');await page.locator('#quickLinkURL').fill('https://example.test/draft');
for(const [width,height] of [[960,700],[1280,800],[1440,960]]){await page.setViewportSize({width,height});await page.evaluate(()=>render());assert.equal(await page.locator('#quickLinkName').inputValue(),'保留的草稿');const box=await page.locator('#quickLinksDialog').boundingBox();assert(box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=height+1);assert(await page.locator('[data-quick="close"]').isVisible());}
await page.keyboard.press('Escape');assert.equal(await page.locator('#quickLinksDialog').evaluate(e=>e.open),false);ok('Night quick-link dialog fits three sizes, preserves draft across refresh and closes with Escape');
await page.evaluate(()=>{const e=document.createElement('input');e.id='auditInvalid';e.setAttribute('aria-invalid','true');document.querySelector('#content').append(e);});const border=await page.locator('#auditInvalid').evaluate(e=>getComputedStyle(e).borderTopColor);assert.equal(border,'rgb(255, 157, 172)');await page.locator('#auditInvalid').evaluate(e=>e.remove());ok('Night invalid-field indicator keeps its error color');
while(workspace.data.quickLinks.length<20)workspace.saveQuickLink({name:'长名称快捷网站测试'+workspace.data.quickLinks.length,url:'https://example.test/'});await page.evaluate(s=>{state=s;render();},snap());
for(const collapsed of [false,true]){if((await page.locator('#sidebarToggle').getAttribute('aria-expanded')==='false')!==collapsed)await page.locator('#sidebarToggle').click();for(const [width,height] of [[960,700],[1280,800],[1440,960]]){await page.setViewportSize({width,height});assert(await page.locator('[data-quick="manage"]').isVisible());assert(await page.evaluate(()=>{const r=document.querySelector('[data-quick="manage"]').getBoundingClientRect(),t=document.querySelector('#workspaceHead .toolbar').getBoundingClientRect();return r.right<=t.left+1&&document.documentElement.scrollWidth<=innerWidth;}));}}
ok('Twenty shortcut labels retain management access at three sizes with either sidebar width');
await page.addInitScript(()=>{Storage.prototype.getItem=function(){throw Error('storage unavailable')};Storage.prototype.setItem=function(){throw Error('storage unavailable')};});await page.reload();await page.waitForSelector('[role=tab]');assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');await page.locator('#themeToggle').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');await page.locator('#sidebarToggle').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.sidebar),'collapsed');ok('Unavailable preference storage does not block appearance controls or startup');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'appearance-audit-results.json'),JSON.stringify({platform:process.platform,backend:'simulated IPC and runtime; actual Store/validation',passed:results.length,results,errors},null,2)+'\n');console.log('All renderer tests passed:',results.length);
}catch(e){console.error('Renderer errors',errors);if(page)await page.screenshot({path:path.join(__dirname,'appearance-audit-failure.png')}).catch(()=>{});throw e;}finally{await browser?.close();fs.rmSync(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exit(1);});
