'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {Store,atomic}=require('../src/main/store.cjs');
const journal=require('../src/main/deletion-journal.cjs');
const batch=require('../src/main/batch-operations.cjs');
function temp(){return fs.mkdtempSync(path.join(os.tmpdir(),'facet-data-'));}
test('atomic writes keep a previous generation and recover a corrupt primary',()=>{const dir=temp(),file=path.join(dir,'settings.json');try{atomic(file,{version:1,value:'one'});atomic(file,{version:1,value:'two'});assert.equal(JSON.parse(fs.readFileSync(file+'.bak')).value,'one');fs.writeFileSync(file,'{broken');const backup=JSON.parse(fs.readFileSync(file+'.bak'));fs.copyFileSync(file+'.bak',file);assert.equal(JSON.parse(fs.readFileSync(file)).value,backup.value);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('Store accepts early array migration and rejects invalid network without direct fallback',()=>{const dir=temp();try{const first=new Store(dir),x=first.create('Migrated');const file=first.file,data=JSON.parse(fs.readFileSync(file,'utf8'));fs.writeFileSync(file,JSON.stringify(data.instances));assert.equal(new Store(dir).get(x.id).name,'Migrated');const bad=JSON.parse(fs.readFileSync(file,'utf8'));bad[0].network.mode='mihomO';fs.writeFileSync(file,JSON.stringify(bad));assert.throws(()=>new Store(dir),/网络配置无效/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('deletion journal is durable, idempotent and can be finalized',()=>{const dir=temp(),id='11111111-1111-4111-8111-111111111111';try{const row=journal.begin(dir,id);assert.equal(journal.list(dir).length,1);journal.update(dir,id,{steps:{metadata:'done'}});assert.equal(journal.list(dir)[0].steps.metadata,'done');assert(journal.finish(dir,id));assert.equal(journal.finish(dir,id),true);assert.equal(journal.list(dir).length,0);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('batch operation records per-instance status and supports retry state',()=>{const dir=temp();try{const row=batch.begin(dir,[{id:'11111111-1111-4111-8111-111111111111',sourceId:'s',name:'n1'},{id:'22222222-2222-4222-8222-222222222222',sourceId:'s',name:'n2'}]);batch.update(dir,row.operationId,0,{status:'success'});batch.update(dir,row.operationId,1,{status:'failed',error:'temporary'});const loaded=batch.read(dir,row.operationId);assert.deepEqual(loaded.items.map(x=>x.status),['success','failed']);assert.equal(batch.list(dir).length,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
