'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {prepareSettings,createInstance}=require('../src/main/operations.cjs');const {environment}=require('../src/main/environment.cjs');
function fixture(){const rows=[],events=[];const c={store:{create(name,network,plannedEnvironment){const x={id:'fixture',name,network:network||{mode:'direct',nodeName:''},environment:environment(plannedEnvironment)};rows.push(x);return x;},get(id){const x=rows.find(x=>x.id===id);if(!x)throw Error('missing');return x;},nodes:()=>[],saveNodes(){},update(id,patch){Object.assign(this.get(id),patch);}},library:{node:()=>({name:'node'})},diagnostics:{timezone:async()=>({timezone:'Europe/Berlin'})},emit(){},choose(){},log(id,text){events.push({id,text});},start:async()=>{}};return {c,rows,events};}
test('invalid network and environment rejected before lifecycle mutation',()=>{const {c}=fixture();const x=c.store.create('x');assert.throws(()=>prepareSettings(c.store,x.id,{network:{mode:'mihomo',nodeName:'missing'}}),/节点/);assert.throws(()=>prepareSettings(c.store,x.id,{network:{mode:'auto'}}),/网络模式/);assert.throws(()=>prepareSettings(c.store,x.id,{environment:{timezone:'not-a-zone'}}),/时区/);});
test('normalized unchanged settings are a no-op',()=>{const {c}=fixture(),x=c.store.create('x');assert.equal(prepareSettings(c.store,x.id,{network:x.network,environment:x.environment}).changed,false);assert.equal(prepareSettings(c.store,x.id,{environment:{...x.environment,cpu:4}}).changed,true);});
test('created instance remains successful when its startup fails',async()=>{const {c,rows}=fixture();c.start=async()=>{throw Error('fixture start failure');};const v=await createInstance(c,{name:'x',start:true});assert.equal(v.created,true);assert.equal(v.started,false);assert.match(v.startError,/start failure/);assert.equal(rows.length,1);assert.equal(c.creationProgress,null);});
test('creation persists a generated environment plan before startup',async()=>{const {c,rows}=fixture();const plan=environment(require('../src/main/fingerprint.cjs').preset('random',environment()));const v=await createInstance(c,{name:'random environment',environment:plan,start:false});assert.equal(v.created,true);assert.equal(rows[0].environment.fingerprint.enabled,true);assert.equal(rows[0].environment.fingerprint.template,plan.fingerprint.template);assert.equal(rows[0].environment.fingerprint.seed,plan.fingerprint.seed);});
test('timezone failure reports warning but does not undo creation',async()=>{const {c,rows}=fixture();c.diagnostics.timezone=async()=>{throw Error('invalid response');};const v=await createInstance(c,{name:'x',syncTimezone:true});assert.equal(v.created,true);assert.match(v.timezoneError,/失败/);assert.equal(rows[0].environment.timezone,'Asia/Tokyo');});
test('proxy copy failure never starts the instance directly',async()=>{const {c,rows}=fixture();let started=0;c.store.saveNodes=()=>{throw Error('disk full');};c.start=async()=>started++;const v=await createInstance(c,{name:'x',sourceId:'s',nodeName:'node',start:true});assert.equal(rows[0].network.mode,'mihomo');assert(v.configurationError);assert.equal(started,0);});
test('creation reports phases and prevents overlap',async()=>{const {c}=fixture();const phases=[];c.emit=()=>phases.push(c.creationProgress?.phase);const v=await createInstance(c,{name:'x',syncTimezone:true,start:true});assert(v.started);assert(phases.includes('按所选出口查询时区'));assert(phases.includes('启动已创建的实例'));c.creationProgress={};await assert.rejects(createInstance(c,{name:'y'}),/正在创建/);});
test('deletion waits for native view destruction and closes connections before clearing session data',async()=>{
 const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events');const filename=path.resolve(__dirname,'../src/main/controller.cjs'),realRequire=require('node:module').createRequire(filename);const order=[];let destroyed=false;const wc=new EventEmitter();wc.isDestroyed=()=>destroyed;wc.stop=()=>order.push('stop-load');wc.close=()=>{order.push('close-view');setTimeout(()=>{destroyed=true;order.push('destroyed');wc.emit('destroyed');},20);};
 const fixtureId='00000000-0000-4000-8000-000000000001',fixtureDir=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'arena-experience-delete-'));const electron={session:{fromPartition:()=>({closeAllConnections:async()=>{assert(destroyed);order.push('connections');},clearStorageData:async()=>{assert(destroyed);order.push('storage');},clearCache:async()=>order.push('cache')})}};const module={exports:{}};vm.runInNewContext(fs.readFileSync(filename,'utf8'),{module,require:name=>name==='electron'?electron:realRequire(name),__dirname:path.dirname(filename),setTimeout,clearTimeout,setImmediate});const c=Object.create(module.exports.Controller.prototype);c.dir=fixtureDir;c.runtimes=new Map([[fixtureId,{status:'running',view:{webContents:wc},core:{stop:async()=>order.push('core-stop')}}]]);c.queues=new Map();c.logs=new Map();c.window={contentView:{removeChildView(){}}};c.store={proxyFile:()=>path.join(fixtureDir,'nonexistent-lifecycle-test.json'),remove:()=>order.push('delete-store')};c.extensions={unload:()=>order.push('unload-extensions'),catalog:{forget:()=>order.push('forget-extensions')}};c.workspace={log:()=>{}};c.log=()=>{};c.emit=()=>{};c.activeId=null;await c.remove(fixtureId);assert.deepEqual(order,['unload-extensions','stop-load','close-view','core-stop','destroyed','delete-store','connections','storage','cache','forget-extensions']);assert.equal(c.runtimes.size,0);fs.rmSync(fixtureDir,{recursive:true,force:true});
});
