'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ExtensionCatalog,localPage,extensionIcon}=require('../src/main/extension-catalog.cjs');
function fixture(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'arena-extensions-')),source=path.join(root,'input');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'manifest.json'),JSON.stringify({manifest_version:2,name:'Fixture',version:'1.0',permissions:['storage'],content_scripts:[{matches:['http://example.test/*'],js:['content.js']}],browser_action:{default_popup:'popup.html'}}));fs.writeFileSync(path.join(source,'popup.html'),'<title>Popup</title>');fs.writeFileSync(path.join(source,'content.js'),'console.log("fixture")');try{fn(new ExtensionCatalog(path.join(root,'data')),source,root);}finally{fs.rmSync(root,{recursive:true,force:true});}}
test('import is copied and disabled by default; explicit bindings persist independently',()=>fixture((c,s,root)=>{const row=c.stage(s);assert.equal(c.data.items.length,0);c.accept(row);fs.writeFileSync(path.join(s,'content.js'),'changed');assert.notEqual(fs.readFileSync(path.join(c.folder(row.id),'content.js'),'utf8'),'changed');c.setEnabled('A',row.id,true);assert.deepEqual(c.enabled('B'),[]);assert.deepEqual(new ExtensionCatalog(path.join(root,'data')).enabled('A'),[row.id]);assert.throws(()=>c.remove(row.id));c.setEnabled('A',row.id,false);c.remove(row.id);assert.equal(c.data.items.length,0);}));
test('cancel, duplicate and invalid manifests never enter catalog',()=>fixture((c,s)=>{let row=c.stage(s);c.discard(row);assert.equal(fs.readdirSync(c.base).length,0);row=c.stage(s);c.accept(row);assert.throws(()=>c.stage(s),/已导入/);assert.equal(fs.readdirSync(c.base).length,1);fs.writeFileSync(path.join(s,'manifest.json'),'invalid');assert.throws(()=>c.stage(s),/JSON/);assert.equal(c.data.items.length,1);}));
test('page paths cannot escape extension origin or directory',()=>{for(const bad of ['../a','http://example.test','/a','x\\y','a?x','a#x','%2e%2e/a']){assert.throws(()=>localPage(bad));}assert.equal(localPage('ui/popup/index.html'),'ui/popup/index.html');});
test('symlinks, oversize files, invalid permissions and ancestor imports rejected',()=>fixture((c,s,root)=>{assert.throws(()=>c.stage(root),/父文件夹/);let m=JSON.parse(fs.readFileSync(path.join(s,'manifest.json')));m.permissions='storage';fs.writeFileSync(path.join(s,'manifest.json'),JSON.stringify(m));assert.throws(()=>c.stage(s),/清单/);m.permissions=[];fs.writeFileSync(path.join(s,'manifest.json'),JSON.stringify(m));const big=path.join(s,'big');fs.writeFileSync(big,'');fs.truncateSync(big,100*1024*1024+1);assert.throws(()=>c.stage(s),/100MB/);fs.unlinkSync(big);if(process.platform==='win32'){const target=path.join(root,'junction-target');fs.mkdirSync(target);fs.symlinkSync(target,path.join(s,'linked'),'junction');}else fs.symlinkSync(path.join(s,'content.js'),path.join(s,'linked'));assert.throws(()=>c.stage(s),/链接/);assert.equal(c.data.items.length,0);}));
test('forgetting one instance preserves all other bindings',()=>fixture((c,s)=>{const row=c.stage(s);c.accept(row);c.setEnabled('A',row.id,true);c.setEnabled('B',row.id,true);c.forget('A');assert.deepEqual(c.enabled('A'),[]);assert.deepEqual(c.enabled('B'),[row.id]);assert.throws(()=>c.setEnabled('B',row.id,'yes'));}));
test('toolbar icon comes only from a small image declared inside the package',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'arena-ext-icon-'));try{const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGUlEQVR4nGPQqDjxnxLMMGrAqAGjBgwXAwAasGcfZXRQWAAAAABJRU5ErkJggg==','base64'),write=m=>fs.writeFileSync(path.join(d,'manifest.json'),JSON.stringify({manifest_version:3,name:'I',version:'1',...m}));
 fs.mkdirSync(path.join(d,'img'));fs.writeFileSync(path.join(d,'img','16.png'),png);fs.writeFileSync(path.join(d,'img','48.png'),png);fs.writeFileSync(path.join(d,'img','big.png'),Buffer.alloc(64*1024+1));fs.writeFileSync(path.join(d,'img','a.txt'),'x');fs.writeFileSync(path.join(path.dirname(d),'outside.png'),png);
 write({icons:{16:'img/16.png',48:'/img/48.png',128:'img/missing.png'}});assert.equal(extensionIcon(d),'data:image/png;base64,'+png.toString('base64'));
 write({action:{default_icon:'./img/16.png'}});assert.match(extensionIcon(d),/^data:image\/png;base64,/);
 write({icons:{48:'img/big.png'}});assert.equal(extensionIcon(d),null,'oversize');
 write({icons:{48:'../outside.png',32:'img/a.txt',64:'C:/x.png'}});assert.equal(extensionIcon(d),null,'outside, wrong type or absolute');
 write({});assert.equal(extensionIcon(d),null,'no icon falls back to a letter in the UI');
 fs.writeFileSync(path.join(d,'manifest.json'),'{bad');assert.equal(extensionIcon(d),null);
}finally{fs.rmSync(d,{recursive:true,force:true});fs.rmSync(path.join(path.dirname(d),'outside.png'),{force:true});}});
