'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const {Store}=require('../src/main/store.cjs'),{Library}=require('../src/main/library.cjs');
const config=JSON.stringify({proxies:[{name:'same-name',type:'http',server:'127.0.0.1',port:9001,password:'private-node-password'}]});
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'arena-library-test-')),store=new Store(dir);return {dir,store,done:()=>fs.rmSync(dir,{recursive:true,force:true})};}
test('migration deduplicates old subscription URLs and never rewrites instance nodes',()=>{const t=setup();try{for(const name of ['A','B']){const i=t.store.create(name);t.store.importNodes(i.id,config);t.store.saveNodes(i.id,t.store.nodes(i.id),{url:'https://example.test/sub?token=secret',updatedAt:new Date().toISOString()});}const before=t.store.list().map(i=>fs.readFileSync(t.store.proxyFile(i.id),'utf8'));const lib=new Library(t.dir,t.store);assert.equal(lib.summaries().length,1);assert(!JSON.stringify(lib.summaries()).includes('secret'));assert(!JSON.stringify(lib.summaries()).includes('private-node-password'));assert.deepEqual(t.store.list().map(i=>fs.readFileSync(t.store.proxyFile(i.id),'utf8')),before);assert.equal(new Library(t.dir,t.store).summaries().length,1);}finally{t.done();}});
test('multiple sources allow duplicate node names, persist rename and delete without instance mutation',async()=>{const t=setup();try{const instance=t.store.create('A');t.store.importNodes(instance.id,config);const lib=new Library(t.dir,t.store);const a=await lib.save({name:'First',text:config}),b=await lib.save({name:'Second',text:config});assert.notEqual(a,b);assert.equal(lib.node(a,'same-name').password,'private-node-password');lib.rename(a,'Renamed');assert.equal(new Library(t.dir,t.store).get(a).name,'Renamed');lib.remove(a);assert.throws(()=>lib.get(a));assert.equal(lib.get(b).nodes.length,1);assert.equal(t.store.nodes(instance.id).length,1);}finally{t.done();}});
test('failed subscription replacement preserves saved URL, nodes and name atomically',async()=>{const t=setup();const server=http.createServer((_req,res)=>res.end('not valid proxies'));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const lib=new Library(t.dir,t.store),id=await lib.save({name:'Original',text:config});const before=fs.readFileSync(lib.file,'utf8');await assert.rejects(lib.save({id,name:'Bad',url:`http://127.0.0.1:${server.address().port}/?token=secret`}));assert.equal(fs.readFileSync(lib.file,'utf8'),before);assert.equal(lib.get(id).name,'Original');await assert.rejects(lib.save({name:'',text:config}));}finally{await new Promise(r=>server.close(r));t.done();}});
test('refresh uses saved URLs independently and does not expose them in summaries',async(context)=>{
// Keep production SSRF checks enabled. Only this test process maps an approved
// fake public hostname to its ephemeral loopback fixture; no Internet request.
const dns=require('node:dns').promises,lookup=dns.lookup,request=http.request;
context.mock.method(dns,'lookup',(host,options)=>host==='subscription.example.test'?Promise.resolve([{address:'93.184.216.34',family:4}]):lookup(host,options));
context.mock.method(http,'request',(url,options,callback)=>{const local=new URL(url);if(local.hostname==='subscription.example.test'){local.hostname='127.0.0.1';return request(local,{...options,lookup:undefined,servername:undefined,family:4},callback);}return request(url,options,callback);});
const t=setup();const hits=[];const server=http.createServer((req,res)=>{hits.push(req.url);res.end(config);});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const lib=new Library(t.dir,t.store),url=`http://subscription.example.test:${server.address().port}/`;const a=await lib.save({name:'A',url:url+'?token=one'}),b=await lib.save({name:'B',url:url+'?token=two'});await lib.save({id:a});assert.deepEqual(hits,['/?token=one','/?token=two','/?token=one']);assert.equal(lib.get(b).url,url+'?token=two');assert(!JSON.stringify(lib.summaries()).includes('token'));}finally{await new Promise(r=>server.close(r));t.done();}});
test('node deletion persists across restart and subscription refresh, with explicit restore',async()=>{const t=setup();try{const lib=new Library(t.dir,t.store);const id=await lib.save({name:'Delete fixture',text:config});lib.removeNodes(id,['same-name']);assert.equal(lib.summaries()[0].nodes.length,0);assert.equal(lib.summaries()[0].excludedCount,1);assert.throws(()=>lib.node(id,'same-name'));assert.equal(new Library(t.dir,t.store).summaries()[0].nodes.length,0);await lib.save({id,text:config});assert.equal(lib.summaries()[0].nodes.length,0);lib.restoreNodes(id);assert.equal(lib.node(id,'same-name').name,'same-name');assert.throws(()=>lib.removeNodes(id,['missing']));}finally{t.done();}});
test('library callers cannot opt out of SSRF protection through input fields',async()=>{
 const t=setup();try{const lib=new Library(t.dir,t.store);await assert.rejects(lib.save({name:'Blocked',url:'http://127.0.0.1:9/sub',allowPrivateHosts:true}),/本机或内网/);assert.equal(lib.summaries().length,0);}finally{t.done();}
});
