'use strict';
// Isolate the UI test and always reclaim its own process tree, including failed assertions.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn,spawnSync}=require('node:child_process');
const {childEnvironment,resolveRuntime}=require('../scripts/electron-runtime.cjs');
const out=fs.mkdtempSync(path.join(os.tmpdir(),'facet-notice-results-')),env={...childEnvironment(),NOTICE_OUTPUT:out},exe=resolveRuntime({executable:require('electron'),version:require('electron/package.json').version,env});
const child=spawn(exe,[path.join(__dirname,'notice-electron.cjs')],{env,cwd:path.resolve(__dirname,'..'),stdio:'inherit',windowsHide:false});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let exited=false;child.once('exit',()=>{exited=true;});child.once('error',e=>{console.error(e.message);exited=true;});
function reclaim(){if(exited)return false;if(process.platform==='win32'){const r=spawnSync('taskkill.exe',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});if(r.status!==0&&!exited)throw Error('Test process cleanup failed');}else child.kill('SIGKILL');return true;}
(async()=>{let report;try{for(let i=0;i<280;i++){const file=path.join(out,'result.json');if(fs.existsSync(file)){report=JSON.parse(fs.readFileSync(file,'utf8'));break;}if(exited)break;await sleep(250);}if(!report)throw Error('UI test did not produce its final result');for(let i=0;i<12&&!exited;i++)await sleep(250);report.testProcessReclaimed=reclaim();for(let i=0;i<20&&!exited;i++)await sleep(100);if(!exited)throw Error('Test process did not exit after cleanup');const destination=path.resolve('release/local-visible-notice/source-output');fs.mkdirSync(destination,{recursive:true});for(const name of fs.readdirSync(out))fs.copyFileSync(path.join(out,name),path.join(destination,name));fs.writeFileSync(path.join(destination,'result.json'),JSON.stringify(report,null,2));if(report.errors.length)throw Error(report.errors.join('\n'));console.log('PASS notice integration: '+report.results.length+' checks; test process exited');}finally{reclaim();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
