'use strict';
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'arena-quick-links-'));app.setPath('userData',root);app.commandLine.appendSwitch('disable-features','CalculateNativeWinOcclusion');app.commandLine.appendSwitch('disable-background-networking');if(process.platform==='linux')app.commandLine.appendSwitch('disable-gpu');
const {Controller}=require('../src/main/controller.cjs'),{installIPC}=require('../src/main/ipc.cjs'),{Workspace}=require('../src/main/workspace.cjs');
let win,c,server,proxy;const results=[],errors=[],hits=[];let proxyHits=0;const pause=()=>new Promise(r=>setTimeout(r,140));const wait=async(fn,label)=>{for(let i=0;i<300;i++){if(await fn())return;await new Promise(r=>setTimeout(r,40));}throw Error('Timeout '+label);};const ok=name=>{results.push(name);console.log('PASS '+name);};setTimeout(()=>app.exit(2),120000).unref();
app.whenReady().then(async()=>{try{
 server=http.createServer((req,res)=>{hits.push(req.url);res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Quick site fixture</title><h1>DIRECT FIXTURE</h1>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 proxy=http.createServer((_req,res)=>{proxyHits++;res.end('<title>Quick proxy fixture</title><h1>PROXY FIXTURE</h1>');});proxy.on('connect',(_req,socket)=>{socket.write('HTTP/1.1 200 Connection established\r\n\r\n');socket.once('data',()=>{proxyHits++;const body='<title>Quick proxy fixture</title><h1>PROXY FIXTURE</h1>';socket.end('HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Length: '+Buffer.byteLength(body)+'\r\nConnection: close\r\n\r\n'+body);});});await new Promise(r=>proxy.listen(0,'127.0.0.1',r));
 win=new BrowserWindow({width:1440,height:960,show:true,webPreferences:{preload:path.join(__dirname,'../src/main/preload.cjs'),sandbox:true,nodeIntegration:false,contextIsolation:true,backgroundThrottling:false}});c=new Controller(win,root,path.join(__dirname,'../resources/mihomo',process.platform==='win32'?'mihomo.exe':'mihomo'));installIPC(win,c);const a=c.store.list()[0],b=c.store.create('Second fixture');c.store.update(a.id,{url:url+'/home'});c.store.update(b.id,{url:url+'/home'});await win.loadFile(path.join(__dirname,'../src/renderer/index.html'));const ui=code=>win.webContents.executeJavaScript(code);await wait(()=>ui('!!current()'),'initialize');
 const click=async selector=>{const point=await ui(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing '+${JSON.stringify(selector)});e.scrollIntoView({block:'center',inline:'nearest'});const r=e.getBoundingClientRect();if(e.disabled||r.width<1||!e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)))throw Error('Not clickable '+${JSON.stringify(selector)});return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()`);win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...point});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...point});await pause();};
 assert.equal(await ui('document.querySelectorAll("[data-quick=open]:disabled").length'),5);assert.equal(c.runtimes.size,0);assert.equal(hits.length,0);const stopped=await ui(`window.arenaCore.request('quick-link-open',{id:${JSON.stringify(a.id)},linkId:'quick-arena'})`);assert.equal(stopped.ok,false);assert.equal(c.runtimes.size,0);ok('Five defaults appear without loading sites; stopped-instance navigation is rejected without startup');
 await c.start(a.id);await c.start(b.id);await ui(`route('browser',${JSON.stringify(a.id)})`);const ra=c.runtimes.get(a.id),rb=c.runtimes.get(b.id);await wait(()=>ra.view.webContents.getTitle()==='Quick site fixture'&&rb.view.webContents.getTitle()==='Quick site fixture','two pages');await ra.view.webContents.executeJavaScript("localStorage.setItem('quick-session','A')");await rb.view.webContents.executeJavaScript("localStorage.setItem('quick-session','B')");await pause();

 const savedEnvironment=JSON.stringify(c.store.get(a.id).environment),savedWC=ra.view.webContents.id;
 assert.equal(await ui('document.documentElement.dataset.theme'),'light');
 const originalWidth=await ui('document.querySelector("#browserHost").getBoundingClientRect().width');
 await click('#sidebarToggle');await pause();assert.equal(await ui('document.documentElement.dataset.sidebar'),'collapsed');assert(await ui('document.querySelector("#browserHost").getBoundingClientRect().width')>originalWidth+100);assert.equal(await ui('document.querySelector("#sidebarToggle").getAttribute("aria-expanded")'),'false');
 assert.equal(ra.view.getVisible(),true);await click('#sidebar [data-view=environment]');assert.equal(await ui('view'),'environment');assert.equal(ra.view.getVisible(),false);await click('#sidebar [data-view=browser]');await wait(()=>ra.view.getVisible(),'collapsed native restore');ok('Collapsed sidebar expands native browser area and retains accessible navigation');
 await click('#themeToggle');assert.equal(await ui('document.documentElement.dataset.theme'),'dark');assert.equal(await ui('getComputedStyle(document.documentElement).colorScheme'),'dark');assert.equal(await ui('document.querySelector("#themeToggle").getAttribute("aria-pressed")'),'true');assert.equal(ra.view.webContents.id,savedWC);assert.equal(JSON.stringify(c.store.get(a.id).environment),savedEnvironment);assert.equal(await ra.view.webContents.executeJavaScript("localStorage.getItem('quick-session')"),'A');ok('Night mode changes control chrome only, preserving native instance and environment');
 await win.reload();await wait(()=>ui('!!current()'),'reload preferences');await pause();assert.equal(await ui('document.documentElement.dataset.theme'),'dark');assert.equal(await ui('document.documentElement.dataset.sidebar'),'collapsed');ok('Night mode and sidebar preference survive control-window reload');
 await click('[data-quick="manage"]');await wait(()=>!ra.view.getVisible(),'dark dialog hides native');assert.equal(await ui('getComputedStyle(document.querySelector("#quickLinksDialog")).backgroundColor'),'rgb(22, 24, 30)');assert(await ui(`(()=>{const e=document.querySelector('#quickLinkURL'),c=getComputedStyle(e,'::placeholder'),bg=getComputedStyle(e).backgroundColor;const lum=s=>s.match(/[\\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);const a=lum(c.color),b=lum(bg);return c.opacity==='1'&&(Math.max(a,b)+.05)/(Math.min(a,b)+.05)>=4.5})()`));ok('Night shortcut placeholder meets 4.5 to 1 contrast in real Windows Chromium');await click('[data-quick="close"]');await wait(()=>ra.view.getVisible(),'dark restore');
 await click('#sidebarToggle');await pause();fs.writeFileSync(path.join(__dirname,`chrome-night-${process.platform}.png`),(await win.webContents.capturePage()).toPNG());
 for(const target of ['overview','environment','proxies','global-logs']){await ui(`route('${target}')`);await pause();assert.equal(await ui('document.documentElement.dataset.theme'),'dark');assert.equal(ra.view.getVisible(),false);assert(await ui('document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth+2'));if(target==='overview')fs.writeFileSync(path.join(__dirname,`chrome-night-overview-${process.platform}.png`),(await win.webContents.capturePage()).toPNG());}
 ok('Night management pages and dialogs retain theme, fit width and hide native content');
 await ui(`route('browser',${JSON.stringify(a.id)})`);await click('#themeToggle');await pause();assert.equal(await ui('document.documentElement.dataset.theme'),'light');assert.equal(JSON.stringify(c.store.get(a.id).environment),savedEnvironment);assert.equal(ra.view.webContents.id,savedWC);
 fs.writeFileSync(path.join(__dirname,`chrome-day-${process.platform}.png`),(await win.webContents.capturePage()).toPNG());ok('Returning to day mode preserves instance configuration and browser identity');
 fs.writeFileSync(path.join(__dirname,`quick-links-bar-${process.platform}.png`),(await win.webContents.capturePage({x:240,y:96,width:win.getContentSize()[0]-240,height:110})).toPNG());
 await click('[data-quick="manage"]');await wait(()=>!ra.view.getVisible(),'native view hidden');win.setSize(1280,800);await pause();c.emit();await pause();assert.equal(ra.view.getVisible(),false);assert.equal(await ui('document.querySelector("#quickLinksDialog").open'),true);ok('Management hides the native page even across resize and state refresh');
 await ui(`document.querySelector('#quickLinkName').value='本地工作页';document.querySelector('#quickLinkURL').value=${JSON.stringify(url+'/destination')}`);await click('#quickLinkSave');await wait(()=>c.workspace.data.quickLinks.length===6,'saved link');const link=c.workspace.data.quickLinks.at(-1),selector='[data-quick="open"][data-quick-id="'+link.id+'"]';assert.equal(new Workspace(root).quickLink(link.id).url,url+'/destination');
 await click('[data-quick="edit"][data-quick-id="'+link.id+'"]');await ui(`document.querySelector('#quickLinkName').value='测试工作页';document.querySelector('#quickLinkURL').value='javascript:alert(1)'`);await click('#quickLinkSave');await wait(()=>ui('document.querySelector("#quickLinkMessage").textContent.includes("HTTP")'),'invalid protocol error');assert.equal(c.workspace.quickLink(link.id).name,'本地工作页');assert.equal(await ui('document.querySelector("#quickLinkURL").value'),'javascript:alert(1)');await ui(`document.querySelector('#quickLinkURL').value=${JSON.stringify(url+'/destination')}`);await click('#quickLinkSave');await wait(()=>c.workspace.quickLink(link.id).name==='测试工作页','edit saved');await click('[data-quick="up"][data-quick-id="'+link.id+'"]');assert.equal(new Workspace(root).data.quickLinks.at(-2).id,link.id);ok('Add, edit, URL rejection with draft preservation, and ordering persist through production IPC');
 fs.writeFileSync(path.join(__dirname,`quick-links-manager-${process.platform}.png`),(await win.webContents.capturePage()).toPNG());await click('[data-quick="close"]');await wait(()=>ra.view.getVisible(),'native restored');const wcId=ra.view.webContents.id,environment=c.store.get(a.id).environment,bURL=rb.view.webContents.getURL();await click(selector);await wait(()=>ra.view.webContents.getURL()===url+'/destination','direct quick navigation');assert.equal(await ra.view.webContents.executeJavaScript("localStorage.getItem('quick-session')"),'A');assert.equal(ra.view.webContents.id,wcId);assert.equal(rb.view.webContents.getURL(),bURL);assert.equal(await rb.view.webContents.executeJavaScript("localStorage.getItem('quick-session')"),'B');assert.equal(await ui('activeId'),a.id);assert.equal(await ui('view'),'browser');assert.deepEqual(c.store.get(a.id).environment,environment);ok('Shortcut navigates only the selected instance and retains its actual webContents and session');
 await ui(`route('browser',${JSON.stringify(b.id)})`);await pause();await click(selector);await wait(()=>rb.view.webContents.getURL()===url+'/destination','second quick navigation');assert.equal(await rb.view.webContents.executeJavaScript("localStorage.getItem('quick-session')"),'B');assert.equal(c.store.list().length,2);ok('Switching instances uses the new target without opening new tabs or sharing login storage');
 const p=c.store.create('Proxy fixture',{mode:'mihomo',nodeName:'fixture'});c.store.saveNodes(p.id,[{name:'fixture',type:'http',server:'127.0.0.1',port:proxy.address().port}]);c.store.update(p.id,{url:url+'/home'});await c.start(p.id);const rp=c.runtimes.get(p.id);await wait(()=>rp.view.webContents.getTitle()==='Quick proxy fixture','proxy page');await ui(`route('browser',${JSON.stringify(p.id)})`);await pause();const directHits=hits.filter(x=>x==='/destination').length,priorProxy=proxyHits;await click(selector);await wait(()=>rp.view.webContents.getURL()===url+'/destination','proxy quick destination');assert(proxyHits>priorProxy);assert.equal(hits.filter(x=>x==='/destination').length,directHits);assert((await rp.session.resolveProxy(url)).includes('PROXY'));ok('Shortcut traffic uses the selected instance bundled Mihomo route instead of direct networking');
 rp.core.child.kill();await wait(()=>rp.status==='error','core exit');const unavailable=await ui(`window.arenaCore.request('quick-link-open',{id:${JSON.stringify(p.id)},linkId:${JSON.stringify(link.id)}})`);assert.equal(unavailable.ok,false);assert.equal(hits.filter(x=>x==='/destination').length,directHits);assert.equal(c.store.get(p.id).network.mode,'mihomo');ok('Proxy failure does not permit quick links to fall back to direct mode');
 await ui(`route('browser',${JSON.stringify(a.id)})`);await click('[data-quick="manage"]');await click('[data-quick="remove"][data-quick-id="'+link.id+'"]');await click('[data-quick="cancel-remove"]');assert(c.workspace.quickLink(link.id));await click('[data-quick="remove"][data-quick-id="'+link.id+'"]');await click('[data-quick="confirm-remove"]');await wait(()=>c.workspace.data.quickLinks.length===5,'delete confirmed');assert.equal(new Workspace(root).data.quickLinks.length,5);assert.equal(ra.view.webContents.getURL(),url+'/destination');await click('[data-quick="close"]');ok('Deletion requires confirmation and removes only the saved shortcut, not the open page');
 while(c.workspace.data.quickLinks.length<20)c.workspace.saveQuickLink({name:'这是较长的快捷网站名称 '+c.workspace.data.quickLinks.length,url:url+'/destination?last'});c.emit();await pause();for(const [w,h]of [[960,700],[1280,800],[1440,960]]){win.setSize(w,h);await pause();assert(await ui(`(()=>{const shell=document.querySelector('.browser-shell').getBoundingClientRect(),addr=document.querySelector('#addressForm').getBoundingClientRect(),nav=document.querySelector('.browser-shell .quick-sites').getBoundingClientRect(),manage=document.querySelector('[data-quick="manage"]').getBoundingClientRect();return nav.height<=40&&nav.top>=addr.bottom-1&&nav.right<=shell.right+1&&manage.left>=nav.left&&manage.right<=nav.right+1&&manage.width>20})()`),'bookmarks bar bounds at '+w);}
 await click('[data-quick="open"]:last-child');await wait(()=>ra.view.webContents.getURL()===url+'/destination?last','overflow last link');ok('Twenty long labels stay in one title row at three sizes; horizontally hidden links remain clickable');
}catch(e){errors.push(e.stack||String(e));console.error(e);}finally{try{await c?.closeAll();}catch(e){errors.push(e.message);}win?.destroy();server?.close();proxy?.close();const report={platform:process.platform,electron:process.versions.electron,passed:results.length,results,errors};fs.writeFileSync(path.join(__dirname,`quick-links-${process.platform}.json`),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));app.exit(errors.length?1:0);}});
