'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),zlib=require('node:zlib'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {downloadSubscription,subscriptionURL}=require('../src/main/subscription.cjs');const {Store,parseNodes}=require('../src/main/store.cjs');
const yaml='proxies:\n  - name: Test\n    type: http\n    server: 127.0.0.1\n    port: 12345\n';
async function fixture(job){const sockets=new Set();const server=http.createServer((req,res)=>{if(req.url.startsWith('/ok')){assert.match(req.headers['user-agent'],/clash.meta/);res.end(yaml);}else if(req.url==='/redirect'){res.writeHead(302,{Location:'/ok'});res.end();}else if(req.url==='/loop'){res.writeHead(302,{Location:'/loop'});res.end();}else if(req.url==='/gzip'){res.setHeader('Content-Encoding','gzip');res.end(zlib.gzipSync(yaml));}else if(req.url==='/bomb'){res.setHeader('Content-Encoding','gzip');res.end(zlib.gzipSync('x'.repeat(2048)));}else if(req.url==='/html'){res.setHeader('Content-Type','text/html');res.end('<html>login</html>');}else if(req.url==='/slow'){}else{res.writeHead(403);res.end('private-token-body');}});server.on('connection',s=>{sockets.add(s);s.on('close',()=>sockets.delete(s));});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{await job(`http://127.0.0.1:${server.address().port}`);}finally{for(const s of sockets)s.destroy();await new Promise(r=>server.close(r));}}
test('subscription URL protocol and credential validation',()=>{assert.equal(subscriptionURL('https://example.test/sub?token=abc#ignored').href,'https://example.test/sub?token=abc');for(const s of ['file:///x','javascript:alert(1)','https://u:p@example.test','not a url'])assert.throws(()=>subscriptionURL(s));});
test('Clash response and redirects download successfully',()=>fixture(async base=>{assert.equal((await downloadSubscription(base+'/ok?token=private')).text,yaml);assert.equal((await downloadSubscription(base+'/redirect')).text,yaml);}));
test('compressed subscription supported and decoded size bounded',()=>fixture(async base=>{assert.equal((await downloadSubscription(base+'/gzip')).text,yaml);await assert.rejects(downloadSubscription(base+'/bomb',{maxBytes:1024}),/2MB/);}));
test('redirect loop, HTML, status and timeout fail without returning response or token',()=>fixture(async base=>{await assert.rejects(downloadSubscription(base+'/loop'),/重定向/);await assert.rejects(downloadSubscription(base+'/html'),/网页/);await assert.rejects(downloadSubscription(base+'/forbidden?token=secret'),e=>e.message.includes('403')&&!e.message.includes('secret')&&!e.message.includes('private-token-body'));await assert.rejects(downloadSubscription(base+'/slow',{timeoutMs:50}),/超时/);}));
test('successful import metadata survives restart; snapshots contain no URL token; network unchanged',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'subscription-store-'));try{const s=new Store(dir),x=s.create('A');s.saveNodes(x.id,parseNodes(yaml),{url:'https://example.test/sub?token=never-expose',updatedAt:'2026-09-26T00:00:00Z'});const reloaded=new Store(dir);assert.equal(reloaded.source(x.id).subscription.url,'https://example.test/sub?token=never-expose');assert(!JSON.stringify(reloaded.subscriptionSummary(x.id)).includes('never-expose'));assert.equal(reloaded.get(x.id).network.mode,'direct');const before=fs.readFileSync(s.proxyFile(x.id),'utf8');assert.throws(()=>s.importNodes(x.id,'<html>bad</html>'));assert.equal(fs.readFileSync(s.proxyFile(x.id),'utf8'),before);s.importNodes(x.id,yaml);assert.equal(s.subscriptionSummary(x.id),null);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('legacy node-array source stays readable',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'subscription-legacy-'));try{const s=new Store(dir),x=s.create('Old');fs.mkdirSync(path.dirname(s.proxyFile(x.id)),{recursive:true});fs.writeFileSync(s.proxyFile(x.id),JSON.stringify(parseNodes(yaml)));assert.equal(s.nodes(x.id).length,1);assert.equal(s.subscriptionSummary(x.id),null);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('subscription cannot disguise DIRECT or a policy group as a proxy',()=>{for(const type of ['direct','select','url-test','reject'])assert.throws(()=>parseNodes(JSON.stringify({proxies:[{name:'unsafe',type,server:'127.0.0.1',port:1234}]})),/DIRECT/);});
