'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {Updates,updateError}=require('../src/main/updates.cjs');
function fixture(options={}){const updater=new EventEmitter();updater.checkForUpdates=async()=>updater.emit('update-available',{version:'0.2.2'});updater.downloadUpdate=async()=>updater.emit('update-downloaded',{version:'0.2.2'});const calls=[];updater.quitAndInstall=(...args)=>calls.push(['install',...args]);const app={isPackaged:true,getVersion:()=> '0.2.1',commandLine:{hasSwitch:()=>false}};const updates=new Updates(app,{updater,prepareInstall:async()=>calls.push(['cleanup']),beginQuit:()=>calls.push(['quit-ready']),cancelQuit:()=>calls.push(['restore']),...options});return {updates,updater,calls,app};}
test('Check and download are manual; exiting cannot silently install or downgrade',async()=>{const {updates,updater,calls}=fixture();assert.equal(updates.snapshot().status,'idle');assert.equal(updater.autoDownload,false);assert.equal(updater.autoInstallOnAppQuit,false);assert.equal(updater.allowDowngrade,false);assert.equal(updater.allowPrerelease,false);await updates.check();assert.equal(updates.snapshot().status,'available');assert.equal(calls.length,0);await updates.download();assert.equal(updates.snapshot().status,'downloaded');assert.equal(calls.length,0);});
test('Installation requires confirmation and successful process cleanup before quitting',async()=>{const {updates,calls}=fixture();await updates.check();await updates.download();await assert.rejects(updates.install(false),/确认/);assert.deepEqual(calls,[]);await updates.install(true);assert.deepEqual(calls,[['cleanup'],['quit-ready'],['install',true,true]]);});
test('Cleanup failure keeps the downloaded update and restores controls without starting installer',async()=>{const {updates,calls}=fixture({prepareInstall:async()=>{throw Error('core still running');}});await updates.check();await updates.download();await assert.rejects(updates.install(true),/core still running/);assert.equal(updates.snapshot().status,'downloaded');assert.deepEqual(calls,[['restore']]);});
test('Download checksum failures remain failures; install is rejected and release URLs are redacted',async()=>{const {updates,updater,calls}=fixture();await updates.check();updater.downloadUpdate=async()=>{throw Object.assign(Error('bad checksum'),{code:'ERR_UPDATER_CHECKSUM_MISMATCH'});};await updates.download();assert.equal(updates.snapshot().status,'error');await assert.rejects(updates.install(true),/下载/);assert.deepEqual(calls,[]);assert.equal(updateError({code:'ERR_UPDATER_CHANNEL_FILE_NOT_FOUND'}),'尚未发布可用的在线更新版本，请稍后再试。');assert(!updateError(Error('request https://example.test/file?token=private-value')).includes('private-value'));});
test('Duplicate checks cannot overlap, and a network error can be retried',async()=>{const {updates,updater}=fixture();let release;updater.checkForUpdates=()=>new Promise(resolve=>release=resolve);const pending=updates.check();await assert.rejects(updates.check(),/正在进行/);updater.emit('error',Error('network unavailable'));release();await pending;assert.equal(updates.snapshot().status,'error');updater.checkForUpdates=async()=>updater.emit('update-not-available',{});await updates.check();assert.equal(updates.snapshot().status,'current');});
test('Custom data directories are not replaced by an automatic default-directory restart',async()=>{const {updater}=fixture();const app={isPackaged:true,getVersion:()=> '0.2.1',commandLine:{hasSwitch:()=>true}};const updates=new Updates(app,{updater});assert.equal(updates.snapshot().restart,false);assert.equal(updater.autoRunAppAfterInstall,false);});
test('Source launches do not expose a working update action',async()=>{const app={isPackaged:false,commandLine:{hasSwitch:()=>false}};const updates=new Updates(app);assert.equal(updates.snapshot().supported,false);await assert.rejects(updates.check(),/源码/);});
