'use strict';
const fs=require('node:fs'),path=require('node:path');
const {app,session,WebContentsView,View}=require('electron');
const {installWebRTCPolicy}=require('./webrtc-policy.cjs');
// 实例网页里的音量脚本启动时异步取当前音量（只返回一个 0–1 的数字）；由控制器自己注册，不依赖界面 IPC 是否安装。
const volumeOwners=new Set();let volumeIPC=false;
function installVolumeIPC(){if(volumeIPC)return;volumeIPC=true;require('electron').ipcMain.handle('facet:volume-get',event=>{for(const owner of volumeOwners){const v=owner.volumeForSession(event.sender.session,true);if(v!=null)return v;}return 1;});}
const {Store,safeURL,parseNodes,networkConfig}=require('./store.cjs');
const {downloadSubscription}=require('./subscription.cjs');
const {Mihomo}=require('./mihomo.cjs');
const {recoverProcessHosts}=require('./process-host.cjs');
const {Workspace,redact}=require('./workspace.cjs');const {applyEnvironment,sanitizeElectronUserAgent}=require('./environment.cjs');
const {Library}=require('./library.cjs');const {Diagnostics}=require('./diagnostics.cjs');
const deletionJournal=require('./deletion-journal.cjs');
const {commitDeletionMetadata}=require('./deletion-commit.cjs');
// 经代理访问时表示「连不上代理/节点」的页面错误码：-130 代理连接失败、-111 隧道失败、-100/-101 连接关闭或重置、
// -118/-7 超时、-324 空响应、-109 地址不可达。只用于提醒，不会切换节点或改为直连。
const PROXY_FAILURES=new Set([-130,-111,-100,-101,-118,-7,-324,-109]);
class Controller {
 constructor(window,dir,binary){installWebRTCPolicy(app);this.window=window;const existing=fs.existsSync(path.join(dir,'instances.json'));this.store=new Store(dir);this.dir=dir;this.binary=binary;this.runtimes=new Map();this.queues=new Map();this.logs=new Map();this.activeId=null;this.bounds=null;this.disposing=false;this.startTail=Promise.resolve();if(!this.store.list().length&&!fs.existsSync(this.store.file))this.store.create('主工作区');this.library=new Library(dir,this.store);this.workspace=new Workspace(dir,{onEvent:require('./runtime-output.cjs').writeRuntimeEvent});this.extensions=new (require('./extensions.cjs').InstanceExtensions)(this,dir);this.nodeNetwork=new (require('./node-network.cjs').NodeNetwork)(dir);this.diagnostics=new Diagnostics(this);this.transfer=new (require('./instance-transfer.cjs').InstanceTransfer)(this);this.workspace.log('application','应用已就绪；随应用启动按各实例设置执行');
  try{const recovered=recoverProcessHosts(path.join(dir,'core-runtime'));if(recovered.terminated||recovered.removed||recovered.skipped)this.workspace.log('application',`已恢复代理进程租约：终止 ${recovered.terminated} 个进程，清理 ${recovered.removed} 个标记`+(recovered.skipped?`，跳过 ${recovered.skipped} 个无效标记`:''),recovered.skipped?'WARN':'INFO');}catch{this.workspace.log('application','代理进程租约恢复失败，将在下次启动重试','WARN');}
  if(this.store.recovered)this.workspace.log('application','实例配置损坏或缺失，已恢复上一代备份；请核对最近变更，未自动启动实例','WARN');
  // 已删除实例的残留分区/内核目录：只在读到已有实例列表时清理，且此时还没有打开任何实例会话。
  if(existing){try{const c=require('./cleanup.cjs').cleanOrphans(dir,this.store.list().map(x=>x.id));if(c.removed||c.failed)this.workspace.log('application',`已清理 ${c.removed} 项已删除实例的残留数据`+(c.failed?`；${c.failed} 项暂未能删除，下次启动再试`:''),c.failed?'WARN':'INFO');}catch{}}
  this.recoverDeletionJournals();
  const currentIds=new Set(this.store.list().map(x=>x.id));
  for(const id of Object.keys(this.extensions.catalog.data.enabled))if(!currentIds.has(id)){
   try{this.extensions.catalog.forget(id);}catch{this.workspace.log('application','已删除实例的扩展绑定清理失败，下次启动重试','WARN');}
  }
 }
 recoverDeletionJournals(){const current=new Set(this.store.list().map(x=>x.id));for(const row of deletionJournal.list(this.dir)){if(current.has(row.instanceId)){deletionJournal.finish(this.dir,row.instanceId);continue;}try{const residual=require('./cleanup.cjs').journalResiduals(this.dir,row.instanceId);if(!residual.length&&!Object.hasOwn(this.extensions.catalog.data.enabled,row.instanceId))deletionJournal.finish(this.dir,row.instanceId);else this.workspace.log('application',`实例 ${row.instanceId} 仍有 ${residual.length} 项删除残留，将在下次启动重试`,'WARN');}catch{this.workspace.log('application','删除操作恢复检查失败，将在下次启动重试','WARN');}}}
 queue(id,job){const prior=this.queues.get(id)||Promise.resolve();const next=prior.catch(()=>{}).then(job);this.queues.set(id,next);next.finally(()=>{if(this.queues.get(id)===next)this.queues.delete(id);}).catch(()=>{});return next;}
 log(id,text,level='INFO'){text=redact(text);this.workspace.log('instance',text,level,id);const lines=this.logs.get(id)||[];lines.unshift({time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),level,text});this.logs.set(id,lines.slice(0,100));this.emit();}
 assignment(id){const data=this.store.source(id),ref=data.assignment;if(!ref)return {status:'本地节点副本 / 未关联来源'};const source=this.library.data.sources.find(s=>s.id===ref.sourceId);if(!source)return {...ref,status:'来源已删除；实例保留副本'};const node=source.nodes.find(n=>n.name===ref.name);const original=data.nodes.find(n=>n.name===ref.name);return {...ref,sourceName:source.name,status:source.excluded?.includes(ref.name)?'来源已本地删除该节点；实例保留副本':!node?'来源已移除此节点':JSON.stringify(node)===JSON.stringify(original)?'配置已同步':'来源配置已变化，重新分配后生效'};}
 snapshot(){return {transferProgress:this.transfer.progress||null,transferOutcome:this.transferOutcome||null,...this.workspace.snapshot(this.library),extensions:this.extensions.snapshot(),control:this.controlApi?.uiSnapshot()||{enabled:false,running:false,apiPort:null,cdpPort:null,token:null,restartRequired:false},creationProgress:this.creationProgress||null,batchDeletion:this.batchDeletion?{id:this.batchDeletion.id,running:this.batchDeletion.running,total:this.batchDeletion.total,done:this.batchDeletion.done,removed:this.batchDeletion.removed,failed:this.batchDeletion.failed,cleanupPending:this.batchDeletion.cleanupPending}:null,batchCreation:this.batchCreation?{id:this.batchCreation.id,running:this.batchCreation.running,cancelling:this.batchCreation.cancelling,total:this.batchCreation.total,done:this.batchCreation.done,created:this.batchCreation.created,failed:this.batchCreation.failed}:null,versions:{app:require('./application-version.cjs').applicationVersion(app),electron:process.versions.electron},library:require('./node-evidence.cjs').summaries(this),diagnostics:this.diagnostics.snapshot(),nodeNetwork:this.nodeNetwork.snapshot(),activeId:this.activeId,coreInstalled:fs.existsSync(this.binary),audioMuted:this.store.muted,instances:this.store.list().map(x=>{const r=this.runtimes.get(x.id);return {...x,assignment:this.assignment(x.id),lastError:this.workspace.events.find(e=>e.instanceId===x.id&&['ERROR','WARN'].includes(e.level))?.text||'',lastErrorAt:this.workspace.events.find(e=>e.instanceId===x.id&&['ERROR','WARN'].includes(e.level))?.time||'',lastLoadedAt:r?.lastLoadedAt||'',pageState:r?.pageState||'未启动',coreVersion:r?.coreVersion||'',status:r?.status||'stopped',error:r?.error||'',proxyAlert:r?.status==='running'&&r.proxyAlert?r.proxyAlert.message:'',proxyAlertAt:r?.status==='running'&&r.proxyAlert?r.proxyAlert.at:'',title:r?.title||'',currentURL:r?.url||x.url,canBack:r?.view&&!r.view.webContents.isDestroyed()?r.view.webContents.navigationHistory.canGoBack():false,canForward:r?.view&&!r.view.webContents.isDestroyed()?r.view.webContents.navigationHistory.canGoForward():false,nodeDiagnosticKeys:Object.fromEntries(this.store.nodes(x.id).map(n=>[n.name,require('./instance-node.cjs').nodeDiagnosticKey(x.id,n)])),nodes:this.store.nodes(x.id).map(n=>n.name),subscription:this.store.subscriptionSummary(x.id),pid:r?.core?.child?.pid||null,proxyPort:r?.core?.proxyPort||null,logs:this.logs.get(x.id)||[]};})};}
 // 静音：全部静音 或 实例自己静音 时，该实例的网页、弹窗以及同一会话里的扩展页面都不出声。状态写入 instances.json，重启后保持；不需要重启实例。
 mutedFor(id){return this.store.muted||this.store.list().some(x=>x.id===id&&(x.muted===true||x.volume===0));}
 // 音量：Electron 没有单个网页的音量接口。每个实例会话注册一个隔离环境的脚本（volume-preload.cjs，网页脚本看不到），
 // 按实例音量缩放网页里 <video>/<audio> 的音量；包括子框架（nodeIntegrationInSubFrames 只让脚本进子框架，沙盒下不开放 Node）。
 volumeFor(id){const x=this.store.list().find(x=>x.id===id);const v=Number.isInteger(x?.volume)?x.volume:100;return Math.max(0,Math.min(100,v));}
 volumePreload(s){volumeOwners.add(this);installVolumeIPC();try{if(s.getPreloadScripts?.().some(p=>p.id==='facet-volume'))return;s.registerPreloadScript({id:'facet-volume',type:'frame',filePath:path.join(__dirname,'volume-preload.cjs')});}catch(e){this.workspace?.log?.('application','音量脚本注册失败：'+e.message,'WARN');}}
 volumeForSession(ses,strict){for(const [id,r] of this.runtimes)if(r.session===ses)return this.volumeFor(id)/100;return strict?null:1;}
 sendVolume(id){const r=this.runtimes.get(id);if(!r?.session)return;const f=this.volumeFor(id)/100;for(const wc of require('electron').webContents.getAllWebContents()){try{if(wc.isDestroyed()||wc.session!==r.session)continue;for(const frame of wc.mainFrame.framesInSubtree)try{frame.send('facet:volume',f);}catch{}}catch{}}}
 setVolume(id,volume){const x=this.store.get(id),v=Math.round(Number(volume));const patch={volume:v};if(v>0&&x.muted)patch.muted=false;this.store.update(id,patch);this.applyAudio(id);this.sendVolume(id);this.emitSoon();return {volume:this.volumeFor(id),muted:this.store.get(id).muted===true};}
 applyAudio(id){const r=this.runtimes.get(id);if(!r)return;const muted=this.mutedFor(id),list=new Set();const add=wc=>{if(wc&&!wc.isDestroyed())list.add(wc);};add(r.view?.webContents);for(const w of r.popups||[])if(!w.isDestroyed())add(w.webContents);const ses=r.view?.webContents?.session;if(ses)for(const wc of require('electron').webContents.getAllWebContents())try{if(!wc.isDestroyed()&&wc.session===ses)add(wc);}catch{}for(const wc of list)try{wc.setAudioMuted(muted);}catch{}}
 setMuted(id,muted){if(id==null)this.store.setMuted(muted===true);else{this.store.get(id);this.store.update(id,{muted:muted===true});}for(const key of this.runtimes.keys())this.applyAudio(key);this.emit();return {global:this.store.muted,instance:id==null?undefined:this.mutedFor(id)};}
 emit(){if(this.emitTimer){clearTimeout(this.emitTimer);this.emitTimer=null;}if(!this.window.isDestroyed()&&!this.disposing)this.window.webContents.send('core:state',this.snapshot());}
 // 网页标题/加载状态、检测进度这类高频变化合并为一次推送；其他操作仍立即推送。
 emitSoon(){if(this.emitTimer)return;this.emitTimer=setTimeout(()=>{this.emitTimer=null;this.emit();},60);}
 flushEmit(){if(this.emitTimer)this.emit();}
 choose(id){if(id!==null)this.store.get(id);this.activeId=id;if(this.grid){this.applyGrid();this.emit();return;}for(const [key,r]of this.runtimes)if(r.view){r.view.setVisible(key===id&&r.status==='running'&&!!this.bounds);if(key===id&&this.bounds){r.view.setBounds(this.bounds);this.fitViewport(r,this.bounds);}}this.emit();}
 async capturePageFrame(id){const r=this.runtimes.get(id);if(id!==this.activeId||!this.bounds||r?.status!=='running'||!r.view||r.view.webContents.isDestroyed())return null;const image=await r.view.webContents.capturePage();return image.isEmpty()?null:'data:image/jpeg;base64,'+image.toJPEG(90).toString('base64');}
 layout(id,bounds){if(id!==this.activeId)return;const [width,height]=this.window.getContentSize();if(!bounds){this.bounds=null;if(this.grid)return;for(const r of this.runtimes.values())r.view?.setVisible(false);return;}const b={x:Math.max(0,Math.round(Number(bounds.x))),y:Math.max(0,Math.round(Number(bounds.y))),width:Math.round(Number(bounds.width)),height:Math.round(Number(bounds.height))};if(!Object.values(b).every(Number.isFinite)||b.width<1||b.height<1)return;b.width=Math.min(b.width,width-b.x);b.height=Math.min(b.height,height-b.y);if(b.width<1||b.height<1)return;if(this.grid)this.setGrid(null);this.bounds=b;this.lastPageSize={width:b.width,height:b.height};const r=this.runtimes.get(id);if(r?.view){r.view.setBounds(b);this.fitViewport(r,b);r.view.setVisible(r.status==='running');}}
 fitViewport(r,bounds,tile=false){if(!r.environment||!r.view||r.status!=='running')return;const wc=r.view.webContents,env=r.environment,vp=require('./viewport.cjs');const send=tile||!!(env.width||env.scale||env.fingerprint?.enabled&&env.fingerprint.hardware);
 // 宫格格子用缩放渲染（tileMetrics）；离开宫格后，不需要视口覆盖的实例清除覆盖，恢复正常。
 const metrics=tile?vp.tileMetrics(env,bounds,this.gridBase(),this.screenSize()):vp.deviceMetrics(env,bounds);const key=(tile?'tile:':'')+JSON.stringify(metrics);if(key===r.viewportKey&&!r.viewportPending)return;r.viewportPending={metrics,key,send};if(r.viewportWork)return;r.viewportWork=(async()=>{while(r.viewportPending&&r.view&&!wc.isDestroyed()){const next=r.viewportPending;r.viewportPending=null;if(next.key===r.viewportKey)continue;if(next.send)await wc.debugger.sendCommand('Emulation.setDeviceMetricsOverride',next.metrics);else if(r.viewportTiled)await wc.debugger.sendCommand('Emulation.clearDeviceMetricsOverride');r.viewportTiled=next.send&&next.key.startsWith('tile:');r.viewportKey=next.key;}})().catch(()=>{if(r.view&&!wc.isDestroyed()){r.viewportKey=null;}}).finally(()=>{r.viewportWork=null;});}
 async start(id,{autoStart=false}={}){return this.queue(id,()=>{const next=this.startTail.catch(()=>{}).then(async()=>{if(autoStart&&(this.disposing||!this.store.list().some(x=>x.id===id&&x.autoStart===true)))return false;await this.startInner(id);return autoStart?true:undefined;});this.startTail=next;return next;});}
 startOnLaunch(){return require('./startup-instances.cjs').startOnLaunch(this);}
 async startInner(id){if(this.disposing)throw Error('应用正在退出');const x=this.store.get(id);networkConfig(x.network);let old=this.runtimes.get(id);if(old?.status==='running')return;if(old?.core?.child||old?.view||old?.loadedExtensions?.size)await this.stopInner(id);const r={status:'starting',view:null,core:null,error:'',url:x.url,environment:x.environment};this.runtimes.set(id,r);this.log(id,x.network.mode==='direct'?'正在以本机 IP 直连启动':'正在启动独立代理内核');
 try{const s=session.fromPartition('persist:arena-core-'+id,{cache:true});r.session=s;this.volumePreload(s);// 只读文件权限：拖入或选择的文件，网页经 FileSystemHandle.getFile() 读取（react-dropzone 等上传组件会这样取文件）；写入仍拒绝。
 const readable=(permission,details)=>permission==='fileSystem'&&details?.fileAccessType==='readable';s.setPermissionRequestHandler((_wc,permission,cb,details)=>cb(permission==='geolocation'&&!!x.environment.geoEnabled||readable(permission,details)));s.setPermissionCheckHandler((_wc,permission,_origin,details)=>permission==='geolocation'&&!!x.environment.geoEnabled||readable(permission,details));await s.closeAllConnections();
 if(x.network.mode==='mihomo'){const node=this.store.nodes(id).find(n=>n.name===x.network.nodeName);if(!node)throw Error('尚未选择可用节点；可导入节点或明确切换到本机 IP 直连');r.core=new Mihomo(this.binary,path.join(this.dir,'core-runtime',id),message=>{if(this.runtimes.get(id)!==r)return;r.status='error';r.error=message;this.destroyView(r);this.log(id,message,'ERROR');},this.nodeNetwork);r.core.onIssue=message=>this.noteProxyIssue(id,r,'内核连续报告连接错误：'+message,false);const {port,version}=await r.core.start(node);r.coreVersion=version;this.log(id,'节点连接：'+r.core.networkSummary.dns+'；'+r.core.networkSummary.route);await s.setProxy({mode:'fixed_servers',proxyRules:`http://127.0.0.1:${port}`,proxyBypassRules:'<-loopback>'});}else await s.setProxy({mode:'direct'});
 if(x.network.mode==='mihomo'&&!r.core?.child)throw Error('代理内核已退出');
 await this.transfer.hydrateCookies(id);s.setUserAgent(x.environment.userAgent||sanitizeElectronUserAgent(s.getUserAgent()),x.environment.language);
 const view=new WebContentsView({webPreferences:{session:s,sandbox:true,nodeIntegration:false,nodeIntegrationInSubFrames:true,contextIsolation:true,webSecurity:true,backgroundThrottling:true}});r.view=view;try{view.webContents.setAudioMuted(this.mutedFor(x.id));}catch{}view.setVisible(false);this.window.contentView.addChildView(view);const wc=view.webContents;
 // 弹出窗口（window.open 带尺寸，如第三方登录）用独立小窗口打开，与本实例同一登录、代理和环境；普通「新窗口」链接仍在当前页打开。
 wc.setWindowOpenHandler(({url,disposition})=>{const popup=disposition==='new-window'&&this.popupAllowed(id,r);let checked;try{checked=safeURL(url);}catch{return popup&&url==='about:blank'?this.popupOptions(x):{action:'deny'};}if(popup)return this.popupOptions(x);setImmediate(()=>this.navigate(id,checked).catch(e=>this.log(id,e.message,'WARN')));return {action:'deny'};});
 wc.on('did-create-window',(win,details)=>this.adoptPopup(id,r,x,win,details));
 wc.on('will-navigate',(event,url)=>{try{safeURL(url);}catch{event.preventDefault();}});wc.on('will-redirect',(event,url)=>{try{safeURL(url);}catch{event.preventDefault();}});
 const changed=()=>{if(wc.isDestroyed()||this.runtimes.get(id)!==r)return;r.url=wc.getURL()||x.url;r.title=wc.getTitle();this.emitSoon();};wc.on('did-navigate',(_event,url)=>{changed();try{if(this.store.get(id).url!==url)this.store.update(id,{url});}catch{}});wc.on('did-navigate-in-page',changed);wc.on('page-title-updated',changed);wc.on('did-stop-loading',changed);
 // 失败的导航随后会显示错误页并触发 did-finish-load；只有新的主框架导航才重置失败标记。
 wc.on('did-start-navigation',(_event,_url,isInPlace,isMainFrame)=>{if(isMainFrame&&!isInPlace)r.loadFailed=false;});wc.on('did-start-loading',()=>{r.pageState='加载中';this.emitSoon();});wc.on('did-finish-load',()=>{r.pageState='已完成加载（不代表所有资源可用）';r.lastLoadedAt=new Date().toISOString();r.error='';if(!r.loadFailed&&/^https?:/i.test(wc.getURL()))this.clearProxyAlert(id,r);this.emitSoon();});
 wc.on('did-fail-load',(_event,code,description,_url,isMain)=>{if(isMain&&code!==-3)r.loadFailed=true;if(isMain&&PROXY_FAILURES.has(code))this.noteProxyIssue(id,r,`页面无法经代理连接（${description}）`+(r.core?.recentIssue()?'；内核提示：'+r.core.recentIssue():''),true);});
 wc.on('did-fail-load',(_event,code,description,_url,isMain)=>{if(isMain&&code!==-3){r.pageState='加载失败';r.error=`页面加载失败：${description} (${code})`+(r.core?.recentIssue()?'；内核提示：'+r.core.recentIssue():'');this.log(id,r.error,'WARN');}});
 wc.on('render-process-gone',()=>{if(this.runtimes.get(id)===r){r.status='error';r.error='浏览进程退出，请停止后重启实例';this.log(id,r.error,'ERROR');this.stop(id).catch(()=>{});}});
 await wc.loadFile(path.join(__dirname,'../renderer/seed.html'));
 const native=await wc.executeJavaScript(`(async()=>({platform:navigator.platform,metadata:navigator.userAgentData?await navigator.userAgentData.getHighEntropyValues(['architecture','bitness','model','platformVersion','fullVersionList','wow64']):null}))()`);r.native=native;
 wc.debugger.attach('1.3');await applyEnvironment(wc,x.environment,native,this.bounds||{width:this.window.getContentSize()[0],height:this.window.getContentSize()[1]});
 if(this.extensions.catalog.enabled(id).length)await this.extensions.load(r,id);
 r.status='running';this.transfer.consumeCookies(id);this.choose(this.activeId);this.log(id,x.network.mode==='direct'?'本机 IP 直连 · 已建立独立持久会话':'代理模式 · 连接失败不会回退直连');wc.loadURL(x.url).catch(e=>{if(e.code!=='ERR_ABORTED')this.log(id,'网页未能完成加载，请检查网址或网络','WARN');});
 }catch(e){r.status='error';r.error=e.message;this.destroyView(r);try{await r.core?.stop();}catch(stopError){r.error+='；'+stopError.message;}this.log(id,r.error,'ERROR');throw Error(r.error);}}
 popupAllowed(id,r){return this.runtimes.get(id)===r&&['starting','running'].includes(r.status)&&(r.popups?.size||0)<4;}
 popupOptions(x){return {action:'allow',overrideBrowserWindowOptions:{parent:this.window,minWidth:360,minHeight:320,autoHideMenuBar:true,title:x.name+' · 弹出窗口',backgroundColor:'#ffffff',webPreferences:{sandbox:true,nodeIntegration:false,contextIsolation:true,webSecurity:true}}};}
 adoptPopup(id,r,x,win,details){if(this.runtimes.get(id)!==r||!['starting','running'].includes(r.status)||(r.popups?.size||0)>=4){if(!win.isDestroyed())win.destroy();return;}
  r.popups??=new Set();r.popups.add(win);try{win.webContents.setAudioMuted(this.mutedFor(id));}catch{}win.on('closed',()=>r.popups?.delete(win));try{win.setMenuBarVisibility(false);}catch{}
  const pwc=win.webContents,target=details?.url||'';try{pwc.stop();}catch{}
  pwc.setWindowOpenHandler(({url})=>{try{const next=safeURL(url);setImmediate(()=>{if(!pwc.isDestroyed())pwc.loadURL(next).catch(()=>{});});}catch{}return {action:'deny'};});
  const guard=(event,url)=>{if(url==='about:blank')return;try{safeURL(url);}catch{event.preventDefault();}};pwc.on('will-navigate',guard);pwc.on('will-redirect',guard);
  pwc.on('render-process-gone',()=>{if(!win.isDestroyed())win.destroy();});
  (async()=>{try{pwc.debugger.attach('1.3');const b=win.getContentBounds();await applyEnvironment(pwc,{...x.environment,width:0,height:0},r.native||{platform:'',metadata:null},{width:b.width,height:b.height});if(/^https?:/i.test(target)&&!pwc.isDestroyed())await pwc.loadURL(target).catch(()=>{});this.log(id,'网页打开了弹出窗口：与本实例同一登录、代理和环境');}catch(e){this.log(id,'弹出窗口未能套用实例环境，已关闭：'+e.message,'WARN');if(!win.isDestroyed())win.destroy();}})();}
 // 代理断开提醒（被动）：页面因代理连不上而加载失败立即提醒；内核 30 秒内连续 3 次报告连接错误也提醒。
 // 只提示，不自动切换节点、不改为直连；页面经代理成功加载后自动清除。
 noteProxyIssue(id,r,message,strong){if(this.runtimes.get(id)!==r||!r.core||!['running','starting'].includes(r.status))return;const now=Date.now();r.issueTimes=(r.issueTimes||[]).filter(t=>now-t<30000);r.issueTimes.push(now);if(!strong&&r.issueTimes.length<3)return;const first=!r.proxyAlert;r.proxyAlert={message:String(message).slice(0,300),at:new Date().toISOString()};if(first)this.log(id,'代理可能已断开：'+r.proxyAlert.message+'。未自动切换节点，也不会改为直连；可在代理管理检测或更换节点','WARN');this.emitSoon();}
 clearProxyAlert(id,r){r.issueTimes=[];if(!r.proxyAlert||this.runtimes.get(id)!==r)return;r.proxyAlert=null;this.log(id,'代理连接已恢复：页面经代理加载成功');this.emitSoon();}
 // 宫格总览：控制界面报告每个格子的位置；实时模式保持真实网页层，省资源模式才隐藏未选中的格子并使用缩略图。
 setGrid(grid){if(!grid){if(!this.grid)return;this.grid=null;for(const [id,r]of this.runtimes){this.releaseCapture(r);r.gridThumbAt=0;r.gridApplied=null;r.gridBounds=null;if(!r.view)continue;r.view.setVisible(false);r.view.webContents.setBackgroundThrottling(!r.extensionWindows?.size);if(r.extensionPanelThrottle!==undefined)r.extensionPanelThrottle=true;if(r.gridParent){r.gridParent.removeChildView(r.view);this.window.contentView.addChildView(r.view);r.gridParent=null;}if(r.status==='running')this.fitViewport(r,id===this.activeId&&this.bounds?this.bounds:this.lastPageSize||{});}if(this.gridClip){this.window.contentView.removeChildView(this.gridClip);this.gridClip=null;this.gridCanvas=null;this.gridClipBounds=null;this.gridCanvasBounds=null;}return;}
   const input=Array.isArray(grid.tiles)?grid.tiles:[];if(input.length>this.store.list().length)throw Error('宫格布局数量超过实际实例数');
   const tiles=new Map();for(const t of input){if(typeof t?.id!=='string'||!this.runtimes.has(t.id))continue;const b={x:Math.round(Number(t.x)),y:Math.round(Number(t.y)),width:Math.round(Number(t.width)),height:Math.round(Number(t.height))};if(!Object.values(b).every(Number.isFinite)||Math.abs(b.x)>100000||Math.abs(b.y)>100000||b.width<40||b.height<30||b.width>10000||b.height>10000)continue;tiles.set(t.id,{...b,live:t.live===true});}
  const bw=Math.round(Number(grid.base?.width)),bh=Math.round(Number(grid.base?.height));
  const viewport=grid.viewport,b=viewport&&{x:Math.round(Number(viewport.x)),y:Math.round(Number(viewport.y)),width:Math.round(Number(viewport.width)),height:Math.round(Number(viewport.height))};
  const valid=b&&Object.values(b).every(Number.isFinite)&&b.x>=0&&b.y>=0&&b.width>0&&b.height>0&&b.width<=10000&&b.height<=10000;
  const scroll=Math.round(Number(grid.scrollTop)),height=Math.round(Number(grid.scrollHeight));
  this.grid={tiles,revision:Number.isSafeInteger(grid.revision)?grid.revision:null,coordinates:grid.coordinates==='content'?'content':'window',mode:grid.mode==='live'?'live':'saver',base:bw>=320&&bh>=240&&bw<=10000&&bh<=10000?{width:bw,height:bh}:null,viewport:valid?b:null,scrollTop:Number.isFinite(scroll)?Math.max(0,Math.min(100000,scroll)):0,scrollHeight:Number.isFinite(height)?Math.max(1,Math.min(100000,height)):1};this.applyGrid();}
 // 高频滚动不解析列表、不遍历实例，只更新一个原生画布。过期布局的位置消息拒绝并要求重新同步。
 scrollGrid(message){if(!message||!this.grid||!this.grid.viewport||this.grid.mode!=='live'||this.grid.coordinates!=='content'||!this.gridCanvas||!Number.isSafeInteger(message.revision)||message.revision!==this.grid.revision)return false;
  const top=Number(message.scrollTop);if(!Number.isFinite(top)||top<0||top>100000)return false;
  this.grid.scrollTop=Math.min(Math.round(top),Math.max(0,this.grid.scrollHeight-this.grid.viewport.height));this.syncGridCanvas();return true;}
 gridBase(){return this.grid?.base||this.lastPageSize||{width:1280,height:800};}
 screenSize(){try{const {screen}=require('electron');return screen.getDisplayMatching(this.window.getBounds()).size;}catch{return {};}}
 syncGridCanvas(){const {viewport,scrollTop,scrollHeight}=this.grid;
  if(viewport){if(!this.gridClip){this.gridClip=new View();this.gridClip.setBorderRadius(0);this.gridCanvas=new View();this.gridClip.addChildView(this.gridCanvas);this.window.contentView.addChildView(this.gridClip);}
   const canvas={x:0,y:-scrollTop,width:viewport.width,height:Math.max(viewport.height,scrollHeight)};
   if(JSON.stringify(viewport)!==JSON.stringify(this.gridClipBounds)){this.gridClip.setBounds(viewport);this.gridClipBounds=viewport;}
   if(JSON.stringify(canvas)!==JSON.stringify(this.gridCanvasBounds)){this.gridCanvas.setBounds(canvas);this.gridCanvasBounds=canvas;}}}
 applyGrid(){if(!this.grid)return;this.syncGridCanvas();const {viewport,scrollTop}=this.grid;
  for(const [id,r]of this.runtimes){if(!r.view)continue;const t=this.grid.tiles.get(id);if(!t||r.status!=='running'){if(r.gridApplied?.visible)r.view.setVisible(false);r.gridApplied=null;this.releaseCapture(r);continue;}
  const parent=viewport?this.gridCanvas:this.window.contentView;const parentChanged=r.gridParent!==parent;
  if(parentChanged){(r.gridParent||this.window.contentView).removeChildView(r.view);parent.addChildView(r.view);r.gridParent=parent;}
  const throttle=this.grid.mode!=='live'&&!r.extensionWindows?.size;if(r.view.webContents.getBackgroundThrottling()!==throttle)r.view.webContents.setBackgroundThrottling(throttle);
  const live=t.live,b={x:t.x,y:t.y,width:t.width,height:t.height},local=this.grid.coordinates==='content'?b:viewport?{...b,x:t.x-viewport.x,y:t.y-viewport.y+scrollTop}:b;
  const prev=r.gridApplied,last=r.gridBounds,sizeChanged=!last||last.width!==b.width||last.height!==b.height,positionChanged=!last||last.x!==local.x||last.y!==local.y,visibilityChanged=!prev||prev.visible!==live;
  // 滚动只移动整个画布；网页的尺寸和相对位置保持稳定，裁剪交给原生父容器。
  if(parentChanged||(live?(positionChanged||sizeChanged):sizeChanged)){r.view.setBounds(local);r.gridBounds=local;}if(sizeChanged)this.fitViewport(r,b,true);
  if(live){this.releaseCapture(r);if(visibilityChanged)r.view.setVisible(true);}else{this.holdCapture(r);if(visibilityChanged)r.view.setVisible(false);}r.gridApplied={...b,visible:live};}}
 // 隐藏的格子仍可截图（capturePage 的 stayHidden 不会让页面变成“可见”）；这里只标记哪些格子需要缩略图。
 holdCapture(r){r.gridCapture=true;}
 releaseCapture(r){r.gridCapture=false;}
 // 缩略图：从未显示过的隐藏视图，绘制画布还是旧尺寸；缩小渲染的网页只画在左上角（格子大小 × DPR），截图后按这个大小裁掉空白再缩放。
 // 仅省资源模式轮询；隐藏的格子每次截图，选中的实时格每 10 秒保留一张备用。
 async gridThumbs(){if(!this.grid)return {};let sf=1;try{sf=require('electron').screen.getDisplayMatching(this.window.getBounds()).scaleFactor||1;}catch{}const out={},now=Date.now(),vp=require('./viewport.cjs'),screen=this.screenSize(),base=this.gridBase();await Promise.all([...this.grid.tiles].map(async([id,t])=>{const r=this.runtimes.get(id);if(r?.status!=='running'||!r.view||r.view.webContents.isDestroyed())return;if(!r.gridCapture&&r.gridThumbAt&&now-r.gridThumbAt<10000)return;try{let image=await r.view.webContents.capturePage(undefined,{stayHidden:true});if(image.isEmpty())return;const {width:W,height:H}=image.getSize(),m=vp.tileMetrics(r.environment,t,base,screen),dpr=r.environment.scale||sf,cw=Math.max(1,Math.min(W,Math.round(m.width*m.scale*dpr))),ch=Math.max(1,Math.min(H,Math.round(m.height*m.scale*dpr)));if(cw<W-1||ch<H-1)image=image.crop({x:0,y:0,width:cw,height:ch});const w=Math.min(image.getSize().width,Math.round(t.width*Math.min(2,sf)));out[id]='data:image/jpeg;base64,'+image.resize({width:w,quality:'good'}).toJPEG(72).toString('base64');r.gridThumbAt=now;}catch{}}));return out;}
 destroyView(r){this.releaseCapture(r);this.extensions.unload(r);for(const w of r.popups||[])if(!w.isDestroyed())w.destroy();r.popups?.clear();if(!r.view)return;const view=r.view,wc=view.webContents;r.view=null;r.closingView=wc;try{(r.gridParent||this.window.contentView).removeChildView(view);}catch{}r.gridParent=null;r.gridBounds=null;if(wc&&!wc.isDestroyed()){wc.stop();wc.close({waitForBeforeUnload:false});}}
 async stop(id){return this.queue(id,()=>this.stopInner(id));}
 async stopInner(id){const r=this.runtimes.get(id);if(!r)return;this.destroyView(r);try{await r.core?.stop();if(r.loadedExtensions?.size)throw Error('扩展尚未卸载，请重试停止；实例配置未修改');const wc=r.closingView;if(wc&&!wc.isDestroyed())await new Promise((resolve,reject)=>{const done=()=>{clearTimeout(timer);resolve();};const timer=setTimeout(()=>{wc.removeListener('destroyed',done);reject(Error('浏览视图尚未关闭，请重试停止；数据未删除'));},5000);wc.once('destroyed',done);});r.closingView=null;r.status='stopped';r.error='';this.log(id,'实例已停止，登录存储与配置保留');}catch(e){r.status='error';r.error=e.message;this.emit();throw e;}}
 async navigate(id,url){const value=safeURL(url),r=this.runtimes.get(id);if(!r?.view||r.status!=='running')throw Error('请先启动实例');await r.view.webContents.loadURL(value);this.store.update(id,{url:value});this.emit();}
 async action(id,kind){const r=this.runtimes.get(id);if(!r?.view||r.status!=='running')throw Error('实例未运行');const wc=r.view.webContents;if(kind==='back'&&wc.navigationHistory.canGoBack())wc.navigationHistory.goBack();else if(kind==='forward'&&wc.navigationHistory.canGoForward())wc.navigationHistory.goForward();else if(kind==='reload')wc.reload();}
 async settings(id,patch){return this.queue(id,async()=>{const {next,changed}=require('./operations.cjs').prepareSettings(this.store,id,patch);if(!changed)return {changed:false};await this.stopInner(id);this.store.update(id,next);this.log(id,'环境配置已保存；重新启动后生效');return {changed:true};});}
 async remove(id){return this.queue(id,()=>this.removeInner(id));}
 async removeInner(id){
  await this.stopInner(id);
  const s=session.fromPartition('persist:arena-core-'+id),proxyFile=this.store.proxyFile(id),cleanupErrors=[];
  cleanupErrors.push(...commitDeletionMetadata(this.store,deletionJournal,this.dir,id));
  try{await s.closeAllConnections();await s.clearStorageData();await s.clearCache();deletionJournal.update(this.dir,id,{steps:{browserStorage:'done'}});}catch(e){cleanupErrors.push('浏览数据清理失败：'+e.message);}
  try{if(!require('./cleanup.cjs').cleanNodeSource(this.dir,id))throw Error('节点源或备份仍被占用');deletionJournal.update(this.dir,id,{steps:{nodeSource:'done'}});}catch(e){cleanupErrors.push('节点源清理失败：'+e.message);}
  try{fs.rmSync(this.transfer.cookieFile(id),{force:true});this.extensions.catalog.forget(id);deletionJournal.update(this.dir,id,{steps:{extensionBinding:'done'}});}catch(e){cleanupErrors.push('扩展绑定或导入 Cookie 任务清理失败：'+e.message);}
  try{if(this.dir&&!require('./cleanup.cjs').cleanInstance(this.dir,id))cleanupErrors.push('运行目录清理未完成');else deletionJournal.update(this.dir,id,{steps:{runtimeDirectory:'done'}});}catch(e){cleanupErrors.push('运行目录清理失败：'+e.message);}
  this.runtimes.delete(id);this.logs.delete(id);if(this.activeId===id)this.choose(null);
  if(!cleanupErrors.length){try{if(!require('./cleanup.cjs').journalResiduals(this.dir,id).length&&!deletionJournal.finish(this.dir,id))cleanupErrors.push('删除记录尚未清理');}catch{cleanupErrors.push('删除残留检查未完成');}}
  if(cleanupErrors.length)this.workspace.log('application','实例配置已删除，部分残留数据将在下次启动时重试：'+cleanupErrors.join('；'),'WARN',id);
  this.emit();
  if(cleanupErrors.length)throw Error('实例配置已删除，但部分数据尚未清理；请重启应用重试并查看系统日志');
 }
 async importSubscription(id,url,refresh=false){return this.queue(id,async()=>{this.store.get(id);if(this.disposing)throw Error('应用正在退出');const target=refresh?this.store.source(id).subscription?.url:url;if(!target)throw Error('此实例尚未保存订阅链接');const downloaded=await downloadSubscription(target);const nodes=parseNodes(downloaded.text);if(this.disposing)throw Error('应用正在退出，未更改订阅');await this.stopInner(id);this.store.saveNodes(id,nodes,{url:downloaded.url,updatedAt:new Date().toISOString()});this.log(id,`订阅${refresh?'更新':'导入'}成功：${nodes.length} 个节点；网络模式保持不变，请选择节点后保存并启动`);return {count:nodes.length};});}
 async closeAll(){await this.transfer.exportTask?.catch(()=>{});this.workspace.log('application','正在退出，回收实例与检测内核');this.disposing=true;await this.queues.get('instance-create')?.catch(()=>{});this.transfer.dispose();await this.queues.get('instance-delete')?.catch(()=>{});await this.queues.get('global-library')?.catch(()=>{});await this.queues.get('node-network')?.catch(()=>{});await this.queues.get('extensions')?.catch(()=>{});await this.diagnostics.close();const ids=this.store.list().map(x=>x.id);const outcomes=await Promise.allSettled(ids.map(id=>this.stop(id)));const failures=outcomes.filter(x=>x.status==='rejected');try{this.workspace.flush?.();this.diagnostics.history?.flush();}catch{}if(failures.length){this.disposing=false;throw Error('存在尚未停止的代理进程，请重试退出');}}
}
module.exports={Controller};
