'use strict';
const fs=require('node:fs'),path=require('node:path');
const {session,WebContentsView}=require('electron');
const {Store,safeURL,parseNodes}=require('./store.cjs');
const {downloadSubscription}=require('./subscription.cjs');
const {Mihomo}=require('./mihomo.cjs');
const {Workspace,redact}=require('./workspace.cjs');const {applyEnvironment}=require('./environment.cjs');
const {Library}=require('./library.cjs');const {Diagnostics}=require('./diagnostics.cjs');
class Controller {
 constructor(window,dir,binary){this.window=window;this.store=new Store(dir);this.dir=dir;this.binary=binary;this.runtimes=new Map();this.queues=new Map();this.logs=new Map();this.activeId=null;this.bounds=null;this.disposing=false;this.startTail=Promise.resolve();if(!this.store.list().length)this.store.create('主工作区');this.library=new Library(dir,this.store);this.workspace=new Workspace(dir);this.extensions=new (require('./extensions.cjs').InstanceExtensions)(this,dir);this.diagnostics=new Diagnostics(this);this.workspace.log('application','应用已就绪；未自动启动实例');}
 queue(id,job){const prior=this.queues.get(id)||Promise.resolve();const next=prior.catch(()=>{}).then(job);this.queues.set(id,next);next.finally(()=>{if(this.queues.get(id)===next)this.queues.delete(id);}).catch(()=>{});return next;}
 log(id,text,level='INFO'){text=redact(text);this.workspace.log('instance',text,level,id);const lines=this.logs.get(id)||[];lines.unshift({time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),level,text});this.logs.set(id,lines.slice(0,100));this.emit();}
 assignment(id){const data=this.store.source(id),ref=data.assignment;if(!ref)return {status:'本地节点副本 / 未关联来源'};const source=this.library.data.sources.find(s=>s.id===ref.sourceId);if(!source)return {...ref,status:'来源已删除；实例保留副本'};const node=source.nodes.find(n=>n.name===ref.name);const original=data.nodes.find(n=>n.name===ref.name);return {...ref,sourceName:source.name,status:source.excluded?.includes(ref.name)?'来源已本地删除该节点；实例保留副本':!node?'来源已移除此节点':JSON.stringify(node)===JSON.stringify(original)?'配置已同步':'来源配置已变化，重新分配后生效'};}
 snapshot(){return {...this.workspace.snapshot(this.library),extensions:this.extensions.snapshot(),creationProgress:this.creationProgress||null,versions:{app:'0.2.0',electron:process.versions.electron},library:this.library.summaries(),diagnostics:this.diagnostics.snapshot(),activeId:this.activeId,coreInstalled:fs.existsSync(this.binary),instances:this.store.list().map(x=>{const r=this.runtimes.get(x.id);return {...x,assignment:this.assignment(x.id),lastError:this.workspace.events.find(e=>e.instanceId===x.id&&['ERROR','WARN'].includes(e.level))?.text||'',lastErrorAt:this.workspace.events.find(e=>e.instanceId===x.id&&['ERROR','WARN'].includes(e.level))?.time||'',lastLoadedAt:r?.lastLoadedAt||'',pageState:r?.pageState||'未启动',coreVersion:r?.coreVersion||'',status:r?.status||'stopped',error:r?.error||'',title:r?.title||'',currentURL:r?.url||x.url,canBack:r?.view&&!r.view.webContents.isDestroyed()?r.view.webContents.navigationHistory.canGoBack():false,canForward:r?.view&&!r.view.webContents.isDestroyed()?r.view.webContents.navigationHistory.canGoForward():false,nodes:this.store.nodes(x.id).map(n=>n.name),subscription:this.store.subscriptionSummary(x.id),pid:r?.core?.child?.pid||null,proxyPort:r?.core?.proxyPort||null,logs:this.logs.get(x.id)||[]};})};}
 emit(){if(!this.window.isDestroyed()&&!this.disposing)this.window.webContents.send('core:state',this.snapshot());}
 choose(id){if(id!==null)this.store.get(id);this.activeId=id;for(const [key,r]of this.runtimes)if(r.view){r.view.setVisible(key===id&&r.status==='running'&&!!this.bounds);if(key===id&&this.bounds){r.view.setBounds(this.bounds);this.fitViewport(r,this.bounds);}}this.emit();}
 async capturePageFrame(id){const r=this.runtimes.get(id);if(id!==this.activeId||!this.bounds||r?.status!=='running'||!r.view||r.view.webContents.isDestroyed())return null;const image=await r.view.webContents.capturePage();return image.isEmpty()?null:'data:image/jpeg;base64,'+image.toJPEG(90).toString('base64');}
 layout(id,bounds){if(id!==this.activeId)return;const [width,height]=this.window.getContentSize();if(!bounds){this.bounds=null;for(const r of this.runtimes.values())r.view?.setVisible(false);return;}const b={x:Math.max(0,Math.round(Number(bounds.x))),y:Math.max(0,Math.round(Number(bounds.y))),width:Math.round(Number(bounds.width)),height:Math.round(Number(bounds.height))};if(!Object.values(b).every(Number.isFinite)||b.width<1||b.height<1)return;b.width=Math.min(b.width,width-b.x);b.height=Math.min(b.height,height-b.y);if(b.width<1||b.height<1)return;this.bounds=b;const r=this.runtimes.get(id);if(r?.view){r.view.setBounds(b);this.fitViewport(r,b);r.view.setVisible(r.status==='running');}}
 fitViewport(r,bounds){if(!r.environment||!r.view||r.status!=='running')return;const wc=r.view.webContents;const metrics=require('./viewport.cjs').deviceMetrics(r.environment,bounds);const key=JSON.stringify(metrics);if(key===r.viewportKey&&!r.viewportPending)return;r.viewportPending={metrics,key};if(r.viewportWork)return;r.viewportWork=(async()=>{while(r.viewportPending&&r.view&&!wc.isDestroyed()){const next=r.viewportPending;r.viewportPending=null;if(next.key===r.viewportKey)continue;if(r.environment.width||r.environment.scale||r.environment.fingerprint?.enabled&&r.environment.fingerprint.hardware)await wc.debugger.sendCommand('Emulation.setDeviceMetricsOverride',next.metrics);r.viewportKey=next.key;}})().catch(()=>{if(r.view&&!wc.isDestroyed()){r.viewportKey=null;}}).finally(()=>{r.viewportWork=null;});}
 async start(id){return this.queue(id,()=>{const next=this.startTail.catch(()=>{}).then(()=>this.startInner(id));this.startTail=next;return next;});}
 async startInner(id){if(this.disposing)throw Error('应用正在退出');const x=this.store.get(id);let old=this.runtimes.get(id);if(old?.status==='running')return;if(old?.core?.child||old?.view||old?.loadedExtensions?.size)await this.stopInner(id);const r={status:'starting',view:null,core:null,error:'',url:x.url,environment:x.environment};this.runtimes.set(id,r);this.log(id,x.network.mode==='direct'?'正在以本机 IP 直连启动':'正在启动独立代理内核');
 try{const s=session.fromPartition('persist:arena-core-'+id,{cache:true});r.session=s;s.setPermissionRequestHandler((_wc,permission,cb)=>cb(permission==='geolocation'&&x.environment.geoEnabled));s.setPermissionCheckHandler((_wc,permission)=>permission==='geolocation'&&x.environment.geoEnabled);await s.closeAllConnections();
 if(x.network.mode==='mihomo'){const node=this.store.nodes(id).find(n=>n.name===x.network.nodeName);if(!node)throw Error('尚未选择可用节点；可导入节点或明确切换到本机 IP 直连');r.core=new Mihomo(this.binary,path.join(this.dir,'core-runtime',id),message=>{if(this.runtimes.get(id)!==r)return;r.status='error';r.error=message;this.destroyView(r);this.log(id,message,'ERROR');});const {port,version}=await r.core.start(node);r.coreVersion=version;await s.setProxy({mode:'fixed_servers',proxyRules:`http://127.0.0.1:${port}`,proxyBypassRules:'<-loopback>'});}else await s.setProxy({mode:'direct'});
 if(x.network.mode==='mihomo'&&!r.core?.child)throw Error('代理内核已退出');
 s.setUserAgent(s.getUserAgent(),x.environment.language);
 const view=new WebContentsView({webPreferences:{session:s,sandbox:true,nodeIntegration:false,contextIsolation:true,webSecurity:true,backgroundThrottling:true}});r.view=view;view.setVisible(false);this.window.contentView.addChildView(view);const wc=view.webContents;
 wc.setWindowOpenHandler(({url})=>{try{const checked=safeURL(url);setImmediate(()=>this.navigate(id,checked).catch(e=>this.log(id,e.message,'WARN')));}catch{}return {action:'deny'};});
 wc.on('will-navigate',(event,url)=>{try{safeURL(url);}catch{event.preventDefault();}});wc.on('will-redirect',(event,url)=>{try{safeURL(url);}catch{event.preventDefault();}});
 const changed=()=>{if(wc.isDestroyed()||this.runtimes.get(id)!==r)return;r.url=wc.getURL()||x.url;r.title=wc.getTitle();this.emit();};wc.on('did-navigate',(_event,url)=>{changed();try{this.store.update(id,{url});}catch{}});wc.on('did-navigate-in-page',changed);wc.on('page-title-updated',changed);wc.on('did-stop-loading',changed);
 wc.on('did-start-loading',()=>{r.pageState='加载中';this.emit();});wc.on('did-finish-load',()=>{r.pageState='已完成加载（不代表所有资源可用）';r.lastLoadedAt=new Date().toISOString();r.error='';this.emit();});
 wc.on('did-fail-load',(_event,code,description,_url,isMain)=>{if(isMain&&code!==-3){r.pageState='加载失败';r.error=`页面加载失败：${description} (${code})`+(r.core?.recentIssue()?'；内核提示：'+r.core.recentIssue():'');this.log(id,r.error,'WARN');}});
 wc.on('render-process-gone',()=>{if(this.runtimes.get(id)===r){r.status='error';r.error='浏览进程退出，请停止后重启实例';this.log(id,r.error,'ERROR');this.stop(id).catch(()=>{});}});
 await wc.loadFile(path.join(__dirname,'../renderer/seed.html'));
 const native=await wc.executeJavaScript(`(async()=>({platform:navigator.platform,metadata:navigator.userAgentData?await navigator.userAgentData.getHighEntropyValues(['architecture','bitness','model','platformVersion','fullVersionList','wow64']):null}))()`);
 wc.debugger.attach('1.3');await applyEnvironment(wc,x.environment,native,this.bounds||{width:this.window.getContentSize()[0],height:this.window.getContentSize()[1]});
 if(this.extensions.catalog.enabled(id).length)await this.extensions.load(r,id);
 r.status='running';this.choose(this.activeId);this.log(id,x.network.mode==='direct'?'本机 IP 直连 · 已建立独立持久会话':'代理模式 · 连接失败不会回退直连');wc.loadURL(x.url).catch(e=>{if(e.code!=='ERR_ABORTED')this.log(id,'网页未能完成加载，请检查网址或网络','WARN');});
 }catch(e){r.status='error';r.error=e.message;this.destroyView(r);try{await r.core?.stop();}catch(stopError){r.error+='；'+stopError.message;}this.log(id,r.error,'ERROR');throw Error(r.error);}}
 destroyView(r){this.extensions.unload(r);if(!r.view)return;const view=r.view,wc=view.webContents;r.view=null;r.closingView=wc;try{this.window.contentView.removeChildView(view);}catch{}if(wc&&!wc.isDestroyed()){wc.stop();wc.close({waitForBeforeUnload:false});}}
 async stop(id){return this.queue(id,()=>this.stopInner(id));}
 async stopInner(id){const r=this.runtimes.get(id);if(!r)return;this.destroyView(r);try{await r.core?.stop();if(r.loadedExtensions?.size)throw Error('扩展尚未卸载，请重试停止；实例配置未修改');const wc=r.closingView;if(wc&&!wc.isDestroyed())await new Promise((resolve,reject)=>{const done=()=>{clearTimeout(timer);resolve();};const timer=setTimeout(()=>{wc.removeListener('destroyed',done);reject(Error('浏览视图尚未关闭，请重试停止；数据未删除'));},5000);wc.once('destroyed',done);});r.closingView=null;r.status='stopped';r.error='';this.log(id,'实例已停止，登录存储与配置保留');}catch(e){r.status='error';r.error=e.message;this.emit();throw e;}}
 async navigate(id,url){const value=safeURL(url),r=this.runtimes.get(id);if(!r?.view||r.status!=='running')throw Error('请先启动实例');await r.view.webContents.loadURL(value);this.store.update(id,{url:value});this.emit();}
 async action(id,kind){const r=this.runtimes.get(id);if(!r?.view||r.status!=='running')throw Error('实例未运行');const wc=r.view.webContents;if(kind==='back'&&wc.navigationHistory.canGoBack())wc.navigationHistory.goBack();else if(kind==='forward'&&wc.navigationHistory.canGoForward())wc.navigationHistory.goForward();else if(kind==='reload')wc.reload();}
 async settings(id,patch){return this.queue(id,async()=>{const {next,changed}=require('./operations.cjs').prepareSettings(this.store,id,patch);if(!changed)return {changed:false};await this.stopInner(id);this.store.update(id,next);this.log(id,'环境配置已保存；重新启动后生效');return {changed:true};});}
 async remove(id){return this.queue(id,async()=>{await this.stopInner(id);const s=session.fromPartition('persist:arena-core-'+id);await s.closeAllConnections();await s.clearStorageData();await s.clearCache();const proxyFile=this.store.proxyFile(id);if(fs.existsSync(proxyFile))fs.unlinkSync(proxyFile);this.extensions.catalog.forget(id);this.store.remove(id);this.runtimes.delete(id);this.logs.delete(id);if(this.activeId===id)this.choose(null);this.emit();});}
 async importSubscription(id,url,refresh=false){return this.queue(id,async()=>{this.store.get(id);if(this.disposing)throw Error('应用正在退出');const target=refresh?this.store.source(id).subscription?.url:url;if(!target)throw Error('此实例尚未保存订阅链接');const downloaded=await downloadSubscription(target);const nodes=parseNodes(downloaded.text);if(this.disposing)throw Error('应用正在退出，未更改订阅');await this.stopInner(id);this.store.saveNodes(id,nodes,{url:downloaded.url,updatedAt:new Date().toISOString()});this.log(id,`订阅${refresh?'更新':'导入'}成功：${nodes.length} 个节点；网络模式保持不变，请选择节点后保存并启动`);return {count:nodes.length};});}
 async closeAll(){this.workspace.log('application','正在退出，回收实例与检测内核');this.disposing=true;await this.queues.get('global-library')?.catch(()=>{});await this.queues.get('extensions')?.catch(()=>{});await this.diagnostics.close();const ids=this.store.list().map(x=>x.id);const outcomes=await Promise.allSettled(ids.map(id=>this.stop(id)));const failures=outcomes.filter(x=>x.status==='rejected');if(failures.length){this.disposing=false;throw Error('存在尚未停止的代理进程，请重试退出');}}
}
module.exports={Controller};
