'use strict';
const {session}=require('electron');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {Mihomo}=require('./mihomo.cjs');
const {hintNode}=require('./library.cjs');
const {networkError}=require('./network-error.cjs');
const {IPLookup,DEFAULT_ENDPOINT,identity}=require('./ip-services.cjs');
const TARGETS={latency:'https://www.cloudflare.com/cdn-cgi/trace',ip:DEFAULT_ENDPOINT,speed:'https://speed.cloudflare.com/__down?bytes=5000000',fallback:'https://www.gstatic.com/generate_204'};
async function consume(response,limit,signal){if(!response.ok)throw Error('检测服务返回 HTTP '+response.status);if(!response.body)return {bytes:0,text:''};const reader=response.body.getReader();let bytes=0;const chunks=[];try{for(;;){signal.throwIfAborted();const {done,value}=await reader.read();if(done)break;bytes+=value.length;if(bytes>limit)throw Error('检测响应超出上限');chunks.push(Buffer.from(value));}return {bytes,text:Buffer.concat(chunks).toString('utf8')};}finally{await reader.cancel().catch(()=>{});}}
class Diagnostics {
 constructor(controller){this.controller=controller;this.history=new (require('./diagnostic-history.cjs').DiagnosticHistory)(controller?.dir);this.ipLookup=new IPLookup();this.results=new Map();this.lastJob=null;this.job=null;this.work=null;this.abort=null;this.cores=new Set();this.standalone=new Set();}
 get activeCore(){return [...this.cores][0]||null;}
 itemUnchanged(item){if(!item.instanceId)return this.controller.library.data.sources.find(s=>s.id===item.sourceId)?.updatedAt===item.sourceVersion;try{return require('./instance-node.cjs').resolveInstanceNode(this.controller.store,item.instanceId,item.name).sourceId===item.sourceId;}catch{return false;}}
 snapshot(){return {job:this.job,lastJob:this.lastJob,results:[...this.results.values()],historyVersion:this.history.version};}
 cancel(){this.abort?.abort(Error('已取消测试'));if(this.job){this.job={...this.job,cancelling:true};this.controller.emit();}}
 async close(){this.timeAbort?.abort();await this.timeWork?.catch(()=>{});this.cancel();await this.work?.catch(()=>{});const standalone=[...this.standalone];for(const item of standalone)item.abort.abort();await Promise.allSettled(standalone.map(item=>item.promise));this.history.flush();const cores=[...this.cores];for(const core of cores){await core.stop();this.cores.delete(core);}}
 probeStandalone(node){const abort=new AbortController(),item={abort,promise:null};item.promise=this.probe(node,'latency',abort.signal,'entry-'+crypto.randomUUID()).finally(()=>this.standalone.delete(item));this.standalone.add(item);return item.promise;}
 run(items,kind,concurrency=3){if(this.work)throw Error('已有检测任务，请等待或取消');if([...this.cores].some(core=>core.child))throw Error('检测内核尚未退出，请退出应用重试清理');if(!['latency','ip','speed'].includes(kind))throw Error('检测类型无效');if(!Array.isArray(items)||!items.length||items.length>100)throw Error('每次请选择 1–100 个节点');if(kind==='speed'&&items.length!==1)throw Error('下载测速仅允许单节点手动执行');const count=Number(concurrency);if(!Number.isInteger(count)||count<1||count>16)throw Error('并发数须为1–16');const unique=[...new Map(items.map(item=>[JSON.stringify([item.instanceId||item.sourceId,item.name]),item])).values()];const list=unique.map(item=>{if(item.instanceId)return require('./instance-node.cjs').resolveInstanceNode(this.controller.store,item.instanceId,item.name);const source=this.controller.library.get(item.sourceId);if(hintNode(item.name)&&!(source.enabledHints||[]).includes(item.name))throw Error('疑似订阅提示条目默认不检测，请先在列表中手动启用');return {...item,sourceVersion:source.updatedAt,node:this.controller.library.node(item.sourceId,item.name)};});this.abort=new AbortController();const workers=kind==='speed'?1:Math.min(count,list.length);this.job={id:crypto.randomUUID(),startedAt:new Date().toISOString(),kind,total:list.length,done:0,name:'准备检测',concurrency:workers,cancelling:false,items:list.map(item=>({sourceId:item.sourceId,instanceId:item.instanceId||null,name:item.name,state:'queued'}))};this.controller.workspace.log('diagnostic',`开始${kind}检测：${list.length}个节点，并发${workers}`,'INFO',null,{taskId:this.job.id});this.controller.emit();this.work=this.execute(list,kind,workers).catch(()=>{this.controller.workspace.log('diagnostic','检测任务异常终止','ERROR');}).finally(()=>{if(this.job)this.lastJob={...this.job,endedAt:new Date().toISOString(),cancelled:!!this.abort?.signal.aborted};this.controller.workspace.log('diagnostic',this.abort?.signal.aborted?'检测已取消':'检测任务结束','INFO',null,{taskId:this.job?.id});this.work=null;this.job=null;this.abort=null;this.controller.emit();});return {started:true};}
 async execute(items,kind,workers){let next=0;const signal=this.abort.signal;const worker=async slot=>{for(;;){if(signal.aborted||this.controller.disposing)return;const index=next++;if(index>=items.length)return;const item=items[index];this.job.items[index].state='running';this.job={...this.job,name:this.job.items.filter(x=>x.state==='running').map(x=>x.name).join(' / ')};(this.controller.emitSoon?this.controller.emitSoon():this.controller.emit());const key=JSON.stringify([item.sourceId,item.name,kind]);let result={taskId:this.job.id,sourceId:item.sourceId,instanceId:item.instanceId||null,name:item.name,kind,at:new Date().toISOString()};try{let value;try{value=await this.probe(item.node,kind,signal,slot);}catch(first){if([...this.cores].some(core=>core.diagnosticSlot===slot)){this.abort.abort();throw first;}if(kind!=='latency'||signal.aborted)throw first;value=await this.probe(item.node,kind,signal,slot,true);value.fallback=true;}result={...result,...value,ok:true};}catch(e){result={...result,ok:false,error:signal.aborted?'已取消':(e.safeDiagnostic||'检测失败：未取得具体原因')+'（未回退直连）'};}if(!this.itemUnchanged(item))result={taskId:this.job.id,sourceId:item.sourceId,name:item.name,kind,at:new Date().toISOString(),ok:false,error:'节点源已更新或删除，请重新检测'};this.results.delete(key);this.results.set(key,result);this.history.record(result);if(this.results.size>500)this.results.delete(this.results.keys().next().value);this.job.items[index].state=result.ok?'success':signal.aborted?'cancelled':'failed';this.job={...this.job,done:this.job.done+1};this.controller.workspace.log('diagnostic',`${kind}检测${result.ok?'成功':result.error}`,result.ok?'INFO':signal.aborted?'INFO':'WARN',item.instanceId||null,{taskId:this.job.id,sourceId:item.sourceId,nodeName:item.name});(this.controller.emitSoon?this.controller.emitSoon():this.controller.emit());}};await Promise.all(Array.from({length:workers},(_,i)=>worker(i)));for(const [index,item]of items.entries())if(this.job.items[index].state==='queued'){this.results.set(JSON.stringify([item.sourceId,item.name,kind]),{taskId:this.job.id,sourceId:item.sourceId,name:item.name,kind,ok:false,error:'已取消',at:new Date().toISOString()});}}

 async timezone(id,network){if(this.timeWork)throw Error('已有出口地区查询，请稍候');const x=this.controller.store.get(id),mode=network?.mode||x.network.mode;if(!['direct','mihomo'].includes(mode))throw Error('无效网络模式');const node=mode==='mihomo'?this.controller.store.nodes(id).find(n=>n.name===(network?.nodeName||x.network.nodeName)):null;if(mode==='mihomo'&&!node)throw Error('请选择有效节点；不会回退直连');this.timeAbort=new AbortController();this.timeWork=this.probe(node,'ip',this.timeAbort.signal,'timezone').then(result=>{const locale=require('./exit-locale.cjs').fromProbe(result);this.controller.workspace.log('instance','已查询出口时区和语言：'+locale.timezone+' / '+locale.language,'INFO',id);return locale;}).catch(()=>{throw Error('查询出口时区和语言失败，原值保留；代理模式未回退直连');}).finally(()=>{this.timeWork=null;this.timeAbort=null;this.controller.emit();});return this.timeWork;}
 async probe(node,kind,cancel,slot=0,fallback=false,options={}){const dir=path.join(this.controller.dir,'diagnostic-runtime',crypto.randomUUID());const abort=new AbortController();const timer=setTimeout(()=>abort.abort(Error('检测超时')),kind==='latency'?12000:35000);const signal=AbortSignal.any([cancel,abort.signal]);const core=new Mihomo(this.controller.binary,dir,()=>abort.abort(Error('检测内核退出')),this.controller.nodeNetwork);core.diagnosticSlot=slot;this.cores.add(core);let s;
 try{const port=node?(await core.start(node,signal)).port:null;signal.throwIfAborted();s=session.fromPartition('arena-core-diagnostics-'+slot,{cache:false});await s.closeAllConnections();await s.setProxy(node?{mode:'fixed_servers',proxyRules:`http://127.0.0.1:${port}`,proxyBypassRules:'<-loopback>'}:{mode:'direct'});await s.closeAllConnections();require('./browser-network-policy.cjs').resumeDictionaries(s);if(kind==='ip')return await this.ipLookup.lookup(identity(node),async(url,requestSignal)=>{const proxy=await s.resolveProxy(url);if(proxy!==(node?`PROXY 127.0.0.1:${port}`:'DIRECT'))throw Error('检测代理未生效');return s.fetch(url,{signal:requestSignal,redirect:'error',cache:'no-store',credentials:'omit',bypassCustomProtocolHandlers:true,headers:{'User-Agent':'Facet/'+require('../../package.json').version}});},signal,{force:options.force!==false,requireLocale:options.requireLocale!==false,...(TARGETS.ip!==DEFAULT_ENDPOINT?{providers:[{id:'ipwho',name:'ipwho.is',url:TARGETS.ip}]}:{})});const url=fallback?TARGETS.fallback:TARGETS[kind];const proxy=await s.resolveProxy(url);if(proxy!==(node?`PROXY 127.0.0.1:${port}`:'DIRECT'))throw Error('检测代理未生效');const begin=performance.now();const response=await s.fetch(url,{signal,redirect:'error',cache:'no-store',credentials:'omit',bypassCustomProtocolHandlers:true});const headersMs=performance.now()-begin;const body=await consume(response,kind==='speed'?5000000:65536,signal);const elapsedMs=performance.now()-begin;if(kind==='speed'){if(body.bytes!==5000000)throw Error('测速数据不完整');return {bytes:body.bytes,elapsedMs:Math.round(elapsedMs),mbps:Number((body.bytes*8/elapsedMs/1000).toFixed(2)),provider:'Cloudflare · 5 MB'};}if(fallback?response.status!==204:!/^ip=.+$/m.test(body.text))throw Error('检测响应无效');return {latencyMs:Math.round(headersMs),provider:(fallback?'Google 204 备用':'Cloudflare')+' · HTTPS 首响应（含连接/TLS）'};
 }catch(e){const safe=new Error('代理检测失败');const status=String(e.message||'').match(/^检测服务返回 HTTP (\d{3})$/);safe.safeDiagnostic=e.safeDiagnostic||core.recentIssue()||(abort.signal.aborted?'检测超时或内核退出':status?'检测服务返回 HTTP '+status[1]+'，不等于节点不可用':networkError(e.message)||'检测目标无法完成请求或响应无效');throw safe;}finally{clearTimeout(timer);try{await s?.closeAllConnections();await s?.clearStorageData();await s?.clearCache();}finally{await core.stop();this.cores.delete(core);fs.rmSync(dir,{recursive:true,force:true});}}}
}
module.exports={Diagnostics,TARGETS};
