'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),net=require('node:net');
const {atomic}=require('./store.cjs');
function canonicalIP(value){const ip=String(value||'').trim();if(!net.isIP(ip))throw Error('请输入有效IPv4或IPv6地址');if(!ip.includes(':'))return ip;const [address,...zone]=ip.split('%');return new URL('http://['+address+']/').hostname.slice(1,-1)+(zone.length?'%'+zone.join('%'):'');}
function redact(value){return String(value??'').replace(/authorization[\"']?\s*[:=]\s*[\"']?(?:bearer|basic)\s+[^\s\"']+/gi,'authorization=[已隐藏]').replace(/https?:\/\/[^\s<>"']+/gi,'[网址已隐藏]').replace(/\b(password|passwd|token|secret|authorization|uuid|username|cookie)[\"']?\s*[:=]\s*[\"']?[^\s,;\"']+/gi,'$1=[已隐藏]').slice(0,700);}
class Workspace {
 constructor(dir){this.file=path.join(dir,'workspace-tools.json');this.logFile=path.join(dir,'global-events.json');this.data=fs.existsSync(this.file)?JSON.parse(fs.readFileSync(this.file,'utf8')):{nodes:[],ips:[]};this.events=fs.existsSync(this.logFile)?JSON.parse(fs.readFileSync(this.logFile,'utf8')):[];if(!Array.isArray(this.data.nodes)||!Array.isArray(this.data.ips)||!Array.isArray(this.events))throw Error('工作空间数据格式无效');const seen=new Set();this.data.ips=this.data.ips.map(x=>({...x,ip:canonicalIP(x.ip)})).filter(x=>{if(seen.has(x.ip))return false;seen.add(x.ip);return true;});this.data.quickLinks=require('./quick-links.cjs').initialLinks(this.data.quickLinks);this.events=this.events.slice(0,1000);this.warning='';}
 commit(data){atomic(this.file,data);this.data=data;}
 favorite(sourceId,name){const exists=this.data.nodes.some(n=>n.sourceId===sourceId&&n.name===name);if(!exists&&this.data.nodes.length>=500)throw Error('收藏上限500个节点');this.commit({...this.data,nodes:exists?this.data.nodes.filter(n=>n.sourceId!==sourceId||n.name!==name):[...this.data.nodes,{sourceId,name,at:new Date().toISOString()}]});}
 saveIP(ip,note){ip=canonicalIP(ip);const text=String(note||'').trim();if(text.length>200)throw Error('备注上限200字');const old=this.data.ips.find(x=>x.ip===ip);if(!old&&this.data.ips.length>=500)throw Error('IP备忘上限500条');const row={id:old?.id||crypto.randomUUID(),ip,note:text,at:new Date().toISOString()};this.commit({...this.data,ips:old?this.data.ips.map(x=>x.ip===ip?row:x):[row,...this.data.ips]});}
 setIPFavorite(ip,selected,note){ip=canonicalIP(ip);if(typeof selected!=='boolean')throw Error('收藏状态无效');const existing=this.data.ips.find(x=>x.ip===ip);if(selected){if(!existing)this.saveIP(ip,note);}else if(existing)this.removeIP(existing.id);}
 selectedIPs(ids){if(!Array.isArray(ids)||ids.length>500||ids.some(x=>typeof x!=='string'))throw Error('请选择有效的IP备忘');const selected=new Set(ids);return this.data.ips.filter(x=>selected.has(x.id));}
 removeIPs(ids){const selected=new Set(this.selectedIPs(ids).map(x=>x.id));if(selected.size)this.commit({...this.data,ips:this.data.ips.filter(x=>!selected.has(x.id))});}
 removeIP(id){this.removeIPs([id]);}
 quickLink(id){const row=this.data.quickLinks.find(x=>x.id===id);if(!row)throw Error('快捷网站已不存在，请刷新后重试');return row;}
 saveQuickLink(value){const fields=require('./quick-links.cjs').linkFields(value);if(value.id){this.quickLink(value.id);this.commit({...this.data,quickLinks:this.data.quickLinks.map(x=>x.id===value.id?{id:x.id,...fields}:x)});}else{if(this.data.quickLinks.length>=20)throw Error('快捷网站最多20个');this.commit({...this.data,quickLinks:[...this.data.quickLinks,{id:crypto.randomUUID(),...fields}]});}}
 removeQuickLink(id){this.quickLink(id);this.commit({...this.data,quickLinks:this.data.quickLinks.filter(x=>x.id!==id)});}
 moveQuickLink(id,direction){this.quickLink(id);if(![-1,1].includes(direction))throw Error('排序方向无效');const rows=[...this.data.quickLinks],i=rows.findIndex(x=>x.id===id),j=i+direction;if(j<0||j>=rows.length)return;[rows[i],rows[j]]=[rows[j],rows[i]];this.commit({...this.data,quickLinks:rows});}
 log(scope,text,level='INFO',instanceId=null,context={}){const row={taskId:context.taskId||null,sourceId:context.sourceId||null,nodeName:context.nodeName?redact(context.nodeName):null,id:crypto.randomUUID(),time:new Date().toISOString(),scope,level,instanceId,text:redact(text)};this.events=[row,...this.events].slice(0,1000);try{atomic(this.logFile,this.events);this.warning='';}catch{this.warning='全局日志写盘失败；当前记录仅保留在内存，请检查磁盘权限或空间';}}
 snapshot(library){return {quickLinks:this.data.quickLinks,favorites:{nodes:this.data.nodes.map(n=>{let available=false;try{library.node(n.sourceId,n.name);available=true;}catch{}return {...n,available,sourceName:library.data.sources.find(s=>s.id===n.sourceId)?.name||'来源已删除'};}),ips:this.data.ips},events:this.events,logWarning:this.warning};}
}
module.exports={Workspace,redact,canonicalIP};
