
'use strict';
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',browser:'M3 5h18v15H3z M3 9h18 M6 7h.01 M9 7h.01',plus:'M12 5v14 M5 12h14',chevron:'M9 5l7 7-7 7',arrow:'M7 17L17 7 M7 7h10v10',up:'M12 18V6 M6 12l6-6 6 6',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M3 12h18 M12 3c-5 5-5 13 0 18 M12 3c5 5 5 13 0 18',fingerprint:'M7 6c3-4 9-3 11 0 M4 11c0-8 16-8 16 0 M8 19c2-3 1-5 1-8 0-4 6-4 6 0 0 5-1 8-3 11 M5 15v-4 M18 12c0 3 0 5-1 8 M12 11v5',play:'M8 5l11 7-11 7z',stop:'M6 6h12v12H6z',log:'M5 3h14v18H5z M8 8h8 M8 12h8 M8 16h5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M4 21v-2a8 8 0 0 1 16 0v2',refresh:'M20 7v5h-5 M4 17v-5h5 M5 8a8 8 0 0 1 14-2l1 6 M4 12l1 6a8 8 0 0 0 14-2',box:'M12 3l9 5v9l-9 5-9-5V8z M3 8l9 5 9-5 M12 13v9 M7 5l9 5',spark:'M12 3l2.8 6.2L21 12l-6.2 2.8L12 21l-2.8-6.2L3 12l6.2-2.8z',lock:'M6 11h12v10H6z M8 11V7a4 4 0 0 1 8 0v4',info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 11v6 M12 7h.01',monitor:'M3 4h18v13H3z M8 21h8 M12 17v4',check:'M5 12l4 4L19 6',back:'M15 5l-7 7 7 7',link:'M9 15l6-6 M8 16l-2 2a4 4 0 0 1-5-5l4-4a4 4 0 0 1 5 0 M16 8l2-2a4 4 0 0 1 5 5l-4 4a4 4 0 0 1-5 0',edit:'M4 16l12-12 4 4L8 20H4z M13 7l4 4',copy:'M8 8h12v13H8z M4 16H2V2h13v2',close:'M6 6l12 12 M6 18L18 6',star:'M12 4l2.5 5 5.5.8-4 3.9.9 5.5L12 16.6 7.1 19.2 8 13.7 4 9.8 9.5 9z',more:'M5.5 12h.01 M12 12h.01 M18.5 12h.01',search:'M11 5a6 6 0 1 0 0 12 6 6 0 0 0 0-12 M16 16l4 4',bolt:'M13 3L5 13.5h6L10 21l8-10.5h-6z',download:'M12 4v11 M7 10.5l5 5 5-5 M5 20h14',trash:'M5 7h14 M10 7V4.5h4V7 M7 7l1 13h8l1-13'};
function icon(n){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.grid}"></path></svg>`}
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bridge=window.arenaCore;
let state={instances:[],coreInstalled:false},activeId=null,view='browser',filter='all',search='',selected=new Set(),modal=null,toastTimer,lastFocus,contentKey='';
const localOpen=new Set();
let renderedTabId=null;
const globalViews=['overview','grid','global','settings','proxies','favorites','global-logs','runtime-output','extensions'];
const current=()=>state.instances.find(x=>x.id===activeId);
const statusText=x=>({running:'运行中',starting:'启动中',stopped:'已停止',error:'异常'}[x.status]||'已停止');
const networkText=x=>x.network.mode==='direct'?'本机 IP 直连':('Mihomo · '+(x.network.nodeName||'未选择节点'));
function currentNodeIP(x){if(x?.network?.mode!=='mihomo')return null;const name=x.network.nodeName,key=x.nodeDiagnosticKeys?.[name],own=key?nodeOutcome(key,name,'ip').r:null;if(own)return own.ok?own:null;const assignment=x.assignment||{};if(!assignment.sourceId||assignment.name!==name||assignment.status!=='配置已同步')return null;return state.diagnostics?.results?.find(r=>r.kind==='ip'&&r.ok&&r.sourceId===assignment.sourceId&&r.name===name)||null;}
function nodeIPText(x){const result=currentNodeIP(x);return result?.ip?`出口 IP ${result.ip}`:'出口 IP 尚未查询';}
const envText=x=>x.environment.language+' · '+x.environment.timezone;
function status(x){return `<span class="status ${x.status}"><i class="dot ${x.status}"></i>${statusText(x)}</span>${proxyAlertHTML(x)}`;}
// 代理可能断开（只提醒，不自动切换节点、不改直连）。
function proxyAlertHTML(x){return x?.proxyAlert&&x.status==='running'?`<span class="proxy-alert" title="${esc(x.proxyAlert+(x.proxyAlertAt?' · '+new Date(x.proxyAlertAt).toLocaleTimeString():'')+'。未自动切换节点，也不会改为直连。')}">代理可能已断开</span>`:'';}
function toast(text){$('#toast').innerHTML=icon('info')+`<span>${esc(text)}</span>`;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
function updateTabScroller(){const shell=$('#tabsShell'),tabs=$('#tabs');if(!shell||!tabs)return;const overflow=tabs.scrollWidth>tabs.clientWidth+1;shell.classList.toggle('has-overflow',overflow);const left=shell.querySelector('[data-tabs-scroll="-1"]'),right=shell.querySelector('[data-tabs-scroll="1"]');if(left)left.disabled=!overflow||tabs.scrollLeft<=1;if(right)right.disabled=!overflow||tabs.scrollLeft+tabs.clientWidth>=tabs.scrollWidth-1;}
function revealTab(id){const tabs=$('#tabs'),tab=tabs?.querySelector(`[data-tab="${id}"]`)?.closest('.tab');if(!tab)return;const bounds=tabs.getBoundingClientRect(),rect=tab.getBoundingClientRect();if(rect.left<bounds.left)tabs.scrollLeft+=rect.left-bounds.left;else if(rect.right>bounds.right)tabs.scrollLeft+=rect.right-bounds.right;updateTabScroller();}
async function request(action,payload={}){if(!bridge)throw Error('这是浏览器界面预览。请运行新项目的 npm start 使用真实功能。');const r=await bridge.request(action,payload);if(!r.ok)throw Error(r.error);return r.value;}
async function call(action,payload={}){try{return await request(action,payload);}catch(e){toast(e.message);return undefined;}}
function nav(name,label,target){return `<button class="nav ${view===target?'active':''}" title="${label}" aria-label="${label}" data-view="${target}" ${!current()&&!globalViews.includes(target)?'disabled':''}>${icon(name)}<span class="nav-label">${label}</span></button>`;}
function render(force=false){
 refreshIPBookmarks();refreshQuickLinksManager();
 document.documentElement.dataset.page=view;scheduleUiSave();if(view!=='grid'&&typeof gridLeave==='function')gridLeave();
 const x=current(),global=globalViews.includes(view),focus=document.activeElement,typing=focus?.id==='addressField'?{value:focus.value,start:focus.selectionStart,end:focus.selectionEnd}:null,refocus=captureShellFocus();
 if(contentKey&&contentKey!==view+':'+activeId)rememberScroll(contentKey);
 $('#headerSummary').innerHTML=`<i class="dot running"></i><b>${state.instances.filter(i=>i.status==='running').length}</b> 运行 · ${state.instances.length} 实例`;
 $('#newTab').innerHTML=icon('plus');$('#allTabs').innerHTML=icon('grid');
 const tabScrollLeft=$('#tabs').scrollLeft,selectedTabId=global?null:activeId,tabChanged=selectedTabId!==renderedTabId;renderedTabId=selectedTabId;
 $('#tabs').innerHTML=state.instances.filter(i=>localOpen.has(i.id)).map(i=>`<div class="tab ${i.id===activeId&&!global?'active':''}"><button class="tab-select" role="tab" aria-selected="${i.id===activeId&&!global}" data-tab="${i.id}" title="${esc(i.name)} · ${esc(networkText(i))}"><i class="dot ${i.status}"></i><span class="tab-name">${esc(i.name)}</span>${i.proxyAlert&&i.status==='running'?`<b class="tab-alert" title="${esc('代理可能已断开：'+i.proxyAlert)}" aria-label="代理可能已断开">!</b>`:''}</button>${volButton(i,'tab-vol')}<button class="icon-btn tab-close" data-close="${i.id}" title="${i.status==='stopped'?'关闭':'停止并关闭'} ${esc(i.name)}" aria-label="${i.status==='stopped'?'关闭':'停止并关闭'} ${esc(i.name)}">×</button></div>`).join('')||'<span class="actions-note">从实例管理打开一个标签，或点 + 新建</span>';
 $('#tabs').scrollLeft=tabScrollLeft;updateTabScroller();requestAnimationFrame(()=>{if(tabChanged&&selectedTabId)revealTab(selectedTabId);else updateTabScroller();});
 const running=x?.status==='running',toggleLabel=running?'停止当前实例':'启动当前实例';
 const instanceBlock=`<div class="instance-card"><div class="instance-card-head"><h2 title="${esc(x?.name||'暂无实例')}">${esc(x?.name||'暂无实例')}</h2>${x?`<button class="icon-btn instance-rename" data-action="rename" title="重命名实例" aria-label="重命名实例">${icon('edit')}</button>`:''}</div><div class="instance-meta">${x?`${status(x)}<span class="instance-net" title="${esc(networkText(x))}">${esc(networkText(x))}</span>`:`<span>${state.instances.length} 个实例 · 新建后即可使用</span>`}</div></div><div class="actions-grid"><button class="btn ${running?'danger':'primary'} wide instance-toggle" title="${toggleLabel}（只影响当前实例；代理故障不会自动转为直连）" aria-label="${toggleLabel}" data-action="toggle" ${!x||x.status==='starting'?'disabled':''}>${icon(running?'stop':'play')}<span class="nav-label">${toggleLabel}</span></button></div><div class="side-label">当前实例</div><nav class="side-nav" aria-label="当前实例">${nav('browser','浏览页面','browser')}${nav('shield','环境配置','environment')}${nav('log','运行日志','logs')}</nav>`;
 $('#sidebar').innerHTML=`${instanceBlock}<div class="side-spacer"></div><div class="side-label">全局管理</div><nav class="side-nav" aria-label="全局管理">${nav('grid','实例管理','overview')}${nav('monitor','宫格总览','grid')}${nav('globe','代理管理','proxies')}${nav('box','扩展中心','extensions')}${nav('log','系统日志','global-logs')}${nav('log','运行输出','runtime-output')}${nav('settings','主题设置','settings')}${nav('info','应用信息','global')}</nav>`;
 const titles={extensions:'扩展中心',browser:'浏览页面',environment:'环境配置',logs:'运行日志',overview:'实例管理',grid:'宫格总览',global:'应用信息',settings:'主题设置',proxies:'代理管理',favorites:'节点收藏','global-logs':'系统日志','runtime-output':'运行输出'};
 const headActions={overview:`<button class="btn primary" data-action="new">${icon('plus')}新建实例</button>`,environment:`<button class="btn subtle" data-action="rename" title="修改当前实例名称">${icon('edit')}重命名实例</button>`,proxies:`<button class="btn" data-bookmark="open" title="节点收藏与 IP 收藏">${icon('star')}收藏夹<span class="count" data-favorite-total>${(state.favorites?.ips.length||0)+(state.favorites?.nodes.length||0)}</span></button>`};
 const head=$('#workspaceHead');head.hidden=view==='browser';head.innerHTML=view==='browser'?'':`<div class="workspace-title"><h1>${titles[view]}<span class="tag">${global?'全局':'仅当前实例'}</span></h1>${!global&&x?`<span class="head-instance" title="${esc(x.name)}">${esc(x.name)}</span>`:''}</div><div class="toolbar">${!global&&x?status(x):''}${headActions[view]||''}</div>`;
 $('#footerCore').textContent='内置 Mihomo · '+(state.coreInstalled?'已就绪':'未安装');refocus();
 $('#content').classList.toggle('extension-management',view==='extensions');$('#content').classList.toggle('proxy-management',view==='proxies');$('#content').classList.toggle('workspace-tools',['favorites','global-logs','runtime-output'].includes(view));$('#content').classList.toggle('grid-view',view==='grid');
 const key=view+':'+activeId;
 if(['environment','proxies','favorites','global-logs','runtime-output'].includes(view)&&contentKey===key&&!force){if(view==='proxies')renderDiagnostics();if(view==='favorites')favoriteNodeRows();if(view==='global-logs')globalLogRows();if(view==='runtime-output')runtimeOutputRows();if(view==='environment'){updateEnvironmentBar();renderInstanceNodeActions();}layout();return;}
 // 宫格：实例列表/状态没变时只同步格子位置，不重建（避免缩略图闪烁）。
 if(view==='grid'&&contentKey===key&&!force&&gridSignature()===gridSig){renderExtensionMenu();positionExtensionMenu();layout();return;}
 const switched=contentKey!==key;contentKey=key;
 if(view==='extensions')extensionPage();else if(view==='browser')browserPage(x);else if(view==='environment')environmentPage(x);else if(view==='proxies')libraryPage();else if(view==='favorites')favoritesPage();else if(view==='global-logs')globalLogsPage();else if(view==='runtime-output')runtimeOutputPage();else if(view==='overview')overview();else if(view==='grid')gridPage();else if(view==='logs')logsPage(x);else if(view==='settings')settingsPage();else globalPage();
 if(view==='environment'){environmentWarnings();mountEnvironment(x);mountInstanceNodeActions();applyUiDetails();}
 if(typing&&$('#addressField')){$('#addressField').value=typing.value;$('#addressField').focus();try{$('#addressField').setSelectionRange(typing.start,typing.end);}catch{}}
 renderExtensionMenu();positionExtensionMenu();
 layout();if(switched)restoreScroll(key);
}
function browserPage(x){if(!x){$('#content').innerHTML='<div class="page-empty"><h2>创建第一个独立实例</h2><p>不需要代理节点，即可明确选择本机 IP 直连。</p><button class="btn primary" data-action="new">新建实例</button></div>';return;}
 const run=x.status==='running';
 const ipResult=currentNodeIP(x),ipTitle=ipResult?.at?`最近检测：${new Date(ipResult.at).toLocaleString()}（非实时）`:'当前节点尚未完成 IP 检测';
 $('#content').innerHTML=`<div class="browser-shell"><form class="address-row" id="addressForm"><button type="button" class="icon-btn" data-action="back" aria-label="后退" title="后退" ${!x.canBack?'disabled':''}>${icon('back')}</button><button type="button" class="icon-btn" data-action="forward" aria-label="前进" title="前进" ${!x.canForward?'disabled':''}>${icon('chevron')}</button><button type="button" class="icon-btn" data-action="reload" aria-label="刷新" title="刷新" ${!run?'disabled':''}>${icon('refresh')}</button><div class="address-input">${icon(run?'lock':'globe')}<input id="addressField" aria-label="当前实例的网址" value="${esc(x.currentURL||x.url)}" ${!run?'disabled':''}><button class="btn tiny ghost address-go" type="submit" ${!run?'disabled':''}>前往</button></div>${extensionToolbarHTML(x)}</form>${quickLinksHTML(x)}<div id="browserHost" class="browser-page">${run?'<div class="page-empty"><p>正在显示独立浏览页面…</p><p class="actions-note">扩展的内容脚本已在页面自动运行；面板从地址栏右侧的扩展图标打开。</p></div>':instanceDetails(x)}</div>${x.error?`<div class="browser-alert" role="alert">${icon('info')}<span>${esc(x.error)}</span>${relatedLogButton(x.id)}</div>`:''}<div class="instance-strip"><span>${icon('globe')}${esc(networkText(x))}</span><span title="${esc(ipTitle)}">${icon('globe')}${esc(nodeIPText(x))}</span><span>${icon('fingerprint')}${esc(envText(x))}</span><span class="viewport-status">${icon('monitor')}${x.environment.width?'固定视口 '+x.environment.width+'×'+x.environment.height+' · 等比适配显示':'视口随窗口自适应'}</span><span class="end">${x.proxyPort?'回环端口 '+x.proxyPort:'独立持久会话'}</span></div></div>`;}
function environmentPage(x){if(!x){view='overview';render(true);return;}
 $('#content').innerHTML=`<div class="scope-note">${icon('info')}只设置「${esc(x.name)}」。保存配置或导入节点会停止此实例；重新启动后生效。</div><form id="environmentForm">${fingerprintPlan(x.environment)}<div class="settings-grid"><section class="settings-card"><h3>${icon('globe')}网络出口</h3><div class="inner"><label class="field"><span>连接方式</span><select id="networkMode"><option value="direct" ${x.network.mode==='direct'?'selected':''}>本机 IP 直连（无需节点）</option><option value="mihomo" ${x.network.mode==='mihomo'?'selected':''}>内置 Mihomo 代理</option></select><small>直连会使用你的本机实际出口。代理失败不会自动转为直连。</small></label><label class="field"><span>此实例的代理节点</span><select id="proxyNodeName"><option value="">${x.nodes.length?'请选择节点':'尚未导入节点'}</option>${x.nodes.map(n=>`<option value="${esc(n)}" ${n===x.network.nodeName?'selected':''}>${esc(n)}</option>`).join('')}</select></label><button class="btn soft" type="button" data-view="proxies">${icon('globe')}打开全局代理管理</button><p class="actions-note">订阅与节点现统一在全局管理。可保存多个订阅，并将节点分配给指定实例。这里保留当前实例的节点副本；更新或删除全局订阅不会中断已配置实例。</p><div class="guide">内置核心：${state.coreInstalled?'已安装':'尚未安装，请运行 npm run setup:core'}。直连模式不需要内核。</div></div></section><section class="settings-card"><h3>${icon('fingerprint')}基础指纹环境</h3><div class="inner"><label class="field"><span>语言 / 区域</span><select id="language">${['zh-CN','en-US','ja-JP','en-GB'].map(l=>`<option ${l===x.environment.language?'selected':''}>${l}</option>`).join('')}</select></label><label class="field"><span>时区（IANA 标识）</span><input id="timezone" value="${esc(x.environment.timezone)}" placeholder="Asia/Tokyo"></label><button type="button" class="btn soft" data-fp="timezone">按当前所选出口 IP 填入时区</button><p class="actions-note">仅查询一次，不随启动更新；查询失败保留原值。更换代理节点后可重新同步。</p><div class="guide">默认沿用原生浏览器环境。高级参数只在明确保存并重新启动后生效；不能保证匿名或防检测。</div><p class="actions-note">这不代表匿名或不可识别。真实网站可能依据 IP、账号和其他信号识别设备。</p></div></section><section class="settings-card full"><h3>高级指纹与参考设备</h3><div class="inner">${advancedEnvironment(x)}</div></section></div><div class="environment-save-bar"><div><strong id="environmentSaveInfo" role="status"></strong><p id="environmentSaveError" class="error" role="alert" hidden></p></div><div class="subscription-actions"><button class="btn subtle" type="button" data-ux="discard-environment">放弃修改</button><span class="shortcut-hint" aria-hidden="true"><kbd>Ctrl</kbd>+<kbd>Enter</kbd> 保存</span><button class="btn primary" type="button" data-ux="save-environment" title="保存配置（Ctrl + Enter）" aria-keyshortcuts="Control+Enter">保存配置</button><button class="btn soft" type="button" data-ux="save-restart">保存并启动</button></div></div></form>`;}
function overview(){const rows=state.instances.filter(x=>(filter==='all'||x.status===filter)&&(x.name+' '+networkText(x)).toLowerCase().includes(search.toLowerCase()));const count=k=>k==='all'?state.instances.length:state.instances.filter(x=>x.status===k).length;
 $('#content').innerHTML=`<div class="overview-summary">${[['all','全部'],['running','运行中'],['error','异常'],['stopped','已停止']].map(([key,title])=>`<div class="stat ${key}"><strong>${count(key)}</strong><span>${title}</span></div>`).join('')}<p class="actions-note">可同时运行；登录存储和网络配置按实例独立管理。</p></div><div class="filters"><div class="segments">${[['all','全部'],['running','运行中'],['error','异常'],['stopped','已停止']].map(([key,title])=>`<button data-filter="${key}" class="${filter===key?'active':''}">${title}</button>`).join('')}</div><label class="search-box">${icon('search')}<input class="search" id="instanceSearch" value="${esc(search)}" placeholder="搜索实例或代理…" aria-label="搜索实例"></label></div>${selected.size?`<div class="batchbar"><span>已选择 ${selected.size} 个实例</span><button class="btn tiny" data-action="batch-start">依次启动</button><button class="btn tiny danger" data-action="batch-stop">停止所选</button><button class="btn ghost tiny" data-action="clear-selection">清空选择</button></div>`:''}<div class="table-wrap instance-grid"><table class="data-table instance-table"><thead><tr><th class="col-check"><span class="visually-hidden">选择</span></th><th>实例</th><th>状态</th><th>网络</th><th>环境</th><th>内核</th><th class="col-actions">操作</th></tr></thead><tbody>${rows.map(x=>`<tr class="managed-card ${selected.has(x.id)?'selected':''}"><td class="col-check"><input type="checkbox" class="check" data-select="${x.id}" ${selected.has(x.id)?'checked':''} aria-label="选择 ${esc(x.name)}"></td><td class="cell-name"><b title="${esc(x.name)}">${esc(x.name)}</b>${x.error?`<small class="cell-error" title="${esc(x.error)}">${esc(x.error)}</small>`:''}</td><td>${status(x)}</td><td class="cell-clip" title="${esc(networkText(x))}">${esc(networkText(x))}</td><td class="cell-muted">${esc(envText(x))}</td><td class="cell-muted">${x.pid?'PID '+x.pid:'未运行 / 不需要'}</td><td class="col-actions"><div class="card-actions"><button class="btn ${x.status==='running'?'':'primary'} tiny" data-ux="instance-open" data-id="${x.id}" ${x.status==='starting'?'disabled':''}>${x.status==='running'?'打开网页':x.status==='starting'?'启动中…':'启动'}</button><button class="btn ghost tiny" data-ux="instance-config" data-id="${x.id}">配置</button>${x.error?relatedLogButton(x.id,'日志'):''}<details class="card-more row-menu"><summary class="icon-btn" aria-label="更多实例操作" title="更多">${icon('more')}</summary><div class="menu"><button class="menu-item" data-ux="instance-rename" data-id="${x.id}">${icon('edit')}重命名</button><hr><button class="menu-item danger" data-delete="${x.id}">${icon('trash')}删除实例及数据</button></div></details></div></td></tr>`).join('')||'<tr><td colspan="7" class="empty-list">没有匹配的实例</td></tr>'}</tbody></table></div>`;}
function logsPage(x){$('#content').innerHTML=`<div class="section-intro"><p>仅记录生命周期和错误；不记录代理凭证或网页内容。</p></div><div class="log-wrap"><table class="logs-table"><thead><tr><th>时间</th><th>级别</th><th>事件</th></tr></thead><tbody>${(x?.logs||[]).map(l=>`<tr><td>${esc(l.time)}</td><td>${esc(l.level)}</td><td>${esc(l.text)}</td></tr>`).join('')||'<tr><td colspan="3">本次应用运行暂无日志</td></tr>'}</tbody></table></div>`;}
function settingsPage(){$('#content').innerHTML=`<div class="settings-grid">${window.arenaAppearance?.cardHTML?.()||''}</div>`;}
function globalPage(){$('#content').innerHTML=`<div class="section-intro"><p>千面 Facet 0.2.0（原 Arena Core）· 开发者：<b class="app-author">一冬</b> · 独立新项目，不读取旧应用的数据。</p></div><div class="settings-grid"><section class="settings-card full github-support-card"><h3>${icon('star')}支持开源项目</h3><div class="inner github-support-inner"><div><p>项目已在 GitHub 开源。如果这个项目对你有帮助，请打开项目主页并点一下 <b>Star</b>，帮助更多人发现它。</p><button class="github-repo-url" type="button" data-action="open-github" title="打开 GitHub 项目主页">github.com/HEYD66/arena-core</button></div><button class="btn primary github-star-btn" type="button" data-action="open-github">去 GitHub 点 Star ${icon('arrow')}</button></div></section><section class="settings-card full"><h3>已接入</h3><div class="inner"><p>真实浏览 · 独立持久会话 · 多实例并行 · 本机 IP 直连 · 内置 Mihomo · 按实例语言/区域/时区</p><div class="guide">关闭标签：停止实例但保留登录资料。删除实例：停止并清除该实例的浏览存储与配置，需单独确认。</div><p>应用退出会停止其自身创建的内核，不管理其他客户端。启动应用不会自动启动实例。</p></div></section><section class="settings-card full"><h3>明确的边界</h3><div class="inner"><p>当前不包含扩展商店、自动注册、换号、抽卡和订阅自动更新。摄像头、麦克风等权限默认拒绝；固定定位仅在实例中明确启用后提供。</p><p>不保证匿名、防检测或防泄漏；代理节点可用性取决于用户导入的配置。</p></div></section>${shortcutListHTML()}<section class="settings-card full" id="disclaimer"><h3>免责声明</h3><div class="inner"><ol class="disclaimer"><li>千面 Facet 由个人开发者「一冬」开发，仅供学习研究和合法用途，按“现状”提供，不附带任何明示或暗示的保证。</li><li>请遵守所在地法律法规以及所访问网站的服务条款。因使用本软件导致的账号受限或封禁、数据丢失、经济损失或法律责任，均由使用者自行承担，开发者不承担任何责任。</li><li>本软件不提供代理节点、订阅或任何网络服务；节点、订阅和扩展均由用户自行导入，其合法性与安全性由用户自行负责。</li><li>不保证匿名、防检测或防泄漏。指纹与环境设置仅用于区分各实例的浏览环境，不得用于欺诈、批量注册、规避平台风控等违规用途。</li><li>所有实例资料和配置只保存在本机，开发者不收集任何使用数据。</li><li>内置的 Mihomo 内核按其开源许可（GPL-3.0）分发，版权归原作者所有。</li></ol><p class="disclaimer-foot">继续使用即表示你已阅读并同意以上内容。</p></div></section></div>`;}
// While an HTML overlay (menu/dialog) is open the native page view must be hidden — HTML cannot draw above it.
// A still frame of the page is captured first and painted in its place, so the page stays visible under the overlay.
let pageSnapshot=null,layoutSeq=0;
function paintSnapshot(el){if(!el||!pageSnapshot||pageSnapshot.id!==activeId)return false;let img=el.querySelector('.page-snapshot');if(!img){img=document.createElement('img');img.className='page-snapshot';img.alt='';img.setAttribute('aria-hidden','true');el.append(img);}if(img.getAttribute('src')!==pageSnapshot.url)img.src=pageSnapshot.url;return true;}
function layout(){if(!bridge)return;const seq=++layoutSeq,el=$('#browserHost'),x=current(),live=!!el&&view==='browser'&&x?.status==='running',covered=!!modal||!!document.querySelector('dialog[data-browser-overlay][open]'),r=live&&!covered?el.getBoundingClientRect():null;
 if(r)lastBrowserHostSize={width:Math.round(r.width),height:Math.round(r.height)};if(view==='grid')gridSendLayout();
 const send=()=>bridge.request('layout',{id:activeId,bounds:r?{x:r.x,y:r.y,width:r.width,height:r.height}:null}).catch(()=>{});
 if(!live||!covered){pageSnapshot=null;const still=el?.querySelector('.page-snapshot');if(!still){send();return;}if(!live){still.remove();send();return;}send().finally(()=>requestAnimationFrame(()=>{if(seq===layoutSeq)still.remove();}));return;}
 if(paintSnapshot(el)){send();return;}
 const id=activeId;Promise.race([bridge.request('browser-snapshot',{id}),new Promise(done=>setTimeout(done,400,null))]).then(res=>{const url=res?.ok?res.value:null;if(seq===layoutSeq&&typeof url==='string'&&id===activeId){pageSnapshot={id,url};paintSnapshot($('#browserHost'));}}).catch(()=>{}).finally(()=>{if(seq===layoutSeq)send();});}
// 已停止的实例没有需要停止的东西：直接关闭标签，不再弹确认。
async function closeStoppedTab(id){localOpen.delete(id);if(activeId===id){activeId=state.instances.find(i=>localOpen.has(i.id))?.id||state.instances[0]?.id||null;if(!globalViews.includes(view))view=localOpen.size?'browser':'overview';}await call('activate',{id:view==='browser'?activeId:null});render(true);}
async function route(next,id){if(next==='favorites'){await route('proxies',id);openIPBookmarks('nodes');return;}if(view==='environment'&&(next!==view||id&&id!==activeId)&&!await confirmEnvironmentLeave())return;if(next==='proxies'&&!globalViews.includes(view))libraryTargetId=id||activeId;if(id){activeId=id;localOpen.add(id);}if(next==='extensions'&&typeof resetExtensionView==='function')resetExtensionView();if(view==='grid'&&next!=='grid')gridLeave();view=next;await call('activate',{id:next==='browser'?activeId:null});render(true);if(id)requestAnimationFrame(()=>revealTab(id));}
function newEnvironmentDefaults(){return {language:'zh-CN',timezone:'Asia/Tokyo',width:0,height:0,scale:0,cpu:0,userAgent:'',platform:'',colorScheme:'system',reducedMotion:'system',geoEnabled:false,latitude:0,longitude:0,fingerprint:{}};}
function newEnvironmentSummary(value){const f=value?.fingerprint||{},label=(typeof fingerprintPresets!=='undefined'&&fingerprintPresets.find(([id])=>id===f.template)?.[1])||'随机设备方案';return `${label} · ${value?.platform||'原生平台'} · CPU ${value?.cpu||'原生'} · 固定种子已生成`;}
function newEnvironmentFields(){return `<div class="new-environment-plan"><div><strong>新实例环境</strong><span id="newEnvironmentSummary" class="actions-note">使用原生浏览器环境</span></div><div class="subscription-actions"><button class="btn tiny primary" type="button" data-new-env="random">一键随机</button><button class="btn tiny subtle" type="button" data-new-env="native">使用原生环境</button></div><p class="actions-note">随机方案会生成独立固定种子，并启用 Canvas、音频和 WebGL 覆盖；结果随创建保存，创建后可在“环境配置”继续调整。</p></div>`;}function openModal(type,id){lastFocus=document.activeElement;rememberModalFocus();modal={type,id:id||activeId,ids:type.startsWith('batch')?[...selected]:[],newEnvironment:null};const x=state.instances.find(i=>i.id===modal.id);const names=modal.ids.map(id=>state.instances.find(i=>i.id===id)?.name).filter(Boolean).join('、');const texts={'leave-environment':['有未保存修改',''],'creation-result':['实例已创建',''],'result-detail':['检测详情',''],'library-confirm':['确认代理操作',''],new:['新建独立实例','默认直连；也可从全局库选择节点副本，代理失败不回退直连。'],rename:['重命名实例','不改变登录资料和网络配置。'],close:['停止并关闭这个标签？','实例配置和登录资料保留，可从实例管理重新打开。'],delete:['删除实例及其浏览数据？',`将停止「${x?.name}」，清除其 Cookie、浏览存储和配置。此操作不可撤销。`],import:['导入代理节点配置？','导入会停止当前实例。只读取你选择的本地文件，不自动启用代理。'],subscription:['导入这个订阅？','通过本机网络下载。仅在内容下载和校验成功后停止当前实例、替换节点；失败保留原配置。不会自动切换网络模式。HTTP 链接不加密，推荐使用 HTTPS。'],'refresh-subscription':['更新此实例的订阅？','使用本机保存的链接重新下载。成功后停止当前实例并替换节点；失败保留原配置及原运行状态。不会自动切换到代理。'],'batch-start':['依次启动所选实例？',names],'batch-stop':['停止所选实例？',names]};const [title,description]=texts[type];$('#modal').innerHTML=`<div class="modal-head"><h2 id="modalTitle">${title}</h2><button class="icon-btn" data-action="modal-close" aria-label="取消">×</button></div><p class="description">${esc(description)}</p>${['new','rename'].includes(type)?`<form id="nameForm"><label class="field"><span>实例名称</span><input id="nameInput" maxlength="40" value="${type==='rename'?esc(x?.name):esc(suggestedInstanceName())}" required></label>${type==='new'?newNetworkFields()+newEnvironmentFields()+'<label><input id="timezoneNew" type="checkbox" checked> 按所选出口 IP 设置一次时区（访问 ipwho.is）</label><p class="actions-note">只在创建时查询一次；以后换节点可在环境设置中手动同步。查询失败保留默认时区并记录警告。</p><label><input id="startNew" type="checkbox" checked> 创建后启动</label>':''}</form>`:''}<p id="creationProgress" class="actions-note" role="status"></p><div id="nameError" class="error"></div><div class="modal-actions"><button class="btn subtle" data-action="modal-close">取消</button><button class="btn ${type==='delete'?'danger':'primary'}" data-action="confirm">确认</button></div>`;$('#modalBackdrop').hidden=false;layout();const focusModal=modal;setTimeout(()=>{if(modal===focusModal)($('#nameInput')||$('#modal button:not(:disabled)'))?.focus();},0);}
function closeModal(force=false){if((modal?.busy||modal?.newEnvironmentBusy)&&!force)return;const leaveResolve=modal?.leaveResolve;modal=null;if(!force)leaveResolve?.(false);$('#modalBackdrop').hidden=true;if($('#modal').classList.contains('proxy-entry-modal')){$('#modal').classList.remove('proxy-entry-modal');$('#modal').replaceChildren();}restoreModalFocus();layout();}
async function confirm(){if(!modal||modal.newEnvironmentBusy)return;const data={...modal};const btn=$('#modal [data-action="confirm"]');if(btn.disabled)return;btn.disabled=true;btn.textContent='处理中…';modal.busy=true;$('#modal').querySelectorAll('[data-action="modal-close"]').forEach(b=>b.disabled=true);updateCreationProgress();let imported,creationResult,assignedId;try{
 if(data.type==='library-confirm'){await request(data.operation,data.payload);if(data.operation==='diagnostic-start'&&$('#rememberDiagnosticConsent')?.checked)diagnosticConsent.add(data.payload.kind);if(data.operation==='library-assign')assignedId=data.payload.id;if(data.operation==='library-delete-nodes'||data.operation==='library-remove')librarySelected.clear();toast('操作已完成');}
 else if(data.type==='new'){creationResult=await request('create',{detailed:true,name:$('#nameInput').value,start:$('#startNew').checked,syncTimezone:$('#timezoneNew').checked,sourceId:$('#newSource').value,nodeName:$('#newNode').value,environment:modal.newEnvironment||undefined});const id=creationResult.id;localOpen.add(id);activeId=id;view='browser';}
 else if(data.type==='rename')await request('rename',{id:data.id,name:$('#nameInput').value});
 else if(data.type==='close'){await request('stop',{id:data.id});localOpen.delete(data.id);if(activeId===data.id){activeId=state.instances.find(i=>localOpen.has(i.id))?.id||state.instances[0]?.id||null;view=localOpen.size?'browser':'overview';}}
 else if(data.type==='delete'){await request('remove',{id:data.id});localOpen.delete(data.id);selected.delete(data.id);if(activeId===data.id)activeId=state.instances[0]?.id||null;view='overview';}
 else if(data.type==='import'){await request('import',{id:data.id});}
 else if(data.type==='subscription'||data.type==='refresh-subscription'){imported=await request(data.type==='subscription'?'import-subscription':'refresh-subscription',{id:data.id,...(data.type==='subscription'?{url:data.url}:{})});}
 else if(data.type.startsWith('batch')){const errors=[];for(const id of data.ids){try{await request(data.type==='batch-start'?'start':'stop',{id});}catch(e){errors.push(e.message);}}selected.clear();if(errors.length)toast(errors.join('；'));}
 closeModal(true);if(imported)toast(`订阅已导入 ${imported.count} 个节点。请选择节点并保存，网络模式未自动改变。`);await call('activate',{id:view==='browser'?activeId:null});render(true);if(creationResult)showCreationResult(creationResult);if(assignedId)showAssignmentResult(assignedId);
 }catch(e){$('#modal').querySelectorAll('[data-action="modal-close"]').forEach(b=>b.disabled=false);if(modal)modal.busy=false;$('#nameError').textContent=e.message;btn.disabled=false;btn.textContent='确认';}}
 document.addEventListener('click',async e=>{const newEnv=e.target.closest('[data-new-env]');if(newEnv){const targetModal=modal;if(!targetModal||targetModal.type!=='new'||targetModal.busy||targetModal.newEnvironmentBusy||newEnv.disabled)return;newEnv.disabled=true;targetModal.newEnvironmentBusy=true;const confirmButton=$('#modal [data-action="confirm"]');if(confirmButton)confirmButton.disabled=true;try{if(newEnv.dataset.newEnv==='native'){targetModal.newEnvironment=null;$('#newEnvironmentSummary').textContent='使用原生浏览器环境';}else{const value=await request('fingerprint-preset',{preset:'random',environment:newEnvironmentDefaults()});if(modal!==targetModal||targetModal.type!=='new')return;targetModal.newEnvironment=value;$('#newEnvironmentSummary').textContent=newEnvironmentSummary(value);}}catch(error){if(modal===targetModal)toast(error.message);}finally{targetModal.newEnvironmentBusy=false;if(newEnv.isConnected)newEnv.disabled=false;if(modal===targetModal&&confirmButton?.isConnected)confirmButton.disabled=false;}return;}const tabScroll=e.target.closest('[data-tabs-scroll]');if(tabScroll){const tabs=$('#tabs');if(tabs){const direction=Number(tabScroll.dataset.tabsScroll)||1;tabs.scrollBy({left:direction*Math.max(220,tabs.clientWidth*.72),behavior:'smooth'});setTimeout(updateTabScroller,220);}return;}const tab=e.target.closest('[data-tab]');if(tab){await route('browser',tab.dataset.tab);return;}const nav=e.target.closest('[data-view]');if(nav){await route(nav.dataset.view,nav.dataset.instance);return;}const close=e.target.closest('[data-close]');if(close){const target=state.instances.find(i=>i.id===close.dataset.close);if(target&&target.status==='stopped'){await closeStoppedTab(target.id);return;}openModal('close',close.dataset.close);return;}const del=e.target.closest('[data-delete]');if(del){openModal('delete',del.dataset.delete);return;}const filt=e.target.closest('[data-filter]');if(filt){filter=filt.dataset.filter;overview();return;}const btn=e.target.closest('[data-action]');if(!btn||btn.disabled)return;const action=btn.dataset.action,x=current();
  if(action==='new')openModal('new');else if(action==='rename')openModal('rename');else if(action==='import')openModal('import');else if(action==='import-subscription'){const value=$('#subscriptionURL').value.trim();if(!value){toast('请先粘贴订阅链接');return;}openModal('subscription');modal.url=value;}else if(action==='refresh-subscription')openModal('refresh-subscription');else if(action==='open-github')await call('open-github');else if(action==='modal-close')closeModal();else if(action==='confirm')await confirm();else if(action==='toggle'&&x){btn.disabled=true;await call(x.status==='running'?'stop':'start',{id:x.id});render();}else if(['back','forward','reload'].includes(action))await call(action,{id:x.id});else if(action.startsWith('batch'))openModal(action);else if(action==='clear-selection'){selected.clear();overview();}});
 document.addEventListener('submit',async e=>{e.preventDefault();if(e.target.id==='nameForm'){await confirm();return;}const x=current();if(!x)return;if(e.target.id==='addressForm'){await call('navigate',{id:x.id,url:$('#addressField').value});}if(e.target.id==='environmentForm'){await saveEnvironment();}});
 document.addEventListener('change',e=>{if(e.target.matches('[data-select]')){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);overview();}});
 document.addEventListener('input',e=>{if(e.target.id==='instanceSearch'){search=e.target.value;const pos=e.target.selectionStart;overview();$('#instanceSearch').focus();$('#instanceSearch').setSelectionRange(pos,pos);}});
 document.addEventListener('keydown',e=>{if(e.target.id==='subscriptionURL'&&e.key==='Enter'&&!modal){e.preventDefault();document.querySelector('[data-action="import-subscription"]').click();return;}if(!modal)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const list=[...$('#modal').querySelectorAll('button,input,select,textarea,a[href],[tabindex]')].filter(el=>!el.disabled&&el.tabIndex>=0&&el.getClientRects().length),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 $('#modalBackdrop').addEventListener('click',e=>{if(e.target===$('#modalBackdrop'))closeModal();});window.addEventListener('resize',()=>{layout();updateTabScroller();});$('#tabs')?.addEventListener('scroll',updateTabScroller,{passive:true});$('#content').addEventListener('scroll',()=>{if(view==='grid'&&typeof gridScrollStart==='function')gridScrollStart();layout();});
 // Row "⋯" menus (overview, proxy nodes): fixed-position popovers so scroll containers never clip them.
 function positionRowMenu(d){const m=d.querySelector(':scope>.menu'),t=d.querySelector(':scope>summary');if(!m||!t)return;const r=t.getBoundingClientRect(),w=m.offsetWidth,h=m.offsetHeight;m.style.left=Math.max(8,Math.min(r.right-w,innerWidth-w-8))+'px';m.style.top=(r.bottom+4+h>innerHeight-8?Math.max(8,r.top-h-4):r.bottom+4)+'px';}
 document.addEventListener('toggle',e=>{const d=e.target;if(!d.matches?.('details.row-menu')||!d.open)return;document.querySelectorAll('details.row-menu[open]').forEach(o=>{if(o!==d)o.open=false;});positionRowMenu(d);},true);
 document.addEventListener('click',e=>{document.querySelectorAll('details.row-menu[open]').forEach(d=>{if(!d.contains(e.target)||e.target.closest('.menu button'))d.open=false;});},true);
 document.addEventListener('scroll',()=>document.querySelectorAll('details.row-menu[open]').forEach(positionRowMenu),true);window.addEventListener('resize',()=>document.querySelectorAll('details.row-menu[open]').forEach(positionRowMenu));
 document.addEventListener('keydown',e=>{if(e.key!=='Escape'||modal)return;const d=document.querySelector('details.row-menu[open]');if(d){d.open=false;d.querySelector('summary')?.focus();}});
 async function initialize(){if(bridge){bridge.onState(next=>{state=next;updateCreationProgress();if(activeId&&!state.instances.some(x=>x.id===activeId))activeId=state.instances[0]?.id||null;render();});state=await request('snapshot');activeId=state.instances[0]?.id||null;state.instances.forEach(x=>localOpen.add(x.id));restoreUiState();await request('activate',{id:globalViews.includes(view)?null:activeId});render(true);}else{state={coreInstalled:false,instances:[{id:'preview',name:'主工作区 · 界面预览',url:'https://arena.ai/',status:'stopped',network:{mode:'direct',nodeName:''},environment:{language:'zh-CN',timezone:'Asia/Tokyo'},nodes:[],logs:[]}]};activeId='preview';localOpen.add(activeId);const notice=document.createElement('div');notice.className='notice';notice.innerHTML='<b>浏览器预览</b><span>真实浏览与代理请在新项目中运行 npm start；此预览不会启动实例。</span>';$('.app').prepend(notice);restoreUiState();render(true);}}
 initialize().catch(e=>toast(e.message));
