'use strict';
const ipBookmarkBusy=new Set(),ipSelection=new Set();
let ipSearch='',ipEditing=null,ipDraft={ip:'',note:''},ipDeletePending=[],ipManagerBusy=false,ipRowsKey='';
function ipKey(value){const ip=String(value||'').trim();try{if(ip.includes(':')){const [address,...zone]=ip.split('%');return new URL('http://['+address+']/').hostname.slice(1,-1)+(zone.length?'%'+zone.join('%'):'');}}catch{}return ip;}
function ipBookmark(ip){return state.favorites?.ips.find(x=>ipKey(x.ip)===ipKey(ip));}
async function toggleResultIP(ip,note){const key=ipKey(ip);if(ipBookmarkBusy.has(key))return;const selected=!ipBookmark(ip);ipBookmarkBusy.add(key);renderDiagnostics();try{await request('set-ip-favorite',{ip,selected,note:String(note||'').slice(0,200)});state=await request('snapshot');renderDiagnostics();toast(selected?'IP 已收藏，可在右上角 IP 收藏夹管理':'已取消 IP 收藏');}finally{ipBookmarkBusy.delete(key);renderDiagnostics();}}
function openIPBookmarks(tab='ips'){let d=$('#ipBookmarksDialog');if(!d){document.body.insertAdjacentHTML('beforeend',`<dialog id="ipBookmarksDialog" class="ip-dialog" aria-labelledby="ipBookmarksTitle"><header><div><h2 id="ipBookmarksTitle">收藏夹 <span data-favorite-total>0</span></h2><p>节点用于连接与检测 · IP 仅为地址备忘</p></div><button class="btn subtle" data-bookmark="close" aria-label="关闭收藏夹">关闭 ×</button></header><div class="favorite-tabs" role="tablist"><button class="btn soft" role="tab" data-unified="tab" data-favorite-tab="nodes">节点收藏 <span data-node-count></span></button><button class="btn soft" role="tab" data-unified="tab" data-favorite-tab="ips">IP 收藏 <span data-ip-count></span></button></div><section id="unifiedNodePanel" hidden></section><div class="ip-body" id="unifiedIPPanel"><form id="ipBookmarkForm"><div class="ip-editor-title" id="ipEditorTitle">新增地址</div><div class="ip-editor"><label class="field"><span>IPv4 / IPv6</span><input id="ipEditorIP" placeholder="例如 203.0.113.9" required autocomplete="off"></label><label class="field"><span>备注 · 最多200字</span><input id="ipEditorNote" maxlength="200" placeholder="地区、用途或节点名称"></label><button class="btn primary" id="ipSave" type="submit">保存收藏</button><button class="btn subtle" type="button" data-bookmark="new">清空 / 新增</button></div></form><div class="ip-filter"><input id="ipBookmarkSearch" aria-label="搜索IP或备注" placeholder="搜索 IP 或备注"><span id="ipBookmarkSummary"></span></div><div class="ip-batch"><button class="btn subtle tiny" data-bookmark="select">选择筛选结果</button><button class="btn subtle tiny" data-bookmark="clear">清空选择</button><button class="btn soft tiny" data-bookmark="copy-selected">复制已选 IP</button><button class="btn danger tiny" data-bookmark="delete-selected">删除已选</button></div><div id="ipDeleteConfirm" role="alert" hidden></div><div class="ip-table-scroll"><table class="logs-table ip-table"><thead><tr><th>选择</th><th>IP / 更新时间</th><th>备注</th><th>操作</th></tr></thead><tbody id="ipBookmarkRows"></tbody></table></div><p id="ipBookmarkMessage" role="status" aria-live="polite"></p></div></dialog>`);d=$('#ipBookmarksDialog');d.addEventListener('cancel',e=>{if(ipManagerBusy||unifiedBusy)e.preventDefault();});d.addEventListener('close',()=>{ipDeletePending=[];unifiedConfirm=null;});}$('#ipEditorIP').value=ipDraft.ip;$('#ipEditorNote').value=ipDraft.note;$('#ipBookmarkSearch').value=ipSearch;$('#ipBookmarkMessage').textContent='';ipRowsKey='';refreshIPBookmarks();d.showModal();setFavoriteTab(tab);if(tab==='ips')$('#ipBookmarkSearch').focus();}
function visibleIPs(){const q=ipSearch.trim().toLowerCase();return (state.favorites?.ips||[]).filter(x=>(x.ip+' '+x.note).toLowerCase().includes(q));}
function refreshIPBookmarks(){document.querySelectorAll('[data-favorite-total]').forEach(x=>x.textContent=(state.favorites?.nodes.length||0)+(state.favorites?.ips.length||0));const rows=state.favorites?.ips||[];document.querySelectorAll('[data-ip-count]').forEach(x=>x.textContent=rows.length);const body=$('#ipBookmarkRows');if(!body)return;for(const id of ipSelection)if(!rows.some(x=>x.id===id))ipSelection.delete(id);const matches=visibleIPs();$('#ipBookmarkSummary').textContent=`匹配 ${matches.length} / ${rows.length} · 已选 ${ipSelection.size}（含隐藏项）`;
 $('#ipEditorTitle').textContent=ipEditing?'编辑备注 · 地址不变':'新增地址';$('#ipEditorIP').readOnly=!!ipEditing;$('#ipSave').textContent=ipManagerBusy?'保存中…':ipEditing?'保存备注':'保存收藏';
 const key=JSON.stringify([matches,[...ipSelection],ipManagerBusy]);if(key!==ipRowsKey){ipRowsKey=key;body.innerHTML=matches.map(x=>`<tr><td><input type="checkbox" data-ip-select="${esc(x.id)}" ${ipSelection.has(x.id)?'checked':''} ${ipManagerBusy?'disabled':''} aria-label="选择 ${esc(x.ip)}"></td><td><code>${esc(x.ip)}</code><small class="library-muted">${esc(new Date(x.at).toLocaleString())}</small></td><td class="ip-note">${esc(x.note)||'<span class="library-muted">无备注</span>'}</td><td><div class="subscription-actions"><button class="btn subtle tiny" data-bookmark="copy" data-id="${esc(x.id)}">复制</button><button class="btn soft tiny" data-bookmark="edit" data-id="${esc(x.id)}">备注</button><button class="btn danger tiny" data-bookmark="delete" data-id="${esc(x.id)}">删除</button></div></td></tr>`).join('')||`<tr><td colspan="4">${rows.length?'没有匹配的 IP，试试其他关键词。':'暂无收藏。点击检测结果旁的「＋收藏」，或在上方手动添加。'}</td></tr>`;}
 const confirm=$('#ipDeleteConfirm');confirm.hidden=!ipDeletePending.length;confirm.innerHTML=ipDeletePending.length?`删除选定的 ${ipDeletePending.length} 条 IP 备忘？只删除收藏，不影响节点或实例。<div class="subscription-actions"><button class="btn danger tiny" data-bookmark="confirm-delete">确认删除 ${ipDeletePending.length} 条</button><button class="btn subtle tiny" data-bookmark="cancel-delete">取消</button></div>`:'';
 document.querySelectorAll('#unifiedIPPanel button,#ipBookmarkForm input,[data-bookmark="close"]').forEach(x=>x.disabled=ipManagerBusy);for(const action of ['copy-selected','delete-selected'])$(`[data-bookmark="${action}"]`).disabled=ipManagerBusy||!ipSelection.size;refreshUnifiedFavorites();
}
function ipMessage(text,error=false){const el=$('#ipBookmarkMessage');el.textContent=text;el.classList.toggle('error',error);}
async function ipOperation(fn){if(ipManagerBusy)return;ipManagerBusy=true;refreshIPBookmarks();try{await fn();state=await request('snapshot');refreshIPBookmarks();renderDiagnostics();}catch(e){ipMessage(e.message,true);}finally{ipManagerBusy=false;refreshIPBookmarks();}}
document.addEventListener('input',e=>{if(e.target.id==='ipEditorIP')ipDraft.ip=e.target.value;if(e.target.id==='ipEditorNote')ipDraft.note=e.target.value;if(e.target.id==='ipBookmarkSearch'){ipSearch=e.target.value;refreshIPBookmarks();}});
document.addEventListener('change',e=>{if(e.target.matches('[data-ip-select]')){const id=e.target.dataset.ipSelect;e.target.checked?ipSelection.add(id):ipSelection.delete(id);refreshIPBookmarks();}});
document.addEventListener('submit',e=>{if(e.target.id!=='ipBookmarkForm')return;e.preventDefault();ipOperation(async()=>{await request('save-ip',{ip:ipDraft.ip.trim(),note:ipDraft.note});ipEditing=null;ipDraft={ip:'',note:''};$('#ipBookmarkForm').reset();ipMessage('已保存，检测结果中的收藏状态已同步。');});});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-bookmark]');if(!b||b.disabled)return;const action=b.dataset.bookmark;if(action==='open'){openIPBookmarks();return;}if(ipManagerBusy)return;const rows=state.favorites?.ips||[],row=rows.find(x=>x.id===b.dataset.id);switch(action){case 'close':$('#ipBookmarksDialog').close();return;case 'select':visibleIPs().forEach(x=>ipSelection.add(x.id));break;case 'clear':ipSelection.clear();break;case 'edit':if(!row)return;ipEditing=row.id;ipDraft={ip:row.ip,note:row.note};$('#ipEditorIP').value=row.ip;$('#ipEditorNote').value=row.note;$('#ipEditorNote').focus();break;case 'new':ipEditing=null;ipDraft={ip:'',note:''};$('#ipBookmarkForm').reset();break;case 'copy':case 'copy-selected':await ipOperation(async()=>{const value=await request('copy-ips',{bookmarkIds:action==='copy'?[row.id]:[...ipSelection]});ipMessage(`已复制 ${value.count} 个 IP（每行一个）`);});return;case 'delete':case 'delete-selected':ipDeletePending=action==='delete'?[row.id]:[...ipSelection];break;case 'cancel-delete':ipDeletePending=[];break;case 'confirm-delete':await ipOperation(async()=>{const ids=[...ipDeletePending];await request('remove-ips',{bookmarkIds:ids});if(ids.includes(ipEditing)){ipEditing=null;ipDraft={ip:'',note:''};$('#ipBookmarkForm').reset();}ipDeletePending=[];ipMessage('已删除选定收藏，节点和实例未改变。');});return;}refreshIPBookmarks();});
