'use strict';
// Session-only drafts. Never persist unsaved environment values to instance storage.
const environmentDrafts=new Map(),environmentBases=new Map(),environmentUndo=new Map(),savingEnvironments=new Set();
let restoringEnvironment=false;
function savedEnvironmentKey(x){return JSON.stringify({network:x.network,environment:x.environment});}
function environmentFormValue(){if(!$('#environmentForm'))return null;const e={language:$('#language').value,timezone:$('#timezone').value,...readAdvancedEnvironment()};for(const k of ['width','height','scale','cpu','latitude','longitude'])e[k]=Number(e[k]);return {network:{mode:$('#networkMode').value,nodeName:$('#proxyNodeName').value},environment:e};}
function environmentChanged(){const f=environmentFormValue(),base=environmentBases.get(activeId);return !!(f&&base&&JSON.stringify(f)!==base.form);}
function captureEnvironmentDraft(){if(restoringEnvironment||view!=='environment'||!$('#environmentForm'))return;const f=environmentFormValue(),base=environmentBases.get(activeId);if(!base)return;if(JSON.stringify(f)===base.form)environmentDrafts.delete(activeId);else environmentDrafts.set(activeId,{value:f,base:environmentDrafts.get(activeId)?.base||base.saved});updateEnvironmentBar();}
function mountEnvironment(x){const draft=environmentDrafts.get(x.id);environmentBases.set(x.id,{form:JSON.stringify(environmentFormValue()),saved:savedEnvironmentKey(x)});if(draft){restoringEnvironment=true;$('#networkMode').value=draft.value.network.mode;$('#proxyNodeName').value=draft.value.network.nodeName;fillEnvironment(draft.value.environment,true);restoringEnvironment=false;}updateEnvironmentBar();}
function environmentConflict(){const draft=environmentDrafts.get(activeId),x=current();return !!(draft&&x&&draft.base!==savedEnvironmentKey(x));}
function environmentDifferences(){const base=environmentBases.get(activeId),f=environmentFormValue();if(!base||!f)return [];const old=JSON.parse(base.form);const labels={language:'语言',timezone:'时区',userAgent:'UA',platform:'平台',width:'视口宽',height:'视口高',scale:'像素比',cpu:'CPU',colorScheme:'色彩偏好',reducedMotion:'动画',geoEnabled:'定位权限',latitude:'纬度',longitude:'经度',fingerprint:'参考指纹'};const out=[];if(JSON.stringify(old.network)!==JSON.stringify(f.network))out.push('网络出口');for(const [k,name] of Object.entries(labels))if(JSON.stringify(old.environment[k])!==JSON.stringify(f.environment[k]))out.push(name);return out;}
function updateEnvironmentBar(){if(!$('#environmentForm'))return;const x=current(),dirty=environmentChanged(),busy=savingEnvironments.has(activeId),conflict=environmentConflict(),diff=environmentDifferences();const info=$('#environmentSaveInfo');if(info)info.textContent=conflict?'已保存配置已发生变化，草稿仍保留。请放弃旧草稿后重新编辑。':busy?'正在保存，请稍候…':dirty?`未保存：${diff.join('、')}。${x?.status==='running'?'保存将停止当前实例。':'保存后需启动生效。'}`:'配置已保存；只有修改后才需要保存';for(const b of document.querySelectorAll('[data-ux="save-environment"],[data-ux="save-restart"]')){b.disabled=!dirty||busy||conflict;if(b.dataset.ux==='save-environment')b.textContent=busy?'保存中…':x?.status==='running'?'保存并停止':'保存配置';else b.textContent=x?.status==='running'?'保存并重启':'保存并启动';}const discard=$('[data-ux="discard-environment"]');if(discard)discard.disabled=!dirty||busy;const undo=$('[data-fp="undo"]');if(undo)undo.disabled=!environmentUndo.has(activeId)||busy;updateFingerprintState?.();}
function showEnvironmentError(message){const root=$('#environmentSaveError');if(root){root.textContent=message;root.hidden=false;}let id=/节点|网络模式/.test(message)?'proxyNodeName':/时区/.test(message)?'timezone':/UA/.test(message)?'envUserAgent':/CPU|cpu/.test(message)?'envCpu':/视口|width|height/.test(message)?'envWidth':/经纬/.test(message)?'envLatitude':/种子/.test(message)?'fpSeed':null;const el=id&&$('#'+id);if(el){let parent=el.parentElement;while(parent){if(parent.tagName==='DETAILS')parent.open=true;parent=parent.parentElement;}el.setAttribute('aria-invalid','true');el.scrollIntoView({block:'center'});el.focus();}else root?.scrollIntoView({block:'nearest'});}
async function saveEnvironment(restart=false){const id=activeId;if(savingEnvironments.has(id))return false;captureEnvironmentDraft();if(environmentConflict()){showEnvironmentError('实例配置已改变，请先放弃旧草稿，避免覆盖新配置');return false;}if(!environmentChanged())return true;const patch=environmentFormValue();if(patch.network.mode==='mihomo'&&!current().nodes.includes(patch.network.nodeName)){showEnvironmentError('请选择已导入的代理节点；当前实例未停止');return false;}savingEnvironments.add(id);updateEnvironmentBar();try{await request('settings',{id,patch});environmentDrafts.delete(id);environmentUndo.delete(id);state=await request('snapshot');if(view==='environment'&&activeId===id)render(true);toast('配置已保存；未自动启动其他实例');if(restart){try{await request('start',{id});toast('配置已保存，当前实例已启动');}catch(e){toast('配置已保存，但启动失败：'+e.message);}}return true;}catch(e){if(view==='environment'&&activeId===id)showEnvironmentError(e.message);else toast(e.message);return false;}finally{savingEnvironments.delete(id);updateEnvironmentBar();}}
function confirmEnvironmentLeave(){captureEnvironmentDraft();if(savingEnvironments.has(activeId)){toast('当前配置正在保存，请稍候');return Promise.resolve(false);}if(!environmentChanged())return Promise.resolve(true);if(modal)return Promise.resolve(false);return new Promise(resolve=>{openModal('leave-environment');modal.leaveResolve=resolve;$('#modal .description').textContent=`「${current().name}」有未保存修改。${current().status==='running'?'保存会停止该实例。':''}留在此页可继续编辑。`;$('#modal .modal-actions').innerHTML='<button class="btn subtle" data-ux="leave-stay">继续编辑</button><button class="btn subtle" data-ux="leave-discard">放弃并离开</button><button class="btn primary" data-ux="leave-save">保存并离开</button>';});}
function finishEnvironmentLeave(yes){const resolve=modal?.leaveResolve;closeModal(true);resolve?.(yes);}
function suggestedInstanceName(){let i=1;while(state.instances.some(x=>x.name==='实例 '+i))i++;return '实例 '+i;}
function updateCreationProgress(){if(modal?.type!=='new'||!modal.busy)return;const progress=state.creationProgress;const node=$('#creationProgress');if(node)node.textContent=progress?progress.phase+'…':'正在准备创建…';}
function showCreationResult(value){const messages=[];if(value.configurationError)messages.push(value.configurationError);if(value.timezoneError)messages.push(value.timezoneError);if(value.startError)messages.push('实例已创建，但启动失败：'+value.startError);if(messages.length){openModal('creation-result',value.id);$('#modal .description').textContent=messages.join('；');$('#modal .modal-actions').innerHTML=`<button class="btn subtle" data-action="modal-close">查看实例</button><button class="btn soft" data-ux="created-config" data-id="${value.id}">修改配置</button>${value.startError&&!value.configurationError?`<button class="btn primary" data-ux="created-retry" data-id="${value.id}">重试启动</button>`:''}`;}else toast(value.started?'实例已创建并启动':'实例已创建，尚未启动');}
function relatedLogButton(id,label='查看相关日志'){return `<button class="btn tiny subtle" data-ux="related-logs" data-id="${esc(id)}">${label}</button>`;}
async function openRelatedLogs({id='all',source='all',task='all'}={}){const previous={instance:globalLogInstance,source:globalLogSource,task:globalLogTask};globalLogLevel='all';globalLogScope='all';globalLogSearch='';globalLogInstance=id;globalLogSource=source;globalLogTask=task;await route('global-logs');if(view!=='global-logs'){globalLogInstance=previous.instance;globalLogSource=previous.source;globalLogTask=previous.task;}}
document.addEventListener('input',e=>{if(e.target.closest('#environmentForm')){e.target.removeAttribute('aria-invalid');captureEnvironmentDraft();}});
document.addEventListener('change',e=>{if(e.target.closest('#environmentForm'))captureEnvironmentDraft();});
document.addEventListener('click',async event=>{const b=event.target.closest('[data-ux]');if(!b||b.disabled)return;const a=b.dataset.ux;
 if(a==='save-environment'){await saveEnvironment();return;}if(a==='save-restart'){await saveEnvironment(true);return;}
 if(a==='discard-environment'){if(savingEnvironments.has(activeId))return;environmentDrafts.delete(activeId);environmentUndo.delete(activeId);render(true);toast('已放弃草稿，恢复已保存配置');return;}
 if(a==='leave-stay'){finishEnvironmentLeave(false);return;}if(a==='leave-discard'){environmentDrafts.delete(activeId);environmentUndo.delete(activeId);finishEnvironmentLeave(true);return;}if(a==='leave-save'){modal.busy=true;$('#modal').querySelectorAll('button').forEach(b=>b.disabled=true);const success=await saveEnvironment();if(success)finishEnvironmentLeave(true);else if(modal){modal.busy=false;$('#modal .description').textContent=$('#environmentSaveError')?.textContent||'保存失败，请继续编辑后重试';$('#modal').querySelectorAll('button').forEach(b=>b.disabled=false);}return;}
 if(a==='related-logs'){if(modal)closeModal();await openRelatedLogs({id:b.dataset.id||'all',task:b.dataset.task||'all',source:b.dataset.source||'all'});return;}
 if(a==='created-config'){const id=b.dataset.id;closeModal(true);await route('environment',id);return;}
 if(a==='created-retry'){b.disabled=true;try{await request('start',{id:b.dataset.id});closeModal(true);await route('browser',b.dataset.id);}catch(e){$('#modal .description').textContent='实例已存在，重试启动失败：'+e.message;}finally{if(b.isConnected)b.disabled=false;}return;}
 if(a==='return-assigned'){await route('browser',b.dataset.id);return;}
 if(a==='instance-open'){const id=b.dataset.id;b.disabled=true;try{const x=state.instances.find(x=>x.id===id);if(x?.status!=='running')await request('start',{id});await route('browser',id);}catch(e){toast('启动失败：'+e.message);await route('browser',id);}finally{if(b.isConnected)b.disabled=false;}return;}
 if(a==='instance-config'){await route('environment',b.dataset.id);return;}
});

function showAssignmentResult(id){const x=state.instances.find(x=>x.id===id);const host=$('#libraryTaskbar')||$('#favoriteNodeRows');if(!host)return;let el=$('#assignmentResult');if(!el){el=document.createElement('div');el.id='assignmentResult';el.className='assignment-result';host.after(el);}el.innerHTML=`<span>已分配给「${esc(x?.name||id)}」，实例保持停止。</span><button class="btn soft tiny" data-ux="return-assigned" data-id="${esc(id)}">返回目标实例</button>`;}
