'use strict';
const fingerprintPresets=[["win-nvidia-qhd", "Windows · NVIDIA RTX 3070 · 2K"], ["win-nvidia-fhd", "Windows · NVIDIA RTX 3060 · 1080p"], ["win-amd-qhd", "Windows · AMD RX 6700 XT · 2K"], ["win-amd-fhd", "Windows · AMD RX 6600 · 1080p"], ["win-intel-fhd", "Windows · Intel UHD · 1080p"], ["win-intel-iris", "Windows · Intel Iris Xe · 笔记本"]];
function fingerprintFields(e){const f=e.fingerprint||{};return `<section class="fingerprint-panel"><h3>参考设备与固定随机</h3><p class="actions-note">选择预设或随机只填表，保存后生效。保存的种子跨刷新、重启固定；不会自动重抽。复制环境也复制种子，需独立组合可再次随机。</p><label><input id="fpEnabled" type="checkbox" ${f.enabled?'checked':''}> 启用参考指纹覆盖（实验性）</label><label class="field"><span>固定种子（留空首次保存生成）</span><input id="fpSeed" maxlength="64" value="${esc(f.seed||'')}"></label><div class="env-grid">${[['screenWidth','屏幕宽',1920],['screenHeight','屏幕高',1080],['availHeight','可用高度',1040],['memory','设备内存 GB（1/2/4/8）',8],['touch','最大触摸点（仅报告值）',0],['colorDepth','色深（24/30/32）',24]].map(([k,n,d])=>`<label class="field"><span>${n}</span><input id="fp-${k}" type="number" step="1" value="${f[k]??d}"></label>`).join('')}</div><div class="fp-switches">${[['hardware','屏幕 / 内存 / 触摸点报告值'],['webgl','WebGL 厂商 / 渲染器（不改变实际显卡）'],['canvas','Canvas 读取 / 导出扰动'],['audio','音频采样扰动（会修改采样数据）'],['rects','元素边界矩形扰动（可能影响定位）']].map(([k,n])=>`<label class="fp-switch"><input type="checkbox" id="fp-${k}" ${f[k]?'checked':''}> ${n}</label>`).join('')}</div><label class="field"><span>WebGL 厂商</span><input id="fp-vendor" maxlength="300" value="${esc(f.vendor||'')}"></label><label class="field"><span>WebGL 渲染器</span><input id="fp-renderer" maxlength="300" value="${esc(f.renderer||'')}"></label><p class="guide">部分影响：这些是页面主世界的API覆盖，Worker / OffscreenCanvas 等未完整覆盖，可能被检测或影响网站功能。Canvas、音频、布局和WebGL默认关闭。未改字体、TLS、真实硬件、webdriver或媒体设备ID，不承诺匿名或防检测。</p></section>`;}
function readFingerprint(){const f={enabled:$('#fpEnabled').checked,seed:$('#fpSeed').value,template:$('#fingerprintPreset').value};for(const k of ['screenWidth','screenHeight','availHeight','memory','touch','colorDepth'])f[k]=Number($('#fp-'+k).value);for(const k of ['hardware','webgl','canvas','audio','rects'])f[k]=$('#fp-'+k).checked;for(const k of ['vendor','renderer'])f[k]=$('#fp-'+k).value;return f;}
function fillFingerprint(f={}){const root=$('.fingerprint-panel');if(!root)return;root.outerHTML=fingerprintFields({fingerprint:f});if($('#fingerprintPreset'))$('#fingerprintPreset').value=f.template||'custom';}
document.addEventListener('click',async event=>{const b=event.target.closest('[data-fp]');if(!b||b.disabled)return;b.disabled=true;try{if(b.dataset.fp==='undo'){const old=environmentUndo.get(activeId);if(old){environmentUndo.delete(activeId);fillEnvironment(old);updateEnvironmentBar();}return;}if(b.dataset.fp==='native'){environmentUndo.set(activeId,environmentFormValue().environment);fillEnvironment({language:$('#language').value,timezone:$('#timezone').value});return;}if(b.dataset.fp==='timezone'){const mode=$('#networkMode').value,nodeName=$('#proxyNodeName').value,id=activeId,previousZone=$('#timezone').value;const result=await request('environment-timezone',{id,network:{mode,nodeName}});if(id!==activeId||!$('#timezone')||$('#networkMode').value!==mode||$('#proxyNodeName').value!==nodeName||$('#timezone').value!==previousZone){toast('配置已切换，已丢弃旧出口的时区查询');return;}$('#timezone').value=result.timezone;captureEnvironmentDraft();toast('时区已按出口IP填入，请保存；不会修改语言或固定定位');return;}const environment={language:$('#language').value,timezone:$('#timezone').value,...readAdvancedEnvironment()};const original=JSON.stringify(environmentFormValue()),id=activeId;const result=await request('fingerprint-preset',{preset:b.dataset.fp==='random'?'random':$('#fingerprintPreset').value,environment});if(id!==activeId||!$('#environmentForm')||JSON.stringify(environmentFormValue())!==original){toast('表单已变化，已丢弃旧的方案结果');return;}environmentUndo.set(id,environment);fillEnvironment(result);}catch(e){toast(e.message);}finally{if(b.isConnected)b.disabled=false;}});

function newNetworkFields(){return `<label class="field"><span>初始网络出口</span><select id="newSource"><option value="">本机 IP 直连</option>${(state.library||[]).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label class="field" id="newNodeField" hidden><span>复制节点到新实例</span><select id="newNode"></select></label>`;}
document.addEventListener('change',event=>{if(event.target.id!=='newSource')return;const source=state.library.find(s=>s.id===event.target.value);$('#newNodeField').hidden=!source;$('#newNode').innerHTML=(source?.nodes||[]).filter(n=>!n.hint).map(n=>`<option value="${esc(n.name)}">${esc(n.name)}</option>`).join('');});

function fingerprintPlan(e){const f=e.fingerprint||{};return `<div class="environment-plan"><div><h3>环境方案</h3><p id="fingerprintPlanSummary" class="actions-note"></p></div><div class="subscription-actions"><select id="fingerprintPreset"><option value="custom" ${!f.template||f.template==='custom'?'selected':''}>自定义 / 选择设备预设</option>${fingerprintPresets.map(([v,n])=>`<option value="${v}" ${f.template===v?'selected':''}>${n}</option>`).join('')}</select><button class="btn tiny soft" type="button" data-fp="preset">填入预设</button><button class="btn tiny primary" type="button" data-fp="random">一键随机</button><button class="btn tiny subtle" type="button" data-fp="undo" disabled>撤销上次方案修改</button><button class="btn tiny subtle" type="button" data-fp="native">使用原生方案</button></div><p class="actions-note">方案只填表，保存后才应用。随机不会修改视口、屏幕尺寸、像素比、语言、时区或固定定位。</p></div>`;}

function updateFingerprintState(){if(!$('#fpEnabled'))return;const enabled=$('#fpEnabled').checked,hardware=$('#fp-hardware').checked,webgl=$('#fp-webgl').checked;for(const k of ['hardware','webgl','canvas','audio','rects'])$('#fp-'+k).disabled=!enabled;$('#fpSeed').disabled=!enabled;for(const k of ['screenWidth','screenHeight','availHeight','memory','touch','colorDepth'])$('#fp-'+k).disabled=!enabled||!hardware;for(const k of ['vendor','renderer'])$('#fp-'+k).disabled=!enabled||!webgl;const summary=$('#fingerprintPlanSummary');if(summary){const platform=$('#envPlatform').value||'原生平台',width=Number($('#envWidth').value);summary.textContent=`${platform} · ${width?width+' × '+$('#envHeight').value:'自适应视口'} · CPU ${Number($('#envCpu').value)||'原生'} · 参考覆盖${enabled?'开启':'关闭'}（表单值，保存并启动后生效）`;}}
