'use strict';
let favoriteTargetId='';
let globalLogLevel='all',globalLogScope='all',globalLogInstance='all',globalLogSearch='',globalLogSource='all',globalLogTask='all';
let globalLogTab='operations',runtimeWindowVisible=true;
let runtimeOutputChannel='all',runtimeOutputSearch='',runtimeOutputTimer=null,runtimeOutputPendingRoot=null,runtimeOutputRenderedRoot=null,runtimeOutputSignature='';
function systemLogTabs(){return '<div class="system-log-toolbar"><div class="segments system-log-tabs" role="group" aria-label="日志类型">'+[['operations','操作记录'],['debug','调试输出']].map(([key,label])=>'<button type="button" data-log-tab="'+key+'" aria-pressed="'+(globalLogTab===key)+'" class="'+(globalLogTab===key?'active':'')+'">'+label+'</button>').join('')+'</div><button type="button" class="btn soft" data-work="feedback" title="打开项目 GitHub Issues">反馈问题 '+icon('arrow')+'</button></div>';}
function stopRuntimeOutputRefresh(){clearInterval(runtimeOutputTimer);runtimeOutputTimer=null;}
function syncRuntimeOutputRefresh(){const active=view==='global-logs'&&globalLogTab==='debug'&&runtimeWindowVisible&&document.visibilityState==='visible';if(!active){stopRuntimeOutputRefresh();return;}if(!runtimeOutputTimer)runtimeOutputTimer=setInterval(()=>{if(view==='global-logs'&&globalLogTab==='debug'&&runtimeWindowVisible&&document.visibilityState==='visible')runtimeOutputRows();},1500);}
window.facet?.onWindowVisibility?.(visible=>{runtimeWindowVisible=visible;syncRuntimeOutputRefresh();if(visible&&view==='global-logs'&&globalLogTab==='debug')runtimeOutputRows();});
document.addEventListener('visibilitychange',()=>{syncRuntimeOutputRefresh();if(view==='global-logs'&&globalLogTab==='debug'&&document.visibilityState==='visible')runtimeOutputRows();});
window.addEventListener('beforeunload',stopRuntimeOutputRefresh);
document.addEventListener('click',event=>{const button=event.target.closest('[data-log-tab]');if(!button||view!=='global-logs'||!['operations','debug'].includes(button.dataset.logTab)||globalLogTab===button.dataset.logTab)return;globalLogTab=button.dataset.logTab;render(true);});
function runtimeOutputPage(){$('#content').innerHTML=`${systemLogTabs()}<div class="section-intro"><div><p>显示本次应用运行的调试输出，包括实例启动、停止、页面错误和代理操作，以及应用进程的标准输出和错误输出；最多保留最近 1000 行，凭据和网址自动脱敏。每 1.5 秒自动刷新，离开或最小化后暂停。“操作记录”保留跨重启历史；此处不汇总网页控制台及代理内核的完整输出。</p><div class="subscription-actions"><label class="field"><span>通道</span><select id="runtimeOutputChannel"><option value="all">全部</option><option value="stdout">标准输出</option><option value="stderr">错误输出</option></select></label><label class="field"><span>搜索</span><input id="runtimeOutputSearch" value="${esc(runtimeOutputSearch)}" placeholder="错误、扩展、网络"></label><button class="btn soft" type="button" data-runtime-action="refresh">刷新输出</button></div></div></div><p id="runtimeOutputWarning" class="error"></p><div id="runtimeOutputRows"></div>`;$('#runtimeOutputChannel').value=runtimeOutputChannel;runtimeOutputRows();}
async function runtimeOutputRows(){
 const root=$('#runtimeOutputRows');if(!root||runtimeOutputPendingRoot===root)return;
 runtimeOutputPendingRoot=root;if(runtimeOutputRenderedRoot!==root)root.innerHTML='<p class="actions-note">正在读取调试输出…</p>';
 try{
  const value=await request('runtime-output');if(!root.isConnected||$('#runtimeOutputRows')!==root)return;
  const rows=(value?.rows||[]).filter(x=>(runtimeOutputChannel==='all'||x.channel===runtimeOutputChannel)&&String(x.text||'').toLowerCase().includes(runtimeOutputSearch.toLowerCase())),signature=JSON.stringify([rows,value?.warning||'',value?.rows?.length||0]);
  $('#runtimeOutputWarning').textContent=value?.warning||'';if(runtimeOutputRenderedRoot===root&&runtimeOutputSignature===signature)return;
  const table=root.querySelector('.library-table'),scrollTop=table?.scrollTop||0,scrollLeft=table?.scrollLeft||0;
  root.innerHTML=`<p class="actions-note">匹配 ${rows.length} 行${value?.rows?.length?' · 最近最多 1000 行':''}</p><div class="library-table"><table class="logs-table"><thead><tr><th>时间</th><th>通道</th><th>输出</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.time?new Date(x.time).toLocaleString():'')}</td><td>${x.channel==='stderr'?'错误输出':'标准输出'}</td><td><code>${esc(x.text)}</code></td></tr>`).join('')||'<tr><td colspan="3">暂无匹配的调试输出</td></tr>'}</tbody></table></div>`;
  const next=root.querySelector('.library-table');if(next){next.scrollTop=scrollTop;next.scrollLeft=scrollLeft;}runtimeOutputRenderedRoot=root;runtimeOutputSignature=signature;
 }catch(e){if(root.isConnected&&$('#runtimeOutputRows')===root){$('#runtimeOutputWarning').textContent=e.message;runtimeOutputRenderedRoot=null;}}
 finally{if(runtimeOutputPendingRoot===root)runtimeOutputPendingRoot=null;}
}
function favoriteExists(sourceId,name){return !!state.favorites?.nodes.some(n=>n.sourceId===sourceId&&n.name===name);}
function favoritesPage(){if($('#favoriteTarget'))favoriteTargetId=$('#favoriteTarget').value;if(!state.instances.some(x=>x.id===favoriteTargetId))favoriteTargetId=activeId||state.instances[0]?.id||'';$('#content').innerHTML=`<div class="section-intro"><div><h2>常用节点收藏</h2><p>收藏的节点可分配给实例。IP 地址收藏已移至代理管理右上角。</p></div></div><section class="settings-card full"><h3>常用节点</h3><div class="inner"><label class="field"><span>分配给实例</span><select id="favoriteTarget">${state.instances.map(x=>`<option value="${x.id}" ${x.id===favoriteTargetId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div id="favoriteNodeRows"></div></div></section>`;favoriteNodeRows();}
function favoriteNodeRows(){const el=$('#favoriteNodeRows');if(!el)return;el.innerHTML=`<div class="library-table"><table class="logs-table"><thead><tr><th>节点 / 订阅</th><th>最近检测出口 IP</th><th>操作</th></tr></thead><tbody>${(state.favorites?.nodes||[]).map(n=>{const ip=state.diagnostics?.results.find(r=>r.sourceId===n.sourceId&&r.name===n.name&&r.kind==='ip'&&r.ok);return `<tr><td>${esc(n.name)}<small class="library-muted">${esc(n.sourceName)}${n.available?'':' · 不可用/已删除'}</small></td><td>${esc(ip?.ip||'尚未查询')}<small class="library-muted">${ip?esc(new Date(ip.at).toLocaleString()):''}</small></td><td><button class="btn tiny soft" data-work="assign-favorite" data-source="${n.sourceId}" data-name="${esc(n.name)}" ${n.available?'':'disabled'}>分配</button><button class="btn tiny subtle" data-work="locate-favorite" data-source="${n.sourceId}" data-name="${esc(n.name)}" ${n.available?'':'disabled'}>定位节点</button><button class="btn tiny danger" data-work="unfavorite" data-source="${n.sourceId}" data-name="${esc(n.name)}">取消收藏</button></td></tr>`;}).join('')||'<tr><td colspan="3">在节点表点击 ☆ 收藏常用线路</td></tr>'}</tbody></table></div>`;}
function globalLogsPage(){if(globalLogTab==='debug'){runtimeOutputPage();return;}$('#content').innerHTML=`${systemLogTabs()}<div class="section-intro"><p>保留最近 1000 条脱敏记录，跨重启保存，自动淘汰旧记录。不记录网页内容、订阅 URL 或代理凭证。</p><div class="subscription-actions"><button class="btn soft" data-work="copy-summary">复制诊断摘要</button><button class="btn subtle" data-work="export-logs">导出全部日志</button></div></div><div class="library-form"><label class="field"><span>级别</span><select id="globalLogLevel">${['all','INFO','WARN','ERROR'].map(x=>`<option ${x===globalLogLevel?'selected':''} value="${x}">${x==='all'?'全部级别':x}</option>`).join('')}</select></label><label class="field"><span>范围</span><select id="globalLogScope">${[['all','全部范围'],['application','应用'],['instance','实例'],['subscription','订阅'],['diagnostic','检测']].map(([v,l])=>`<option value="${v}" ${v===globalLogScope?'selected':''}>${l}</option>`).join('')}</select></label><label class="field"><span>实例</span><select id="globalLogInstance"><option value="all">全部实例</option>${state.instances.map(x=>`<option value="${x.id}" ${x.id===globalLogInstance?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label class="field"><span>订阅 / 节点源</span><select id="globalLogSource"><option value="all">全部来源</option>${[...new Set((state.events||[]).map(x=>x.sourceId).filter(Boolean))].map(id=>`<option value="${esc(id)}" ${id===globalLogSource?'selected':''}>${esc(state.library?.find(s=>s.id===id)?.name||id)}</option>`).join('')}</select></label><label class="field"><span>检测任务</span><select id="globalLogTask"><option value="all">全部任务</option>${[...new Set((state.events||[]).map(x=>x.taskId).filter(Boolean))].map(id=>`<option value="${esc(id)}" ${id===globalLogTask?'selected':''}>${esc(id)}</option>`).join('')}</select></label><label class="field"><span>搜索</span><input id="globalLogSearch" value="${esc(globalLogSearch)}" placeholder="错误原因 / 状态"></label></div><p id="globalLogWarning" class="error"></p><button class="btn tiny subtle" data-work="reset-log-filters">清除筛选</button><div id="globalLogRows"></div>`;globalLogRows();}
function globalLogRows(){refreshLogFilters();const root=$('#globalLogRows');if(!root)return;$('#globalLogWarning').textContent=state.logWarning||'';const rows=(state.events||[]).filter(x=>(globalLogLevel==='all'||x.level===globalLogLevel)&&(globalLogScope==='all'||x.scope===globalLogScope)&&(globalLogInstance==='all'||x.instanceId===globalLogInstance)&&(globalLogSource==='all'||x.sourceId===globalLogSource)&&(globalLogTask==='all'||x.taskId===globalLogTask)&&[x.text,x.nodeName,x.taskId,x.sourceId].join(' ').toLowerCase().includes(globalLogSearch.toLowerCase()));root.innerHTML=`<p class="actions-note">匹配 ${rows.length} 条 · 应用 ${esc(state.versions?.app||'')} / Electron ${esc(state.versions?.electron||'')}</p><div class="library-table"><table class="logs-table"><thead><tr><th>时间</th><th>范围 / 实例</th><th>级别</th><th>事件</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(new Date(x.time).toLocaleString())}</td><td>${esc({application:'应用',instance:'实例',subscription:'订阅',diagnostic:'检测'}[x.scope]||x.scope)}<small class="library-muted">${esc(state.instances.find(n=>n.id===x.instanceId)?.name||x.instanceId||'全局')}</small></td><td>${esc(x.level)}</td><td>${esc(x.text)}${x.nodeName?`<small class="library-muted">节点：${esc(x.nodeName)}</small>`:''}${x.taskId?`<small class="library-muted">任务 ${esc(x.taskId)}</small>`:''}</td></tr>`).join('')||'<tr><td colspan="4">没有匹配记录</td></tr>'}</tbody></table></div>`;}
function instanceDetails(x){const e=x.environment,assignment=x.assignment||{},ip=state.diagnostics?.results.find(r=>r.sourceId===assignment.sourceId&&r.name===assignment.name&&r.kind==='ip'&&r.ok);
 const groups=[['网络',[['网络模式',networkText(x)],['节点来源',x.network.mode==='direct'?'不使用代理':assignment.sourceName||'本地副本 / 未关联'],['配置同步',x.network.mode==='direct'?'直连模式，不应用代理副本':assignment.status||'未关联来源'],['最近检测 IP',ip?ip.ip+'（'+new Date(ip.at).toLocaleString()+'，非实时）':'尚未查询']]],
  ['环境',[['语言 / 时区',envText(x)],['视口 / 像素比',e.width?`${e.width} × ${e.height} / ${e.scale||'原生'}`:'自适应 / '+(e.scale||'原生')],['UA / 平台',`${e.userAgent?'自定义':'原生'} / ${e.platform||'原生'}`],['CPU / 媒体偏好',`${e.cpu||'原生'} / ${e.colorScheme||'system'} / ${e.reducedMotion||'system'}`],['参考指纹',e.fingerprint?.enabled?'已启用 · '+(e.fingerprint.template||'自定义')+' · 固定种子':'原生 / 未启用'],['地理位置',e.geoEnabled?'固定位置（已允许网页获取）':'默认拒绝']]],
  ['状态',[['实例状态',statusText(x)],['网页状态',x.status==='running'?(x.pageState||'尚未加载'):'当前未打开网页'+(x.lastLoadedAt?'；上次加载成功：'+new Date(x.lastLoadedAt).toLocaleString():'')],['当前错误',x.error||'暂无'],['历史错误',x.lastError?(x.lastErrorAt?new Date(x.lastErrorAt).toLocaleString()+' · ':'')+x.lastError:'暂无']]]];
 const tone=(k,v)=>(k==='当前错误'||k==='历史错误')&&v!=='暂无'?' class="warn"':'';
 return `<div class="instance-details"><div class="details-head"><span class="details-symbol">${icon('browser')}</span><div class="details-title"><h2 title="${esc(x.name)}">${esc(x.name)}</h2><p>${x.status==='starting'?'正在启动…':'未运行'} · 独立持久会话 · 启动后才连接网页</p></div><div class="subscription-actions">${relatedLogButton(x.id)}<button class="btn" data-view="environment">编辑环境</button><button class="btn primary" data-action="toggle" ${x.status==='starting'?'disabled':''}>${icon('play')}${x.status==='starting'?'启动中…':'启动这个实例'}</button></div></div><div class="details-groups">${groups.map(([title,rows])=>`<section><h3>${title}</h3><dl>${rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd${tone(k,v)} title="${esc(v)}">${esc(v)}</dd></div>`).join('')}</dl></section>`).join('')}</div><p class="actions-note">${icon('info')}${x.network.mode==='direct'?'将使用本机实际出口。':'只使用已分配的节点副本，失败不回退直连。'}检测 IP 仅代表上次检测时的出口，不能保证启动后不变。</p></div>`;}
function advancedEnvironment(x){const e=x.environment;return `<details class="advanced-environment"><summary>高级环境设置（自定义前请阅读兼容性说明）</summary><div class="guide">修改 UA / platform 不会改变真实操作系统、GPU或TLS实现。下方可选图形覆盖仅影响部分页面API。自定义时清空 UA-CH 元数据，避免继续发送矛盾的原生平台信息，但可能影响网站兼容性。固定视口将等比缩放至浏览区域，可能使文字变小；宽高均为0时随窗口自适应。屏幕报告值与网页视口不是同一参数。</div><div class="subscription-actions"><button type="button" class="btn tiny soft" data-work="env-preset" data-preset="native">恢复默认</button><button type="button" class="btn tiny subtle" data-work="env-preset" data-preset="ja">日语 / 东京</button><button type="button" class="btn tiny subtle" data-work="env-preset" data-preset="en">英语 / UTC</button></div><label class="field"><span>复制其他实例的环境（保存后生效）</span><select id="environmentCopy"><option value="">选择实例</option>${state.instances.filter(n=>n.id!==x.id).map(n=>`<option value="${n.id}">${esc(n.name)}</option>`).join('')}</select></label><label class="field"><span>User-Agent（留空保留原生）</span><input id="envUserAgent" maxlength="512" value="${esc(e.userAgent||'')}" placeholder="高级自定义 UA"></label><label class="field"><span>navigator.platform</span><select id="envPlatform">${['','Win32','MacIntel','Linux x86_64'].map(p=>`<option value="${p}" ${p===(e.platform||'')?'selected':''}>${p||'原生'}</option>`).join('')}</select></label><div class="env-grid">${[['Width','视口宽度（0=自适应）',e.width||0],['Height','视口高度（0=自适应）',e.height||0],['Scale','像素比（0=原生，1–3）',e.scale||0],['Cpu','CPU逻辑线程数（0=原生，1–64）',e.cpu||0]].map(([id,label,v])=>`<label class="field"><span>${label}</span><input id="env${id}" type="number" min="0" step="${id==='Scale'?'any':'1'}" value="${v}"></label>`).join('')}<label class="field"><span>色彩偏好</span><select id="envColorScheme">${['system','light','dark'].map(v=>`<option value="${v}" ${v===e.colorScheme?'selected':''}>${{system:'跟随系统',light:'浅色',dark:'深色'}[v]}</option>`).join('')}</select></label><label class="field"><span>动画偏好</span><select id="envReducedMotion">${['system','reduce','no-preference'].map(v=>`<option value="${v}" ${v===e.reducedMotion?'selected':''}>${{system:'跟随系统',reduce:'减少动画','no-preference':'无特殊偏好'}[v]}</option>`).join('')}</select></label></div><label><input type="checkbox" id="envGeoEnabled" ${e.geoEnabled?'checked':''}> 允许网页获取下方固定地理位置（默认关闭）</label><div class="env-grid"><label class="field"><span>纬度 -90～90</span><input id="envLatitude" type="number" step="any" value="${e.latitude||0}"></label><label class="field"><span>经度 -180～180</span><input id="envLongitude" type="number" step="any" value="${e.longitude||0}"></label></div><p id="environmentWarnings" class="error"></p><p class="actions-note">WebRTC 非代理 UDP 始终受限；摄像头、麦克风等其他权限保持拒绝。额外的硬件与图形覆盖见下方实验性选项。字体与真实硬件仍保留原生。改动在保存并重新启动后生效。</p>${fingerprintFields(e)}</details>`;}
function readAdvancedEnvironment(){return {fingerprint:readFingerprint(),userAgent:$('#envUserAgent').value,platform:$('#envPlatform').value,width:$('#envWidth').value,height:$('#envHeight').value,scale:$('#envScale').value,cpu:$('#envCpu').value,colorScheme:$('#envColorScheme').value,reducedMotion:$('#envReducedMotion').value,geoEnabled:$('#envGeoEnabled').checked,latitude:$('#envLatitude').value,longitude:$('#envLongitude').value};}
function fillEnvironment(e,quiet=false){fillFingerprint(e.fingerprint);const language=$('#language'),locale=e.language||'zh-CN';if(![...language.options].some(o=>o.value===locale))language.add(new Option(locale,locale));language.value=locale;$('#timezone').value=e.timezone||'Asia/Tokyo';for(const [id,key]of [['UserAgent','userAgent'],['Platform','platform'],['Width','width'],['Height','height'],['Scale','scale'],['Cpu','cpu'],['ColorScheme','colorScheme'],['ReducedMotion','reducedMotion'],['Latitude','latitude'],['Longitude','longitude']])$('#env'+id).value=e[key]??(['colorScheme','reducedMotion'].includes(key)?'system':['userAgent','platform'].includes(key)?'':0);$('#envGeoEnabled').checked=!!e.geoEnabled;environmentWarnings();if(!quiet){captureEnvironmentDraft();toast('已填入环境，请检查后保存；不会自动修改实例');}}
document.addEventListener('click',async event=>{const b=event.target.closest('[data-work]');if(!b||b.disabled)return;const action=b.dataset.work;try{if(action==='feedback'){b.disabled=true;await request('open-feedback');return;}if(action==='reset-log-filters'){globalLogLevel=globalLogScope=globalLogInstance=globalLogSource=globalLogTask='all';globalLogSearch='';globalLogsPage();return;}if(action==='env-preset'){fillEnvironment(b.dataset.preset==='ja'?{language:'ja-JP',timezone:'Asia/Tokyo'}:b.dataset.preset==='en'?{language:'en-US',timezone:'UTC'}:{});return;}if(action==='assign-favorite'){const id=$('#favoriteTarget').value;if(!id)throw Error('请先创建实例');libraryConfirm('分配收藏节点？',`将「${b.dataset.name}」分配给「${state.instances.find(x=>x.id===id)?.name}」，切换为代理模式并停止该实例；请随后手动启动。其他实例不变。`,'library-assign',{id,sourceId:b.dataset.source,name:b.dataset.name});return;}if(action==='locate-favorite'){librarySource=b.dataset.source;librarySearch=b.dataset.name;libraryPageIndex=0;librarySelected.clear();await route('proxies');return;}b.disabled=true;if(action==='unfavorite')await request('favorite-node',{sourceId:b.dataset.source,name:b.dataset.name});else if(action==='copy-summary'){await request('copy-summary');toast('脱敏诊断摘要已复制');return;}else if(action==='export-logs'){const value=await request('export-logs');if(!value?.cancelled)toast('日志已导出');return;}render(true);}catch(e){toast(e.message);}finally{if(b.isConnected)b.disabled=false;}});
document.addEventListener('change',event=>{const id=event.target.id;if(id==='favoriteTarget')favoriteTargetId=event.target.value;if(id==='environmentCopy'){const x=state.instances.find(x=>x.id===event.target.value);if(x)fillEnvironment(x.environment);}if(id==='globalLogSource')globalLogSource=event.target.value;if(id==='globalLogTask')globalLogTask=event.target.value;if(id==='globalLogLevel')globalLogLevel=event.target.value;if(id==='globalLogScope')globalLogScope=event.target.value;if(id==='globalLogInstance')globalLogInstance=event.target.value;if(id.startsWith('globalLog'))globalLogRows();});
document.addEventListener('input',event=>{if(event.target.id==='globalLogSearch'){globalLogSearch=event.target.value;globalLogRows();}});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-runtime-action="refresh"]');if(!button)return;button.disabled=true;try{await runtimeOutputRows();}finally{button.disabled=false;}});
document.addEventListener('change',event=>{if(event.target.id==='runtimeOutputChannel'){runtimeOutputChannel=event.target.value;runtimeOutputRows();}});
document.addEventListener('input',event=>{if(event.target.id==='runtimeOutputSearch'){runtimeOutputSearch=event.target.value;runtimeOutputRows();}});

function environmentWarnings(){const root=$('#environmentWarnings');if(!root)return;const ua=$('#envUserAgent').value,p=$('#envPlatform').value,warnings=[];if(ua&&p&&(/Windows/i.test(ua)&&p!=='Win32'||/Macintosh|Mac OS X/i.test(ua)&&p!=='MacIntel'||/Linux/i.test(ua)&&p!=='Linux x86_64'))warnings.push('UA与platform标识可能矛盾，请核对。');if(p&&!ua)warnings.push('已修改platform但UA仍为原生，可能暴露不同平台信息。');if($('#envGeoEnabled').checked)warnings.push('固定定位不会同步修改出口IP所在地或时区，请自行保持一致。');root.textContent=warnings.join(' ');}
document.addEventListener('input',event=>{if(event.target.id.startsWith('env'))environmentWarnings();});document.addEventListener('change',event=>{if(event.target.id.startsWith('env'))environmentWarnings();});

function readableTask(id){const events=state.events||[],e=events.find(e=>e.taskId===id&&e.text.startsWith('开始'))||events.find(e=>e.taskId===id);return e?new Date(e.time).toLocaleTimeString()+' · '+e.text.replace('latency','连通性').replace('speed','测速').replace('ip检测','IP检测'):id;}
function refreshLogFilters(){const configs=[['globalLogTask',globalLogTask,'全部任务',(state.events||[]).map(e=>e.taskId).filter(Boolean),readableTask],['globalLogSource',globalLogSource,'全部来源',(state.events||[]).map(e=>e.sourceId).filter(Boolean),id=>state.library?.find(x=>x.id===id)?.name||'已移除来源 · '+id.slice(0,8)],['globalLogInstance',globalLogInstance,'全部实例',state.instances.map(x=>x.id),id=>state.instances.find(x=>x.id===id)?.name||'已删除实例 · '+id.slice(0,8)]];for(const [key,selected,all,ids,label]of configs){const el=$('#'+key);if(!el)continue;const values=[...new Set(ids)];if(selected!=='all'&&!values.includes(selected))values.push(selected);const html=`<option value="all">${all}</option>`+values.map(id=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(label(id))}</option>`).join('');if(el.innerHTML!==html)el.innerHTML=html;el.value=selected;}}
